### ISSUE TITLE
感谢和尊敬作者，在此推荐一款同类型的桌面应用 AI0x0

### ISSUE THREAD

**Issue by mushan0x0** [openai-translator/openai-translator#1009]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

[AI0x0](https://github.com/mushan0x0/AI0x0.com) 推荐

### 描述 Motivation

非常感谢作者开源的这个项目，非常优秀，但因为桌面端前期由 electron 切换为了 tauri 这个不成熟的框架导致了很多问题。

所以我在此推荐我开发的项目 [AI0x0](https://github.com/mushan0x0/AI0x0.com) ，虽然没有开源但也小有名气，而且是可以填 key 或者登录 ChatGPT 等页面免费使用的。

这个项目从今年初开始立项，花了我很多心血，也解决了很多包括兼容性或者类似于划词这种极具挑战性的功能，故此没有开源，但可以免费使用也算是非常良心了。

### 特色功能非常多，包括写作：

https://github.com/openai-translator/openai-translator/assets/29084441/a95fb900-517f-4b02-b998-732675b08d20

### 或者一键翻译：

https://github.com/openai-translator/openai-translator/assets/29084441/b6c5b35e-c305-4906-91f7-2d0f22b5ad9d

### 还有不同的桌面外观，支持众多模型：

<img width="315" alt="image" src="https://github.com/openai-translator/openai-translator/assets/29084441/18572089-0ca9-49eb-9b9b-6ce9087446ff">

<img width="446" alt="image" src="https://github.com/openai-translator/openai-translator/assets/29084441/381a00fe-7060-47aa-8a05-8d409ca58f1b">

## 衷心感谢作者和开源社区的无私付出和努力

我本人也参与和资金资助过众多开源项目，我的翻译工具预设包里的单词查询 prompt 也是参考该项目实现的，再次感谢🙏。

https://github.com/openai-translator/openai-translator/assets/29084441/eefe85bf-3158-499c-86e4-41558259b94b

包括作者在框架选择上选择了 tauri 这么不成熟和这么激进的框架，我觉得 openai-translator 应该算是 tauri 的具有代表作品之一了，为其生态或者建设带来了很大帮助，这也是伟大的开源精神！我在此并不贬低 tauri 或者该项目所带来的伟大开源力量！

感谢，致敬

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
在我这边打广告，不太合适吧。。。

**Comment by mushan0x0** [comment]
@yetone  我在 twitter 回了很多条信息怕你没看见，昨天捐赠的 1000 是用于你买 Win 电脑做适配的，我也是看到你发推说需要自费买电脑才想到发广告的，我本来也考虑了很久，因为我们是同类软件，但是你是开源的社区软件，有很多用户还是希望用开源的，所以还是发了这个广告，我资助 https://github.com/Yidadaa/ChatGPT-Next-Web 了好几千，也是用的捐赠，然后作者答应在 README 里放了我的链接，不过你可以开放 README 广告位，这样获得的捐赠应该会更多一些。

给你带来困扰了我很抱歉🙏，昨天我给的捐赠不用退回了，是我本来就决定捐赠的，开源不易，谢谢！

**Comment by yetone** [comment]
@mushan0x0 
<img width="540" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/0a48f3ff-7dd2-49bc-89d8-fe99b06a9f4f">

**Comment by mushan0x0** [comment]
谢谢 @yetone 的中肯看法，这件事确实是我做的不对，十分抱歉 @yetone 🙏

**Comment by mushan0x0** [comment]
<img width="597" alt="image" src="https://github.com/openai-translator/openai-translator/assets/29084441/dd25acba-0f4e-4ac7-a959-19557126b7c3">

**Comment by yetone** [comment]
你的目的也达到了，你的项目也已成功完成了曝光，这个 issue 可以 lock 了 🤮
