### ISSUE TITLE
[Bug] 感觉翻译的很生硬，举一个例子对比：

### ISSUE THREAD

**Issue by toyo2333** [openai-translator/openai-translator#1014]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.88

### 系统/浏览器版本 System/Browser version

windows11

### 复现步骤 Reproduce step

翻译这段中文为英文：
科技股下跌周五拖累了标普500指数，缩窄了该大盘指数近期的涨幅，令其本周走软。周五，标普500指数下跌1.2%，纳斯达克综合指数下跌1.6%。道琼斯指数下跌约289点，跌幅0.8%。

### 你看到了什么错误？What errors do you see?

翻译结果如下
`Technology stocks fell on Friday, dragging down the S&P 500 index and narrowing its recent gains, causing it to weaken this week. On Friday, the S&P 500 index fell by 1.2%, while the Nasdaq Composite Index dropped by 1.6%. The Dow Jones Industrial Average declined by approximately 289 points, a decrease of 0.8%.`

作为 对比deepL网页版的翻译如下
`Falling tech stocks weighed on the S&P 500 on Friday, narrowing the broader index's recent gains and leaving it weaker for the week. On Friday, the S&P 500 fell 1.2% and the Nasdaq Composite lost 1.6%. The Dow Jones fell about 289 points, or 0.8 percent.`

简单来说，后者的用词更地道。或者说言简意赅。尤其是第一句，用过了weighed承压这样的词汇。而openAI给的翻译，像口语口水话，像chinglish，有点“逐字翻译”的感觉。

请问这是提示词的问题还是什么原因？

### 你期望看到什么？What did you expect to see?

希望openAI的翻译能更地道。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by devyujie** [comment]
赞同，写作功能的中译英翻译的有点幼稚

**Comment by caomeizhibo** [comment]
没找到设置按钮在哪

**Comment by ricklei2777** [comment]
这个确实，提示词还是写的不够好。
