### ISSUE TITLE
[Bug] {{运行后窗口一闪而退.}}

### ISSUE THREAD

**Issue by Ihix** [openai-translator/openai-translator#1050]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.89

### 系统/浏览器版本 System/Browser version

windows 1909 (18363.778)

### 复现步骤 Reproduce step

![explorer_x7jMpQZoSl](https://github.com/openai-translator/openai-translator/assets/26695081/f1b6a34c-3cb3-4d5b-a12d-41df9da37f22)

### 你看到了什么错误？What errors do you see?

开启后窗口闪退.

### 你期望看到什么？What did you expect to see?

正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by luolongfei** [comment]
遇到同样的问题

**Comment by GGabirel** [comment]
The same bug exists on the latest openai_translator 0.3.8 with Windows 10 22H2,
**which can be mitigated by running the exe from cmd**.

![Snipaste_2024-01-01_16-17-16](https://github.com/openai-translator/openai-translator/assets/118699236/b3788b37-3032-48a1-8f8d-05c160f284ea)

That should work. I'm planning to look into it when available.

**Comment by ntdsir** [comment]
我也遇到了一样的问题，升级最新版问题依旧。

**Comment by GGabirel** [comment]
> 我也遇到了一样的问题，升级最新版问题依旧。

Consider running openai translator in different ways, e.g. by **double click/running from cmd/right click**, which may mitigate this problem.
I suppose this crash is relevant with the parent process (cmd.exe/explorer.exe), which encourages further debugging:)

**Comment by yetone** [comment]
抱歉，最新版已经彻底解决闪退问题。

**Comment by LJZ20** [comment]
我尝试下载了[OpenAI.Translator_0.3.32_x64_en-US.msi](https://github.com/openai-translator/openai-translator/releases/download/v0.3.32/OpenAI.Translator_0.3.32_x64_en-US.msi)和[OpenAI.Translator_0.3.31_x64_en-US.msi](https://github.com/openai-translator/openai-translator/releases/download/v0.3.31/OpenAI.Translator_0.3.31_x64_en-US.msi)都发现了同样的问题，无法正常运行？
