### ISSUE TITLE
[Bug] Azure API的说明文档中需要针对0613模型进行更新

### ISSUE THREAD

**Issue by smile-xuc** [openai-translator/openai-translator#1061]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.38

### 系统/浏览器版本 System/Browser version

macOS 14.0/Chrome 版本 118.0.5993.117（正式版本） (x86_64)

### 复现步骤 Reproduce step

现有关于Azure API的配置说明如下，
const API_URL = `https://${resourceName}.openai.azure.com`
const API_URL_PATH = `/openai/deployments/${deployName}/completions?api-version=${apiVersion}`

这爱之前Azure的模型里使用是正常的，
但最近Azure更新0613模型后，这个写法就失效了。
需要在URL_PATH的deployname之后加上/chat/，即把第二行改为：
const API_URL_PATH = `/openai/deployments/${deployName}/chat/completions?api-version=${apiVersion}`

### 你看到了什么错误？What errors do you see?

如果不改写，会报错error 无法在此模型下工作。

### 你期望看到什么？What did you expect to see?

更新wiki

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by SuperPhant** [comment]
我用“const API_URL_PATH = /openai/deployments/${deployName}/chat/completions?api-version=${apiVersion}”这个格式也不行啊，报错“resource not found”。

**Comment by smile-xuc** [comment]
> ${deployName}

你把${deployName}换成你部署的名称了不？

**Comment by lovelywanz** [comment]
model name: gpt-4
设置里面设置：
API URL：
https://********.openai.azure.com
API_URL_PATH
/openai/deployments/gpt-4/chat/completions?api-version=0613

报错resource not found

**Comment by IVSpretender** [comment]
> model name: gpt-4 设置里面设置： API URL： https://********.openai.azure.com API_URL_PATH /openai/deployments/gpt-4/chat/completions?api-version=0613
> 
> 报错resource not found

${deployName}处要写的不是模型名称，而是部署名。
![image](https://github.com/openai-translator/openai-translator/assets/92420468/40bd891a-457f-4912-a48a-efcadb406933)

**Comment by github-pigsy** [comment]
> > ${deployName}
> 
> 你把${deployName}换成你部署的名称了不？

感谢，已经搞好了，原来是这里出问题。我还以为是模型版本不对
