### ISSUE TITLE
添加新的 API 模型 Add new API models

### ISSUE THREAD

**Issue by JackerGamer** [openai-translator/openai-translator#1077]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Feature

[New models and developer products announced at DevDay](https://openai.com/blog/new-models-and-developer-products-announced-at-devday)
[gpt-3.5-turbo-1106](https://platform.openai.com/docs/models/gpt-3-5)
[gpt-4-1106-preview](https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo)

### Are you willing to submit a PR?

- [X] 我愿意提供 PR!
I'm willing to submit a PR!

**Comment by AreChen** [comment]
同求!
