### ISSUE TITLE
[Bug] 升级后提示 Unknown error

### ISSUE THREAD

**Issue by brucmao** [openai-translator/openai-translator#1093]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.94

### 系统/浏览器版本 System/Browser version

win11 22H2

### 复现步骤 Reproduce step

0.0.90 正常
从 0.0.90 升级到0.0.94 后翻译任何文本提示 Unknown error，发现0.0.93也是同样的错误

### 你看到了什么错误？What errors do you see?

Unknown error

### 你期望看到什么？What did you expect to see?

升级后能翻译

### 还有其他的内容吗？Anything else?

用的Azure OpenAI ，模型名称：gpt-35-turbo ，模型版本：0613
OpenAI Translator API Model 选择gpt-3.5-trubo 或者gpt-3.5-trubo-0613 都提示Unknown error

我退回以下版本都测试了下，对应报错信息

`0.0.93`   Unknown error
`0.0.92`   和 `0.0.91`  报错如下
Access denied due to invalid subscription key or wrong APl endpoint.Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.

看了下是从0.0.91加入的API Model 选择功能，可能问题就出在这

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by lucky9-cyou** [comment]
google-chrome 119.0.6045.159-1
chrome extension version 0.1.39
有类似的错误，相同的配置在bob openai translator插件里可以使用。
![image](https://github.com/openai-translator/openai-translator/assets/56758695/7f769599-ff51-4895-ad05-831b28d5d8b0)

**Comment by lucky9-cyou** [comment]
chrome extension 0.1.39也有这个错误

**Comment by khuencheng** [comment]
一样，今天出现了 "Access denied due to invalid subscription key or wrong API endpoint"
Azure GPT4, 在 ChatHub 或 AMA 这些第三方客户端中正常

**Comment by xavierskip** [comment]
0.1.39 版本是出了什么问题吗？我查看网络请求，以我 azure为例，请求头中的 api-key 内容是空的，但是我在设置中设置了的。
一直用的好好的，下午突然不行了。

**Comment by yetone** [comment]
最新版已经修复此问题
