### ISSUE TITLE
[Bug]0.2.0版本无法使用

### ISSUE THREAD

**Issue by Mabisi** [openai-translator/openai-translator#1106]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.2.0

### 系统/浏览器版本 System/Browser version

版本 119.0.6045.200（正式版本） （64 位）

### 复现步骤 Reproduce step

打开软件无法操作编辑，窗口无法拖动

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/19968269/3af0a6b1-c538-471d-9f6b-e185a656b150)打开软件无法操作编辑，窗口无法拖动，保存一直在转圈圈

### 你期望看到什么？What did you expect to see?

正常

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by wlqcwin** [comment]
The same problem...

**Comment by fzgjyf** [comment]
尝试了 v0.2.0 以后的所有版本，直到 v0.2.3，均出现窗口冻结，无法最小化、无法关闭、无法拖动，完全冻结在窗口上，只能后台杀进程。退回到0.0.9.96版本，谢谢。系统 windows 11 专业版  22H2

**Comment by middle-chunjie** [comment]
same problem

**Comment by zhangqiu-ai** [comment]
v0.2.3 同样的问题，无法拖动窗口

**Comment by flamewi** [comment]
12/04 14:50
v0.2.3 同樣問題，且無法關閉窗口。目前已退回0.096

**Comment by bluehj777** [comment]
same problem,v0.2.3

**Comment by yetone** [comment]
感谢反馈，是最近升级到 Tauri 2.0 导致的问题，看起来 Tauri 2.0 在 Windows 有一些兼容性问题，正在看了

**Comment by yetone** [comment]
最新版 v0.2.4 已经修复此问题，辛苦大家手动更新一下~
