### ISSUE TITLE
翻译模式TTS仍不能识别日语和中文

### ISSUE THREAD

**Issue by johnsmith8736** [openai-translator/openai-translator#112]
翻译模式TTS仍不能识别日语和中文

**Comment by ShinChven** [comment]
你浏览器tts的语言设置是什么？

**Comment by johnsmith8736** [comment]
> 
浏览器还能设置TTS？

**Comment by szh-bash** [comment]
这翻译模式是指什么？

**Comment by ShinChven** [comment]
https://github.com/yetone/openai-translator/blob/b418d12eb88376dfad8fe6d6783040188a2d3f39/src/background/index.ts#L2

看上去自动识别语言还没做完

**Comment by maltoze** [comment]
@ShinChven 不，是我忘删了

**Comment by maltoze** [comment]
windows用户可以这样安装语音文件
[下载用于沉浸式阅读器、阅读模式和大声朗读的语言和语音](https://support.microsoft.com/zh-cn/topic/%E4%B8%8B%E8%BD%BD%E7%94%A8%E4%BA%8E%E6%B2%89%E6%B5%B8%E5%BC%8F%E9%98%85%E8%AF%BB%E5%99%A8-%E9%98%85%E8%AF%BB%E6%A8%A1%E5%BC%8F%E5%92%8C%E5%A4%A7%E5%A3%B0%E6%9C%97%E8%AF%BB%E7%9A%84%E8%AF%AD%E8%A8%80%E5%92%8C%E8%AF%AD%E9%9F%B3-4c83a8d8-7486-42f7-8e46-2b0fdf753130)
