### ISSUE TITLE
增加选项，快捷键呼出translator后不自动翻译，保留上次翻译内容

### ISSUE THREAD

**Issue by JaydonZhao** [openai-translator/openai-translator#1122]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

增加选项，快捷键呼出translator后不自动翻译，保留上次翻译内容

### 描述 Motivation

Currently, the open-translator automatically translates every time the shortcut key is pressed, causing the previous translation result to be lost. Many times, users simply want to open the panel and view the translation result, and it is frustrating that the system makes this decision on behalf of the users.

### Solution

Adding an option to prevent automatic translation upon invoking the translator using shortcut keys, in order to retain the previously translated content.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by showthesunli** [comment]
同求此功能。

换句简单的话：想要一个快捷键，单纯的呼出软件而不要有任何其他动作

**Comment by yetone** [comment]
<img width="254" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/fb6cba0c-52e9-4552-9840-706067acda79">

最新版已经支持
