### ISSUE TITLE
[Bug] output display error when using ChatGPT WEB（Default GPT3.5）

### ISSUE THREAD

**Issue by PPG007** [openai-translator/openai-translator#1133]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.2.7

### 系统/浏览器版本 System/Browser version

Chrome 119.0.6045.159

KDE neno 5.25.

### 复现步骤 Reproduce step

Translate from English to Chinese by ChatGPT Web Default 3.5，the result display error。

### 你看到了什么错误？What errors do you see?

![Peek 2023-12-08 09-19](https://github.com/openai-translator/openai-translator/assets/48715059/5851229b-10f7-4cac-a860-23d4d1198c6f)

### 你期望看到什么？What did you expect to see?

Result display correctly.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by alexchiu0226** [comment]
我也遇到一樣的問題

**Comment by lwd-temp** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/26019675/79e4d0b1-8cbb-41eb-a700-253e8315fff7)
![image](https://github.com/openai-translator/openai-translator/assets/26019675/618ba9d5-dfd4-43f8-aed9-2c617b2608a2)

**Comment by RtYkk** [comment]
#1142 我说怎么好了，原来是光速修了。thx, yetone!
