### ISSUE TITLE
[Bug] Unusually high memory and CPU usage

### ISSUE THREAD

**Issue by eMUQI** [openai-translator/openai-translator#1156]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.2.14

### 系统/浏览器版本 System/Browser version

Windows 10 Pro 22H2 19045.3693

### 复现步骤 Reproduce step

Open the application and use it as usual.

### 你看到了什么错误？What errors do you see?

1. My computer has become unusually slow, and upon checking the task manager, I found that the memory and CPU usage of openai translator are exceptionally high.
![image](https://github.com/openai-translator/openai-translator/assets/32332228/4b0b4f7a-0a71-4dea-8cc3-dfa5f79b09b2)
2. The shortcut for translation is also not working. Pressing Ctrl+Q after selecting the text has no response.
![image](https://github.com/openai-translator/openai-translator/assets/32332228/d46e2603-e3c7-4b93-babf-0324ca0d0a1c)

### 你期望看到什么？What did you expect to see?

The memory and CPU are within the normal range, and the translation shortcut keys can also work properly.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by eMUQI** [comment]
Another new issue has been found. The openai translator occasionally triggers the behavior of adjusting the window size for unknown reasons. I did not drag the edge of the program, but the edge of the program follows my mouse.

**Comment by eMUQI** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/32332228/f06a1d80-f1a7-489c-a907-8c41e3c55665)

**Comment by h4rvey-g** [comment]
same issue here

**Comment by Lion176** [comment]
same issue

**Comment by xin2014** [comment]
same issue 
back to 0.2.13 temporarily

**Comment by eMUQI** [comment]
Based on my experience, I think this problem has been fixed in version 0.2.16, even though it's not mentioned in the update log. Thanks.
