### ISSUE TITLE
[Bug] 翻译结果混乱

### ISSUE THREAD

**Issue by czy-moyu** [openai-translator/openai-translator#1158]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.2.7

### 系统/浏览器版本 System/Browser version

Windows11/Chrome 120.0.6099.71（正式版本） （64 位）

### 复现步骤 Reproduce step

直接点翻译即可

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/45380309/cd034929-77e9-4a3d-a0a4-dd135ffbfe4b)

### 你期望看到什么？What did you expect to see?

正确的翻译

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by lingkerio** [comment]
同有这个问题，需要刷新后才能出现正确翻译

**Comment by h4rvey-g** [comment]
same issue

**Comment by czy-moyu** [comment]
突然自己好了
