### ISSUE TITLE
[Bug]Linux AppImage can not open after v0.2.1 version

### ISSUE THREAD

**Issue by ttys3** [openai-translator/openai-translator#1185]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.2.2 to  v3.0.0

### 系统/浏览器版本 System/Browser version

Chrome 120.0.6099.109 (Official Build) (64-bit)

### 复现步骤 Reproduce step

I downloaded latest versions to see from which version work and which not:

v0.2.1 is the latest version which works under Linux

```shell
/bin/ls -1 *.AppImage
open-ai-translator_0.0.96_amd64.AppImage
open-ai-translator_0.2.0_amd64.AppImage
open-ai-translator_0.2.11_amd64.AppImage
open-ai-translator_0.2.17_amd64.AppImage
open-ai-translator_0.2.1_amd64.AppImage
open-ai-translator_0.2.2_amd64.AppImage
open-ai-translator_0.2.3_amd64.AppImage
open-ai-translator_0.2.4_amd64.AppImage
open-ai-translator_0.2.5_amd64.AppImage
open-ai-translator_0.3.0_amd64.AppImage
open-ai-translator_0.3.1_amd64.AppImage
open-ai-translator_0.3.2_amd64.AppImage
open-ai-translator_0.3.3_amd64.AppImage
```

### 你看到了什么错误？What errors do you see?

```shell
./open-ai-translator_0.2.2_amd64.AppImage
mouse event Hooked!
libEGL warning: egl: failed to create dri2 screen

(open-ai-translator:688944): LIBDBUSMENU-GLIB-WARNING **: 19:52:38.577: About to Show called on an item wihtout submenus.  We're ignoring it.
libEGL warning: egl: failed to create dri2 screen
thread 'main' panicked at src/windows.rs:455:43:
called `Result::unwrap()` on an `Err` value: UnsupportedPlatform
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```shell
./open-ai-translator_0.3.3_amd64.AppImage
# exited with error code 101, no any error output
```

### 你期望看到什么？What did you expect to see?

the app should run and show a window

### 还有其他的内容吗？Anything else?

as I see, v0.2.1 is the latest version which works under Linux

begin v0.2.2 panic with :

```
thread 'main' panicked at src/windows.rs:455:43:
called `Result::unwrap()` on an `Err` value: UnsupportedPlatform
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

this caused by `window_shadows` crates, as the doc said `Linux: Unsupported`:

> window_shadows
> pub fn set_shadow(window: impl raw_window_handle::HasRawWindowHandle, enable: bool) -> Result<(), Error>
> Enables or disables the shadows for a window.
> 
> Platform-specific
> Windows: On Windows 11, the window will also have rounded corners.
> macOS: Shadows are always disabled for transparent windows.
> Linux: Unsupported, Shadows are controlled by the compositor installed on the end-user system.

and begin with v0.3.0 exited with error no 101 and no error shown up.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by ttys3** [comment]
try build

```shell
rm -rf src-tauri/target/ 
pnpm install

sudo dnf install -y ./javascriptcoregtk4.1-devel    
pnpm dev-tauri
```

**Comment by AngelontheRoad** [comment]
我遇到了相同的问题，release下载的appimage打不开，错误信息如下
```
libEGL warning: egl: failed to create dri2 screen
mouse event hook skipped in linux!
thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/global-hotkey-0.2.4/src/hotkey.rs:182:36:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
自己创建了一个`tauri_signing_key`，尝试build，已安装依赖。没出现大错，但运行结果也是`segment error`，无详细报错。

[build_info.txt](https://github.com/openai-translator/openai-translator/files/15236698/build_info.txt)

**Comment by ttys3** [comment]
> 我遇到了相同的问题，release下载的appimage打不开，错误信息如下
> 
> ```
> libEGL warning: egl: failed to create dri2 screen
> mouse event hook skipped in linux!
> thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/global-hotkey-0.2.4/src/hotkey.rs:182:36:
> called `Option::unwrap()` on a `None` value
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> 自己创建了一个`tauri_signing_key`，尝试build，已安装依赖。没出现大错，但运行结果也是`segment error`，无详细报错。
> 
> [build_info.txt](https://github.com/openai-translator/openai-translator/files/15236698/build_info.txt)

this is not the same issue.

I've created another one, please do not comment here.

https://github.com/openai-translator/openai-translator/issues/1522
