### ISSUE TITLE
报错TypeError: Failed to fetch

### ISSUE THREAD

**Issue by letuplus** [openai-translator/openai-translator#121]
TypeError: Failed to fetch

**Comment by yetone** [comment]
网络问题，检查一下代理 IP 能否正常访问 OpenAI API

**Comment by hxx258456** [comment]
不是说openai api不用代理也可以访问吗

**Comment by jaychoubaby** [comment]
> 不是说openai api不用代理也可以访问吗

同问，api不是不需要代理吗？

> 网络问题，检查一下代理 IP 能否正常访问 OpenAI API

是否可以考虑加入代理功能呀

**Comment by shaonianche** [comment]
> 不是说openai api不用代理也可以访问吗

可以使用Cloudflare Workers来做一个api代理：https://github.com/noobnooc/noobnooc/discussions/9

**Comment by jaychoubaby** [comment]
> > 不是说openai api不用代理也可以访问吗
> 
> 可以使用Cloudflare Workers来做一个api代理：[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9)

此方法测试有效，感谢

**Comment by Jackiexiao** [comment]
可以通过腾讯云函数的方法，声称可以支持 SSE （不过我看有人说 部署在 AWS 或者 腾讯云的 云函数实测都不支持 SSE 流式返回结果），另外通过香港节点可能存在被封的危险
https://github.com/easychen/openai-api-proxy

**Comment by yywill** [comment]
我用了代理也是如此。请问你的chrome 插件是不是会读取系统的代理设置？ macbook

**Comment by Blushxbwang** [comment]
> > 不是说openai api不用代理也可以访问吗
> 
> 可以使用Cloudflare Workers来做一个api代理：[noobnooc/noobnooc#9](https://github.com/noobnooc/noobnooc/discussions/9)

完美解决，太感谢了！
