### ISSUE TITLE
[Bug]划词后出现显示一半的大号ICON，点了没反应

### ISSUE THREAD

**Issue by bitfirefly** [openai-translator/openai-translator#1210]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.7

### 系统/浏览器版本 System/Browser version

EDGE 120.0.2210.77 

### 复现步骤 Reproduce step

划词后出现半个大号ICON

### 你看到了什么错误？What errors do you see?

ICON 大小不对，而且只有一半。点击ICON图标后无反应。

### 你期望看到什么？What did you expect to see?

正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by t754Yuu** [comment]
我也是这样，求修复

**Comment by t754Yuu** [comment]
![屏幕截图 2023-12-21 001848](https://github.com/openai-translator/openai-translator/assets/87240694/de57bb01-dfc2-4233-ae51-fa8a319dc848)

**Comment by yetone** [comment]
<img width="376" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/091e0c5a-f617-484f-ab53-a2b75b004070">

关掉这个即可，具体原因：
<img width="531" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/d620f206-7229-481a-8311-9ef67aaf0bd8">

https://x.com/yetone/status/1643684601532137472?s=20

**Comment by bitfirefly** [comment]
收到，谢谢

**Comment by jas0nma** [comment]
关闭了这个选项，问题依旧存在。
