### ISSUE TITLE
可否添加直接使用chatgpt的功能，而不是调用API

### ISSUE THREAD

**Issue by JDYG** [openai-translator/openai-translator#122]
对于已经购买了plus会员的用户，可以直接调用chatgpt. 对于非plus用户，仍然可以使用免费的chatgpt接口。
API的免费额度用完后，付费对于国内用户还是挺麻烦的。

**Comment by EricPengShuai** [comment]
想问问普通用户使用 ChatGPT API 需要收费吗，就是创建API使用的话是按照 token 计费的吗
![API](https://user-images.githubusercontent.com/1206493/223043946-0e7486ca-94d7-4324-a4f2-f62b9a3d527d.png)

**Comment by wenlzhang** [comment]
> 想问问普通用户使用 ChatGPT API 需要收费吗，就是创建API使用的话是按照 token 计费的吗

通过 API 使用 ChatGPT 需要按照 Token 计费。英文的话，大概 1000 tokens = 750 单词 = 0.002 USD。

https://openai.com/pricing

**Comment by lucasli0721** [comment]
有同样的需求，来自plus用户

**Comment by haoxia1** [comment]
+1

**Comment by likfees** [comment]
有相同的需求

**Comment by Pengree** [comment]
+1

**Comment by maltoze** [comment]
supported by #573
