### ISSUE TITLE
可以自定义模型名称

### ISSUE THREAD

**Issue by DillionApple** [openai-translator/openai-translator#1241]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

自定义支持模型名称，以支持兼容 OpenAI 格式的其它模型

### 描述 Motivation

现在有很多支持 OpenAI API 格式的大模型提供商，可以通过更改 base_url、sk、模型名称来使用。以及有一些自己在本地 host 的模型也支持 OpenAI 的 API 格式。

但是现在 OpenAI Translator 不支持自己填写模型名称，导致这些模型无法使用。如果可以自己指定，能极大的提升软件的适用范围，迅速接入开源生态。

### Solution

增加一个 Customized Model 选项，让用户可以自己填写所请求的模型名称。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Sheldontao** [comment]
pleassssssssse author.

**Comment by yetone** [comment]
<img width="707" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/92eada5c-ab99-47f9-a600-042b6b580dac">

一直支持自定义的

**Comment by joostshao** [comment]
老板，我想支持多个~~~~~~~~~~~~~~~~求~
