### ISSUE TITLE
闪退 我使用的是MacBook Pro， 处理器2.6 GHz 六核Intel Core i7，系统14.2.1 (23C71) ，图形显卡Radeon Pro 555X 4 GB Intel UHD Graphics 630 1536 MB ，6 GB 2400 MHz DDR4

### ISSUE THREAD

**Issue by touch3080** [openai-translator/openai-translator#1254]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

OpenAI.Translator_0.3.9_aarch64.dmg

### 系统/浏览器版本 System/Browser version

macos14.2.1 (23C71)

### 复现步骤 Reproduce step

闪崩，无法打开

### 你看到了什么错误？What errors do you see?

闪崩，无法打开

### 你期望看到什么？What did you expect to see?

闪崩，无法打开

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Garlic6694** [comment]
1.Intel 芯片应该使用 OpenAI.Translator_0.3.9_**x64**.dmg NOT **aarch64**
2.我使用0.3.9_x64版本 Intel芯片,ventura13.6 也闪退

**Comment by wiihunting** [comment]
同样闪退
<img width="280" alt="iShot_2024-01-21_13 53 17" src="https://github.com/openai-translator/openai-translator/assets/2383622/ee9247a4-291d-4f73-a6b7-bdd5e917ffcd">

<img width="260" alt="iShot_2024-01-21_13 52 57" src="https://github.com/openai-translator/openai-translator/assets/2383622/a8819fa9-61ca-4e93-9274-a9e2ff1bc5bf">

**Comment by wiihunting** [comment]
本次更新前可以正常使用

**Comment by Garlic6694** [comment]
> 同样闪退 <img alt="iShot_2024-01-21_13 53 17" width="280" src="https://private-user-images.githubusercontent.com/2383622/298362969-ee9247a4-291d-4f73-a6b7-bdd5e917ffcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTY4MDMsIm5iZiI6MTcwNTgxNjUwMywicGF0aCI6Ii8yMzgzNjIyLzI5ODM2Mjk2OS1lZTkyNDdhNC0yOTFkLTRmNzMtYTZiNy1iZGQ1ZTkxN2ZmY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY2NDBjNzhhOTFlNGM0ZjE1ODk0YWE3MjhjMmNkNzZhOTY2ZTFiNjJlOGNiOGZiMjAzYTAwYTM0NmYxMWU1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qaIWuqQAcL8XbbWg2rv6sSC6pcRwb9iF4eX0kC50t3M">
> 
> <img alt="iShot_2024-01-21_13 52 57" width="260" src="https://private-user-images.githubusercontent.com/2383622/298362958-a8819fa9-61ca-4e93-9274-a9e2ff1bc5bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTY4MDMsIm5iZiI6MTcwNTgxNjUwMywicGF0aCI6Ii8yMzgzNjIyLzI5ODM2Mjk1OC1hODgxOWZhOS02MWNhLTRlOTMtOTI3NC1hOWUyZmYxYmM1YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZiMDI3Nzc2N2U3OGY4MzFjYmE3YTA3NjRhNDc1MDc5YWU0NTQ3ZGUzY2E2N2VkNzY3YzJlZGE0ZWZjOTExNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JMb92NMDV4zbAnz8_Z1gRg7F-R-O1PdZ14-y4tYkprM">

我回退到了v0.3.8

**Comment by wiihunting** [comment]
> > 同样闪退 <img alt="iShot_2024-01-21_13 53 17" width="280" src="https://private-user-images.githubusercontent.com/2383622/298362969-ee9247a4-291d-4f73-a6b7-bdd5e917ffcd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTY4MDMsIm5iZiI6MTcwNTgxNjUwMywicGF0aCI6Ii8yMzgzNjIyLzI5ODM2Mjk2OS1lZTkyNDdhNC0yOTFkLTRmNzMtYTZiNy1iZGQ1ZTkxN2ZmY2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTY2NDBjNzhhOTFlNGM0ZjE1ODk0YWE3MjhjMmNkNzZhOTY2ZTFiNjJlOGNiOGZiMjAzYTAwYTM0NmYxMWU1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qaIWuqQAcL8XbbWg2rv6sSC6pcRwb9iF4eX0kC50t3M">
> > <img alt="iShot_2024-01-21_13 52 57" width="260" src="https://private-user-images.githubusercontent.com/2383622/298362958-a8819fa9-61ca-4e93-9274-a9e2ff1bc5bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MTY4MDMsIm5iZiI6MTcwNTgxNjUwMywicGF0aCI6Ii8yMzgzNjIyLzI5ODM2Mjk1OC1hODgxOWZhOS02MWNhLTRlOTMtOTI3NC1hOWUyZmYxYmM1YmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjFUMDU1NTAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjZiMDI3Nzc2N2U3OGY4MzFjYmE3YTA3NjRhNDc1MDc5YWU0NTQ3ZGUzY2E2N2VkNzY3YzJlZGE0ZWZjOTExNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JMb92NMDV4zbAnz8_Z1gRg7F-R-O1PdZ14-y4tYkprM">
> 
> 我回退到了v0.3.8

谢谢！我也回退回去v0.3.8了，目前正常使用

**Comment by hunteritself** [comment]
我这边一样的错误，回退版本了还是闪退，报栈溢出的错误。

**Comment by dfldylan** [comment]
闪退
<img width="392" alt="image" src="https://github.com/openai-translator/openai-translator/assets/28103567/25f5a63f-dd3e-4f91-b176-c80041840ea9">

**Comment by lroolle** [comment]
[OpenAI.Translator_0.3.9_x64.dmg](https://github.com/openai-translator/openai-translator/releases/download/v0.3.9/OpenAI.Translator_0.3.9_x64.dmg)

- 0.3.9 crash
- 回退到 0.3.8 正常

**Comment by lifeva** [comment]
0.3.9 crash，我是intel cpu ，macos 14.3

**Comment by neohob** [comment]
实在是没办法用了，我也闪退 intel cpu，0.3.9,  macos 13.6.3

**Comment by Melonan** [comment]
0.38 , 0.39 同样的闪退 mbp 2020 intel cpu macos 14.1.2

**Comment by htoooth** [comment]
我也闪退

**Comment by igeekbb** [comment]
0.3.10 继续闪退

**Comment by Bill-Haku** [comment]
0.3.10继续闪退

**Comment by mz1999** [comment]
0.3.10 在 macOS 14.2.1  X86-64 上闪退

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               OpenAI Translator [7425]
Path:                  /Applications/OpenAI Translator.app/Contents/MacOS/OpenAI Translator
Identifier:            xyz.yetone.apps.openai-translator
Version:               0.3.10 (20240129.115301)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-02-02 09:39:05.6923 +0800
OS Version:            macOS 14.2.1 (23C71)
Report Version:        12
Bridge OS Version:     8.2 (21P2057)
Anonymous UUID:        E301BA7F-830B-F2B9-A8CA-BEC3F4A8772F


Time Awake Since Boot: 340000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  main  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000020
Exception Codes:       0x0000000000000001, 0x0000000000000020

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [7425]

VM Region Info: 0x20 is not in any region.  Bytes before following region: 140737486327776
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      shared memory            7fffffe11000-7fffffe12000 [    4K] r-x/r-x SM=SHM  

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter


Thread 0 Crashed:: main Dispatch queue: com.apple.main-thread
0   libobjc.A.dylib               	    0x7ff807a2cb81 lookUpImpOrForward + 40
1   libobjc.A.dylib               	    0x7ff807a2c59b _objc_msgSend_uncached + 75
2   WebKit                        	    0x7ff90c06fe43 -[WKWebView _evaluateJavaScript:asAsyncFunction:withSourceURL:withArguments:forceUserGesture:inFrame:inWorld:completionHandler:] + 117
3   WebKit                        	    0x7ff90c06f385 -[WKWebView evaluateJavaScript:completionHandler:] + 99
4   OpenAI Translator             	       0x10a558b6b objc_exception::try_no_ret::try_objc_execute_closure::ha028842559efa712 + 107
5   OpenAI Translator             	       0x10a5fd702 RustObjCExceptionTryCatch + 18
6   OpenAI Translator             	       0x10a558e52 objc_exception::try::h71eb45893ae31772 + 114
7   OpenAI Translator             	       0x10a558136 objc::message::platform::send_unverified::hfd4792ac58431593 + 118
8   OpenAI Translator             	       0x10a5505bc wry::wkwebview::InnerWebView::eval::h7b76a2eef3f33615 + 892
9   OpenAI Translator             	       0x10a55f231 wry::WebView::evaluate_script::hcc2e57942d26f4ed + 17
10  OpenAI Translator             	       0x109fb0615 tauri_runtime_wry::handle_user_message::ha48e5cf0c7d5cea1 + 2917
11  OpenAI Translator             	       0x109faf8d1 tauri_runtime_wry::send_user_message::h9563cbedd6aa22f7 + 129
12  OpenAI Translator             	       0x109f983ea tauri::window::Window$LT$R$GT$::listen_js::hb03dae7d44d5656c + 682
13  OpenAI Translator             	       0x10a020140 tauri::event::plugin::init::_$u7b$$u7b$closure$u7d$$u7d$::h499e014ef4f4c24e + 560
14  OpenAI Translator             	       0x10a0269a9 _$LT$tauri..plugin..TauriPlugin$LT$R$C$C$GT$$u20$as$u20$tauri..plugin..Plugin$LT$R$GT$$GT$::extend_api::h6990ec59d0472e40 + 57
15  OpenAI Translator             	       0x10a021ac8 tauri::plugin::PluginStore$LT$R$GT$::extend_api::h2f977fe7fcb5cf15 + 152
16  OpenAI Translator             	       0x109e5506f tauri::manager::AppManager$LT$R$GT$::extend_api::h55fe9acb04e5d0d2 + 191
17  OpenAI Translator             	       0x109f95883 tauri::window::Window$LT$R$GT$::on_message::hedfcc519de8dd7cd + 4867
18  OpenAI Translator             	       0x109ea5824 tauri::ipc::protocol::get::_$u7b$$u7b$closure$u7d$$u7d$::hb1a1c38e39edbecb + 2964
19  OpenAI Translator             	       0x109fe389a tauri::manager::window::WindowManager$LT$R$GT$::prepare_pending_window::_$u7b$$u7b$closure$u7d$$u7d$::h2eb964b992c28980 + 74
20  OpenAI Translator             	       0x109fad44d tauri_runtime_wry::create_webview::_$u7b$$u7b$closure$u7d$$u7d$::heb847b03a63c450d + 157
21  OpenAI Translator             	       0x10a54df00 wry::wkwebview::InnerWebView::new_ns_view::start_task::h61ac9b43f632636c + 5504
22  WebKit                        	    0x7ff90c1d4cd6 WebKit::WebURLSchemeHandlerCocoa::platformStartTask(WebKit::WebPageProxy&, WebKit::WebURLSchemeTask&) + 78
23  WebKit                        	    0x7ff90c392b79 WebKit::WebURLSchemeHandler::startTask(WebKit::WebPageProxy&, WebKit::WebProcessProxy&, WTF::ObjectIdentifierGeneric<WebCore::PageIdentifierType, WTF::ObjectIdentifierMainThreadAccessTraits>, WebKit::URLSchemeTaskParameters&&, WTF::CompletionHandler<void (WebCore::ResourceResponse const&, WebCore::ResourceError const&, WTF::Vector<unsigned char, 0ul, WTF::CrashOnOverflow, 16ul, WTF::FastMalloc>&&)>&&) + 285
24  WebKit                        	    0x7ff90c3574e3 WebKit::WebPageProxy::startURLSchemeTaskShared(WTF::Ref<WebKit::WebProcessProxy, WTF::RawPtrTraits<WebKit::WebProcessProxy>>&&, WTF::ObjectIdentifierGeneric<WebCore::PageIdentifierType, WTF::ObjectIdentifierMainThreadAccessTraits>, WebKit::URLSchemeTaskParameters&&) + 139
25  WebKit                        	    0x7ff90c35743a WebKit::WebPageProxy::startURLSchemeTask(WebKit::URLSchemeTaskParameters&&) + 46
26  WebKit                        	    0x7ff90c6d2f7c WebKit::WebPageProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 34924
27  WebKit                        	    0x7ff90c785813 IPC::MessageReceiverMap::dispatchMessage(IPC::Connection&, IPC::Decoder&) + 223
28  WebKit                        	    0x7ff90c38bafd WebKit::WebProcessProxy::didReceiveMessage(IPC::Connection&, IPC::Decoder&) + 31
29  WebKit                        	    0x7ff90c7812f7 IPC::Connection::dispatchMessage(std::__1::unique_ptr<IPC::Decoder, std::__1::default_delete<IPC::Decoder>>) + 269
30  WebKit                        	    0x7ff90c78165c IPC::Connection::dispatchIncomingMessages() + 496
31  JavaScriptCore                	    0x7ff8249bf62e WTF::RunLoop::performWork() + 430
32  JavaScriptCore                	    0x7ff8249c03ba WTF::RunLoop::performWork(void*) + 26
33  CoreFoundation                	    0x7ff807ed4077 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
34  CoreFoundation                	    0x7ff807ed4019 __CFRunLoopDoSource0 + 157
35  CoreFoundation                	    0x7ff807ed3de4 __CFRunLoopDoSources0 + 215
36  CoreFoundation                	    0x7ff807ed2a61 __CFRunLoopRun + 919
37  CoreFoundation                	    0x7ff807ed2102 CFRunLoopRunSpecific + 557
38  HIToolbox                     	    0x7ff8127aa9d9 RunCurrentEventLoopInMode + 292
39  HIToolbox                     	    0x7ff8127aa7e6 ReceiveNextEventCommon + 665
40  HIToolbox                     	    0x7ff8127aa531 _BlockUntilNextEventMatchingListInModeWithFilter + 66
41  AppKit                        	    0x7ff80b4e07b9 _DPSNextEvent + 880
42  AppKit                        	    0x7ff80bdd8f64 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1304
43  AppKit                        	    0x7ff80b4d1d32 -[NSApplication run] + 603
44  OpenAI Translator             	       0x109e8a8d9 objc_exception::try_no_ret::try_objc_execute_closure::h82e7f8bfb10a0790 + 41
45  OpenAI Translator             	       0x10a5fd702 RustObjCExceptionTryCatch + 18
46  OpenAI Translator             	       0x109eeb297 objc::message::platform::send_unverified::h0b160f367599f0c5 + 119
47  OpenAI Translator             	       0x109e47138 tao::platform_impl::platform::event_loop::EventLoop$LT$T$GT$::run::hf393f43fcf68aafe + 504
48  OpenAI Translator             	       0x109fe4fe1 _$LT$tauri_runtime_wry..Wry$LT$T$GT$$u20$as$u20$tauri_runtime..Runtime$LT$T$GT$$GT$::run::h915926056b37cf85 + 241
49  OpenAI Translator             	       0x10a00da29 tauri::app::App$LT$R$GT$::run::hf6148bb071de8bf6 + 217
50  OpenAI Translator             	       0x109fed7d8 app::main::h24ea80fd493716a2 + 8792
51  OpenAI Translator             	       0x109f0be76 std::sys_common::backtrace::__rust_begin_short_backtrace::hc859ce12add92b92 + 6
52  OpenAI Translator             	       0x109f8c99c std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h32772e482282dde1 + 12
53  OpenAI Translator             	       0x10a69cbd0 std::rt::lang_start_internal::had326b3bd136b0a7 + 800
54  OpenAI Translator             	       0x109fef11c main + 44
55  dyld                          	    0x7ff807a6d386 start + 1942
...
```

**Comment by lonelygo** [comment]
macOS 14.3, Intel i9.
3.9,3.10两个版本同样闪退。

**Comment by geekbb** [comment]
大家不用试了，v0.3.11依旧闪退
<img width="260" alt="image" src="https://github.com/openai-translator/openai-translator/assets/46196358/bd550b0f-d131-4753-93e6-713238795136">

**Comment by apkcoder** [comment]
复议，v0.3.11依旧闪退

**Comment by steve-yuan-8276** [comment]
我也是，作者能不能出来调试一下bug，现在基本上处于不可用的状态。

**Comment by lifeva** [comment]
0.3.11继续闪退，是不支持intel cpu了吗？

**Comment by Bill-Haku** [comment]
> 0.3.10继续闪退

实测0.3.21似乎已修复该问题

**Comment by yetone** [comment]
最新版已经不闪退了，这个 bug 是由 Tauri 引起的，与 OpenAI Translator 本身完全无关，最新版的 Tauri 已经修复这个 bug，所以最新版 OpenAI Translator 也不再闪退了，大家更新一下吧
