### ISSUE TITLE
支持 gpt-3.5-turbo-0125

### ISSUE THREAD

**Issue by devyujie** [openai-translator/openai-translator#1267]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

支持 gpt-3.5-turbo-0125

### 描述 Motivation

支持 gpt-3.5-turbo-0125

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by shouyiwang** [comment]
赞同！

最好可以在设置里增加一个输入框，可以让大家自己输入新的openAI刚发布的api。
毕竟等更新加入列表的话，还是太慢了。对心急的人很折磨

**Comment by 2168028160** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/46835377/e5e223c0-fbcc-409c-9ba4-48f6b46d69a5)
新的版本0.3.25已经支持自定义模型了
