### ISSUE TITLE
[Bug] {{更新了0.3.10还是闪退，什么狗屎💩}}

### ISSUE THREAD

**Issue by daydayfish** [openai-translator/openai-translator#1274]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.10

### 系统/浏览器版本 System/Browser version

-

### 复现步骤 Reproduce step

https://github.com/openai-translator/openai-translator/issues/1254

### 你看到了什么错误？What errors do you see?

https://github.com/openai-translator/openai-translator/issues/1254

### 你期望看到什么？What did you expect to see?

https://github.com/openai-translator/openai-translator/issues/1254

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by NeKoOuO** [comment]
笑死了 張嘴就來 開源不適合你快滾吧

**Comment by Weijun2009** [comment]
人家又没收你钱，狗屎人白嫖还要求那么多

**Comment by yetone** [comment]
抱歉，最新版已经彻底解决闪退问题。

**Comment by ShikiSuen** [comment]
来拆一下你这两句话：

1. 「更新了0.3.10还是闪退」
2. 「什么狗屎💩」

你作为 FOSS 软件的用户，讲第一句没问题，第二句过分了。

**Comment by NeKoOuO** [comment]
> @NeKoOuO I assume that his ability is far from being able to create a usable PR for this repository.

True dude 🤣
