### ISSUE TITLE
[Bug] {{win11应用启动分辨率不正确，并且无法通过边框拖拽进行调整.}}

### ISSUE THREAD

**Issue by IcarusAegis** [openai-translator/openai-translator#1278]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.10

### 系统/浏览器版本 System/Browser version

windi

### 复现步骤 Reproduce step

从桌面默认启动后，显示不正确，并且不能通过拖拽边框进行调整。
显示器分辨率为1440p，16：10.
![Clip_2024-02-06_13-24-27](https://github.com/openai-translator/openai-translator/assets/46650308/a46551d1-c662-4a3a-8c59-ccaf458d716c)

### 你看到了什么错误？What errors do you see?

显示不正确

### 你期望看到什么？What did you expect to see?

正确的显示

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Willmerhyper** [comment]
我有同样问题，v0.3.11版本也一样

**Comment by Loongphy** [comment]
Windows 11 23H2 22631.3235
无法拖拽窗口顶部来调整调整位置，这应当是可预期的行为

**Comment by Loongphy** [comment]
> Windows 11 23H2 22631.3235 无法拖拽窗口顶部来调整调整位置，这应当是可预期的行为

0.3.30 已修复，作者真快啊❤️
自带的更新器有点问题，没法正常更新，下载新的 release 版本安装

**Comment by yetone** [comment]
抱歉，最新版已经修复，请更新到最新版
