### ISSUE TITLE
Support Google gemini

### ISSUE THREAD

**Issue by NTTAT-Shou-Chin** [openai-translator/openai-translator#1282]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

Support Google gemini as api source

### 描述 Motivation

Google gemini api is free. And OpenAI is not free to use even gpt 3.5. 

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="732" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/3ba92f8f-30b7-4288-a538-7482b73fb48c">

Hello, it already supports Gemini
