### ISSUE TITLE
[Bug] 0.3.11继续闪退，Macos 14.3.1，intel cpu

### ISSUE THREAD

**Issue by lifeva** [openai-translator/openai-translator#1286]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.11

### 系统/浏览器版本 System/Browser version

14.3.1

### 复现步骤 Reproduce step

更新，启动，闪退

### 你看到了什么错误？What errors do you see?

意外退出

### 你期望看到什么？What did you expect to see?

正常启动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Mabisi** [comment]
windows也闪退，打开任务栏显示几秒钟图标，然后就退出了

**Comment by daydayfish** [comment]
💩

**Comment by smile-xuc** [comment]
一样的环境，一样的问题。打开就闪退。
[OpenAI Translator 0.3.11闪退.pdf](https://github.com/openai-translator/openai-translator/files/14320994/OpenAI.Translator.0.3.11.pdf)

**Comment by sirius777coder** [comment]
我也闪退了

**Comment by shurco** [comment]
I got this error since version 0.3.9. I had to rollback to 0.3.8 and everything works.

**Comment by slipbox** [comment]
继续闪退，无法使用
<img width="759" alt="image" src="https://github.com/openai-translator/openai-translator/assets/57564522/0116ca1c-ce04-4a5f-bd78-e550311a0fa7">

**Comment by slipbox** [comment]
0.3.8还是闪退……

**Comment by beanu** [comment]
mac m1 同样的问题

**Comment by x1nchen** [comment]
我升级之后也发现了这个问题，我测试了几个版本，发现是升级到 v3.x 才会闪退，v2 的最后一个版本 v0.2.17 正常工作

附上 report 日志 
[Uploading crash-report.txt…]()

**Comment by Coya-yan** [comment]
macOS 13.6.1 (22G313) 在打开后几秒随即闪退

**Comment by eirture** [comment]
Intel, macOS Sonoma 14.3.1 同样闪退

**Comment by Willmerhyper** [comment]
我是 openai-translator 重度用户. Win11和 Mac OS都在使用. 
看到 Github的 Issue 很多闪退情况, 好像也一直没有修复.
今天之前使用都正常, 但今天遇到 Mac OS出现闪退, 导致无法打开使用, 我可能发现导致闪退的原因: 今天设置了下 Hotkey 为 Control+option, 就突然出现闪退! 然后就一直无法打开
采取的尝试方法:
1.移除重新安装
2.回退版本从 V.03.11至 V0.3.6
3.采取Readme 中的 Troubleshooting
以上都没有解决.
我的系统:
New MacBook Pro /Apple M2 Pro/ macOS 14.3.1 (23D60)
Mac现在完全用不了openai-translator, 希望能尽快修复!

**Comment by slipbox** [comment]
0.3.20继续闪退
<img width="927" alt="image" src="https://github.com/openai-translator/openai-translator/assets/57564522/97104be5-abab-4a24-8cba-b404c8780ab1">

**Comment by Bill-Haku** [comment]
实测0.3.21似乎已修复该问题

**Comment by yetone** [comment]
最新版已彻底解决此问题

**Comment by tddtds01** [comment]
> 最新版已彻底解决此问题

今天下的最新版，win 11系统，打开没有任何反应，用管理员运行，右下角出现图标，一点图标又消失了，不知道是什么原因

**Comment by shiqimei** [comment]
> 我是 openai-translator 重度用户. Win11和 Mac OS都在使用. 看到 Github的 Issue 很多闪退情况, 好像也一直没有修复. 今天之前使用都正常, 但今天遇到 Mac OS出现闪退, 导致无法打开使用, 我可能发现导致闪退的原因: 今天设置了下 Hotkey 为 Control+option, 就突然出现闪退! 然后就一直无法打开 采取的尝试方法: 1.移除重新安装 2.回退版本从 V.03.11至 V0.3.6 3.采取Readme 中的 Troubleshooting 以上都没有解决. 我的系统: New MacBook Pro /Apple M2 Pro/ macOS 14.3.1 (23D60) Mac现在完全用不了openai-translator, 希望能尽快修复!

就是设置快捷键的问题，感觉不设置都还挺正常的，一设置后就直接闪退。参考楼上方法删除 `rm ~/Library/Application\ Support/xyz.yetone.apps.openai-translator/config.json` 恢复正常使用。
