### ISSUE TITLE
希望支持Ollama

### ISSUE THREAD

**Issue by chllei** [openai-translator/openai-translator#1296]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望支持自部署的Ollama

### 描述 Motivation

如题，希望能够支持本地的自部署模型。其实，绝大部分的翻译和润色任务，用7b的模型（比如OpenChat、CausalLM等）都可以很不错地完成，所需显存8GB也就够了，完全可以自己部署。这样隐私性更佳。希望大神能够考虑一下支持Ollama等本地的推理服务。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by chllei** [comment]
刚看到支持 Ollama 了，非常感谢！有个小问题，我 Ollama 里用的是 OpenChat 模型，但是在这里的设置中，我发现没法用我的模型

**Comment by yetone** [comment]
@chllei 最新版已经支持自定义模型了

<img width="732" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/856b27e0-7c3d-482d-9efb-223a0e70e65a">

**Comment by sola97** [comment]
浏览器插件不支持本地模型吗

**Comment by lukaschan** [comment]
请问“自定义模型名称”的填写规则？比如我下的模型是：llama2-chinese:13b-chat-q4_K_M

**Comment by yetone** [comment]
> 请问“自定义模型名称”的填写规则？比如我下的模型是：llama2-chinese:13b-chat-q4_K_M

没有规则，如实填写即可

**Comment by lianglaoda1** [comment]
为啥不运行呢？只是显示ing。看得到没有加载GPU

**Comment by chllei** [comment]
> 为啥不运行呢？只是显示ing。看得到没有加载GPU

如果用 Ollama 的话，需要先在 Windows Terminal 命令行里确保你本地的 Ollama 运行正常，再试用这个软件。
