### ISSUE TITLE
输入框没有内容时，切换翻译语言选项时不要自动翻译。

### ISSUE THREAD

**Issue by susanooxyz** [openai-translator/openai-translator#1302]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.11

### 系统/浏览器版本 System/Browser version

win11

### 复现步骤 Reproduce step

清空上一次翻译的输入后（不管点清空输入的按钮还是删除键删除），改变源语言或者目标语言或者对调。

### 你看到了什么错误？What errors do you see?

会自动把上一次翻译的结果作为输入执行翻译动作。

### 你期望看到什么？What did you expect to see?

当清空输入后，修改源语言或者目标语言，不要执行翻译动作。只是简单的却换语言就好。用户自己点提交执行新的翻译。
或者可以做成一个选项。

### 还有其他的内容吗？Anything else?

当清空输入后，我是想做新的翻译操作。这时候没有必要以上一次的输出作为输入去执行翻译。
和#627可能是同一个问题

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版已修复此问题
