### ISSUE TITLE
[Bug] 光标无法使用方向键移动

### ISSUE THREAD

**Issue by leadream** [openai-translator/openai-translator#1303]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.20

### 系统/浏览器版本 System/Browser version

macOS 14.0

### 复现步骤 Reproduce step

输入一段文字，按方向键移动光标，光标不动。
输入一段文字，按 Cmd 加方向键移动光标到开头或末尾，光标不动。
输入一段文字，按 Shift 加方向键选中文字，光标不动。

### 你看到了什么错误？What errors do you see?

输入一段文字，按方向键移动光标，光标不动。
输入一段文字，按 Cmd 加方向键移动光标到开头或末尾，光标不动。
输入一段文字，按 Shift 加方向键选中文字，光标不动。

https://github.com/openai-translator/openai-translator/assets/12868055/b2e823c7-6636-4f41-9a0b-eb48771d5fa1

### 你期望看到什么？What did you expect to see?

光标正常移动，就像在其他编辑器中一样

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版已彻底解决此问题
