### ISSUE TITLE
[Bug] {{在ollama环境下，api 正常访问，运行本地model报错404，mac pro M1 32G RAM}}

### ISSUE THREAD

**Issue by johnny5015** [openai-translator/openai-translator#1317]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.25

### 系统/浏览器版本 System/Browser version

macOs 14.2.1

### 复现步骤 Reproduce step

![1709015352281](https://github.com/openai-translator/openai-translator/assets/10346555/4bee09ad-06aa-421e-87ec-d842bcd89d94)

设置本地ollama环境，model选择mistral
![1709015802162](https://github.com/openai-translator/openai-translator/assets/10346555/c870f0c2-7fa2-4e14-9cfe-d1f640825d0f)
翻译报404, 可能配置的api url有问题

### 你看到了什么错误？What errors do you see?

![aa](https://github.com/openai-translator/openai-translator/assets/10346555/af01c573-6bd9-4087-b5a0-3cdc9366d8a3)

"failed to call API: error sending request for url (http://localhost:11434/v1/chat/completions): connection closed before message completed"

### 你期望看到什么？What did you expect to see?

本地完成翻译，不报错

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by johnny5015** [comment]
After rebooting My Computer, The bug disappeared.

**Comment by markelzhang** [comment]
+1 本地运行报错，重启无效

版本：Version 0.3.33 (20240306.115455)

<img width="584" alt="image" src="https://github.com/openai-translator/openai-translator/assets/61811312/99166e1b-a605-4a1b-84fe-1f20e04f44ea">

**Comment by yetone** [comment]
请关闭所有的代理软件和防火墙

**Comment by xinxin98k** [comment]
本地防火墙和代理均关闭状态 本地urllib3版本还回退至了1.25.11版本，dify接入调用时一直报错，如何排查解决呢~
![hh](https://github.com/user-attachments/assets/ed2b5490-a2c1-43c9-acce-e66e9f4bce62)
