### ISSUE TITLE
Mac M2 出现错误：“OpenAI Translator”意外退出。

### ISSUE THREAD

**Issue by wenxinmomo** [openai-translator/openai-translator#1318]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.25

### 系统/浏览器版本 System/Browser version

无

### 复现步骤 Reproduce step

设置快捷键后就打不开了，重新安装也不行。
设置的快捷键：应该是 ***窗口/隐藏（具体是什么名忘了），设置成了common+r
然后就崩溃掉了，打开后出现：“OpenAI Translator”意外退出。

### 你看到了什么错误？What errors do you see?

设置快捷键后就打不开了，重新安装也不行。
设置的快捷键：应该是 ***窗口/隐藏（具体是什么名忘了），设置成了common+r
然后就崩溃掉了，打开后出现：“OpenAI Translator”意外退出。

### 你期望看到什么？What did you expect to see?

设置快捷键后就打不开了，重新安装也不行。
设置的快捷键：应该是 ***窗口/隐藏（具体是什么名忘了），设置成了common+r
然后就崩溃掉了，打开后出现：“OpenAI Translator”意外退出。

### 还有其他的内容吗？Anything else?

设置快捷键后就打不开了，重新安装也不行。
设置的快捷键：应该是 ***窗口/隐藏（具体是什么名忘了），设置成了common+r
然后就崩溃掉了，打开后出现：“OpenAI Translator”意外退出。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
在 terminal 里执行：

```bash
mv ~/Library/Application\ Support/xyz.yetone.apps.openai-translator/config.json{,.back}
```

**Comment by wenxinmomo** [comment]
> 在 terminal 里执行：
> 
> ```shell
> mv ~/Library/Application\ Support/xyz.yetone.apps.openai-translator/config.json{,.back}
> ```

可以了，感谢
