### ISSUE TITLE
[Bug] {{Windows版本0.3.27，无法拖动窗口，设置已关闭固定位置}}

### ISSUE THREAD

**Issue by Crabor** [openai-translator/openai-translator#1334]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.27

### 系统/浏览器版本 System/Browser version

Windows11 22635.3212/Edge 123.0.2420.10

### 复现步骤 Reproduce step

关闭固定位置，依旧无法拖动窗口

### 你看到了什么错误？What errors do you see?

无法拖动窗口

### 你期望看到什么？What did you expect to see?

窗口可以拖动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by caecfd** [comment]
0.3.26版本也有相同的问题，窗口无法移动

**Comment by qianjun1985** [comment]
也发现拖动不了，而且出现error 10061，ollama本地模型那个localhost:11434...无法连接😂

**Comment by cloudinnng** [comment]
我也出现该问题

**Comment by farion1231** [comment]
‌‌‌‌The same issue exists on Windows 11 version 23H2, operating system version 22631.3155.

**Comment by yetone** [comment]
抱歉，最新版已经修复，请更新到最新版
