### ISSUE TITLE
无法移动窗口 Windows 22H2

### ISSUE THREAD

**Issue by JaydonZhao** [openai-translator/openai-translator#1336]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.27

### 系统/浏览器版本 System/Browser version

Windows 22H2

### 复现步骤 Reproduce step

1. 双击打开App
2. 将鼠标移动到app界面顶面，试图移动窗口

### 你看到了什么错误？What errors do you see?

无法移动，鼠标移过去之后光标自动变为调整窗口大小，只能调整窗口大小，无法移动窗口，难受死了

### 你期望看到什么？What did you expect to see?

只有鼠标移动到UI最边界的时候再变成调整大小

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jinjunliu** [comment]
Same here. 暂时解决方法是回退到 [0.3.25](https://github.com/openai-translator/openai-translator/releases/tag/v0.3.25) 版本。

**Comment by bisslot** [comment]
最近几个版本更新都存在窗口控制问题，如：无法调整窗口大小、无法窗口最小化、无法窗口最大化等，希望能够解决这些问题！用起来实在不方便，谢谢！

**Comment by bisslot** [comment]
> 最近几个版本更新都存在窗口控制问题，如：无法调整窗口大小、无法窗口最小化、无法窗口最大化等，希望能够解决这些问题！用起来实在不方便，谢谢！

PS：希望字体风格及大小也可以设置那就更好了！

**Comment by JaydonZhao** [comment]
> 最近几个版本更新都存在窗口控制问题，如：无法调整窗口大小、无法窗口最小化、无法窗口最大化等，希望能够解决这些问题！用起来实在不方便，谢谢！

还有窗口移动问题，窗口调整大小问题。太痛苦了用起来

**Comment by yetone** [comment]
抱歉，最新版已经修复，请更新到最新版

**Comment by bisslot** [comment]
> 抱歉，最新版已经修复，请更新到最新版

谢谢修复！
