### ISSUE TITLE
[Bug] {{设置与ocr按钮没反应.}}

### ISSUE THREAD

**Issue by cancundeyingzi** [openai-translator/openai-translator#1337]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.27

### 系统/浏览器版本 System/Browser version

Chrome 已是最新版本 版本 122.0.6261.95（正式版本） （64 位）

### 复现步骤 Reproduce step

划词直接点击

### 你看到了什么错误？What errors do you see?

进不去设置/ocr

![image](https://github.com/openai-translator/openai-translator/assets/73635883/47088591-56e1-41e9-bcd8-54401c6b3672)

### 还有其他的内容吗？Anything else?

/

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
建议使用桌面端应用来代替浏览器插件
