### ISSUE TITLE
浏览器插件支持ollama

### ISSUE THREAD

**Issue by phantooom** [openai-translator/openai-translator#1343]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

期望浏览器插件支持ollama

### 描述 Motivation

当前客户端版本已经支持了ollama了，但是个人更多的场景是在浏览器中使用划词翻译，但是目前看浏览器插件似乎还没有支持ollama的支持。期望后续版本能够支持相关的能力。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
Ollama 跨域比较麻烦，所以浏览器插件暂不支持 Ollama

**Comment by phantooom** [comment]
感谢 @yetone 解答，我开始以为是有什么特别复杂的情况不支持呐。看起来只是想让更多的用户无感用起来。这边尝试着自己处理了一下。能够正常运行。
```
git clone https://github.com/openai-translator/openai-translator.git
cd openai-translator
pnpm install
make build-browser-extension
```
文件产出位置在 dist/browser-extension/chromium/ 下
chrome 右上角3个点-> 扩展程序 -> 管理扩展程序
右上角，打开开发者模式 加载 dist/browser-extension/chromium/ 这个插件

修改ollama配置
Linux
```
sudo vim /etc/systemd/system/ollama.service
增加如下内容
Environment="OLLAMA_HOST=0.0.0.0"
Environment="OLLAMA_ORIGINS=*"
第一条的话wsl环境可能用的到，如过是纯Linux的话可以忽略

重启ollama
sudo systemctl daemon-reload
sudo systemctl restart ollama
```

mac

```
launchctl setenv OLLAMA_ORIGINS "*"
重启ollama
```

![image](https://github.com/openai-translator/openai-translator/assets/10242001/cccaf34d-df02-4728-808a-8b1d33fcdedd)
![image](https://github.com/openai-translator/openai-translator/assets/10242001/aac8c5ec-9ce6-4e84-8cc9-d46d1098c6a9)


最后能不能加一高级配置，能够原生开启支持呐(讲道理平时用ollama的应该不太是非常初级的用户了，有个文档做个配置的话应该不是特别复杂？)。还是不太想自己改代码。

**Comment by yetone** [comment]
@phantooom 是的，一切只是为了让用户更无感，其实因为 Ollama 本身就支持 OpenAI compatible API，所以我甚至可以不单独支持 Ollama 直接写个配置文档让用户自定义 OpenAI API URL 即可，但是哪怕就多这么一步，有很多用户仍然会感到困难，会增加配置错误率，所以我的原则就是要做就做到更无痛、更极致、更「一键即达」

去终端执行命令来开启跨域对很多用户来说是更困难的事情，所以暂时不考虑在浏览器插件端支持 Ollama。

不过还是很感谢你的这个教程，对很多动手能力强的用户来说很有帮助！

**Comment by phantooom** [comment]
感谢

**Comment by puckee** [comment]
请问windows 端应该如何设置？

**Comment by LGinC** [comment]
> 请问windows 端应该如何设置？

![CleanShot 2024-04-16 at 14 31 44@2x](https://github.com/openai-translator/openai-translator/assets/15363011/7a826bd8-7890-48f6-81e0-9524901aaaed)
增加环境变量，重启ollama

**Comment by osen77** [comment]
@phantooom 请教下，我在Windows中按照你的方法下载源码从新打包，在环境变量中也添加了 OLLAMA_ORIGINS="*"，为什么在浏览器插件没有 ollama 的选项呢？
![image](https://github.com/openai-translator/openai-translator/assets/23171354/1aa4c0ec-9ec7-4bd4-8d82-f66fda37fde3)

**Comment by alex8224** [comment]
@osen77 在代码 src/common/components/Settings.tsx 的1353 行增加如下行重新make即可 
  { label: `Ollama (${t('Local Model')})`, id: 'Ollama' },

**Comment by osen77** [comment]
@alex8224 感谢，解决了。发现位置是在 1371 处增加，1353 上默认有了
![image](https://github.com/user-attachments/assets/fb8b7748-98cd-4e81-838b-bb7efd42d00d)
