### ISSUE TITLE
[Bug] {{Windows不能拖动标题栏}}

### ISSUE THREAD

**Issue by Think2twice** [openai-translator/openai-translator#1347]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.29

### 系统/浏览器版本 System/Browser version

 chrome 122.0.6261.95

### 复现步骤 Reproduce step

标题栏不能拖动，我看到你们0.3.27好像是修复macOS上的标题栏的问题了。macOS就有这个问题吗？现在Windows就有

### 你看到了什么错误？What errors do you see?

标题栏不能拖动

### 你期望看到什么？What did you expect to see?

标题栏能正常拖动

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
抱歉，最新版已经修复，请更新到最新版
