### ISSUE TITLE
[Bug] You exceeded your current quota

### ISSUE THREAD

**Issue by CrazyPoohBear** [openai-translator/openai-translator#1352]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.10

### 系统/浏览器版本 System/Browser version

edge/chrome

### 复现步骤 Reproduce step

不管翻譯什麼都會出現一樣的錯誤 甚至連潤稿都不行

### 你看到了什么错误？What errors do you see?

You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.

### 你期望看到什么？What did you expect to see?

正常使用翻譯功能

### 还有其他的内容吗？Anything else?

非常確api使用並沒有到達限制

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by MFYDev** [comment]
I am having the same issue now
