### ISSUE TITLE
[Bug] "failed to convert chunk to utf-8: invalid utf-8 sequence of 1 bytes from index 1" if using aihubmix

### ISSUE THREAD

**Issue by caopulan** [openai-translator/openai-translator#1354]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.32

### 系统/浏览器版本 System/Browser version

macOS 13

### 复现步骤 Reproduce step

Following https://doc.aihubmix.com/%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8/%E5%9C%A8OpenAI%20Translator%E4%B8%AD%E4%BD%BF%E7%94%A8

### 你看到了什么错误？What errors do you see?

"failed to convert chunk to utf-8: invalid utf-8 sequence of 1 bytes from index 1"

### 你期望看到什么？What did you expect to see?

Translation

### 还有其他的内容吗？Anything else?

I have tried official OPENAI api and don't meet this bug.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by xiaoouwang** [comment]
no response?

**Comment by unique416** [comment]
the same problem but my pc is microsoft surface 9 pro with windows operating system

**Comment by secondhh2** [comment]
same bug on windows11, OpenAI Translator v0.3.41

**Comment by SmallRabit** [comment]
same problem, windows 10, openai translator v0.3.41

**Comment by yetone** [comment]
你好，刚刚发布的最新版已修复此问题。
