### ISSUE TITLE
[已解决] [Bug] 无法更新

### ISSUE THREAD

**Issue by thomasTAT** [openai-translator/openai-translator#1366]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.33

### 系统/浏览器版本 System/Browser version

windows 11 version23H2

### 复现步骤 Reproduce step

1. 点击更新
2. 更新完成, openai translator 自动重启
3. 重启又叫我更新.

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/109513632/ad8c9545-aa0a-4af6-8745-a614f04bf50b)

### 你期望看到什么？What did you expect to see?

成功更新

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
是 Tauri updater 的 bug，等我去提个 bug

**Comment by yetone** [comment]
你们安装到的地方不是 C 盘吗？

**Comment by jas0nma** [comment]
是C盘，安装路径就是默认得目录。

**Comment by jsdfhasuh** [comment]
我也是一样的bug，重复更新

**Comment by ainlee** [comment]
完全一樣的問題
好幾個版本都不見改善
現在基本上都手動更新了，已經懶得再試了.....

**Comment by yetone** [comment]
大家不要使用 `-setup.exe` 来安装！！！！用 `-setup.exe` 来安装的话会导致无法自动更新！！！！！！！！

请务必使用 `.msi` 来安装！！！！这样才能正常自动更新到最新版本！！！

**Comment by yetone** [comment]
大家请手动卸载 OpenAI Translator，然后下载并安装最新版的 OpenAI Translator `.exe` 安装包！

这样以后就再也不会有无法自动更新到最新版的问题了！

**Comment by ainlee** [comment]
這個問題好像已經在0.4.0版之後解決！可喜可樂！
