### ISSUE TITLE
[Bug] 升级到0.33后，perplexity api 遇到报错“After the (optional) system message(s), user and assistant roles should be alternating.”

### ISSUE THREAD

**Issue by Adnios** [openai-translator/openai-translator#1371]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.3

### 系统/浏览器版本 System/Browser version

windows 11

### 复现步骤 Reproduce step

感谢作者提供优秀的软件！

我使用的是perplexity api. 配置如下图，在之前的版本完美使用，
![image](https://github.com/openai-translator/openai-translator/assets/41060790/15b9b5dc-0ce0-4b88-89f5-e78dc55c45a1)

### 你看到了什么错误？What errors do you see?

在v0.3.3上遇到报错，错误信息是：After the (optional) system message(s), user and assistant roles should be alternating
![image](https://github.com/openai-translator/openai-translator/assets/41060790/a0a7037a-b932-47ab-933c-28147789c8e2)

### 你期望看到什么？What did you expect to see?

这是v0.3.2工作正常的截图
![image](https://github.com/openai-translator/openai-translator/assets/41060790/9e20b12b-6099-4534-94e4-7c418cdbae35)

### 还有其他的内容吗？Anything else?

两天前我发了个[discussion](https://github.com/openai-translator/openai-translator/discussions/1365)，当时我以为是我的配置有问题或者perplexity api 发生了变化，今天降级到v0.3.2后便可以使用，所以感觉是新版本的问题。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by willhome360** [comment]
0.33版本问题太多了，建议不要用

**Comment by yetone** [comment]
抱歉，这个问题是由于在 0.3.33 版对 prompts 进行了优化导致的，在最新版已经回滚了其相关修改，所以此问题已经修复，你可以更新到最新版试一下
