### ISSUE TITLE
openai web 不能用了

### ISSUE THREAD

**Issue by laosuan** [openai-translator/openai-translator#1384]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.10

### 系统/浏览器版本 System/Browser version

chrome 122.0.6261.112

### 复现步骤 Reproduce step

浏览器划词翻译

### 你看到了什么错误？What errors do you see?

ChatGPT Web error: Our systems have detected unusual activity from your system. Please try again later.

### 你期望看到什么？What did you expect to see?

正常的翻译

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Ox0400** [comment]
+1

**Comment by Ox0400** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/5310853/fd1be386-36a8-4c06-ba4e-e53e4c00d2a6)

**Comment by dispassion79** [comment]
me too

**Comment by RtYkk** [comment]
![chrome_0PudXX1NOL](https://github.com/openai-translator/openai-translator/assets/45971730/b42a45ef-dbe1-4f1a-89f4-2de733697f5c)
我这里直接 error 了，应该是今天出现的。
ChatGPT 网页登录正常，聊天正常，直接打开也没有遇到任何 captcha

**Comment by goodskillprogramer** [comment]
I meet the same issue.

**Comment by Han1018** [comment]
有人有解法嗎，同樣的問題

**Comment by Sagilll** [comment]
一样的问题

**Comment by NatsumeMichiru** [comment]
same issue here

**Comment by howellhux** [comment]
occurs the same problem

**Comment by lwd-temp** [comment]
bug可复现。

`https://chat.openai.com/backend-api/conversation`返回

```json
{
    "detail": "There was a problem with your chat request. Please use a different browser or try again later."
}
```

**Comment by yetone** [comment]
抱歉，最新版的 OpenAI Translator 已经可以正常使用 ChatGPT Web 了！

**Comment by Han1018** [comment]
有看到更新至 chrome extension 了，但是還是無法使用 顯示一樣的錯誤

**Comment by RtYkk** [comment]
@Han1018 虽然我这也不能用，但是报错应该不一样了。
`Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.`

我已经尝试过按要求做，但是还是没有任何帮助。

**Comment by B1ack3ye** [comment]
Problem still exists.
```
Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.
```

The described solution for the problem is not working.

**Comment by twodogsss** [comment]
> @Han1018 虽然我这也不能用，但是报错应该不一样了。 `Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.`
> 
> 我已经尝试过按要求做，但是还是没有任何帮助。

先退出账号，再重新登录，就可以了

**Comment by twodogsss** [comment]
> Problem still exists.
> 
> ```
> Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.
> ```
> 
> The described solution for the problem is not working.

First log out of the account, then log in again, and it will return to normal.
<img width="605" alt="屏幕截图 2024-03-31 161115" src="https://github.com/openai-translator/openai-translator/assets/116331541/4ed7eb90-cae7-40c5-b02c-8bfaa4ea540b">

**Comment by Han1018** [comment]
重新登入 ChatGPT web 後解決了！！感謝！

> > @Han1018 虽然我这也不能用，但是报错应该不一样了。 `Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.`
> > 我已经尝试过按要求做，但是还是没有任何帮助。
> 
> 先退出账号，再重新登录，就可以了

**Comment by Sagilll** [comment]
> m
您好 退出账号，再重新登录，还是不行 一样的问题

**Comment by twodogsss** [comment]
> > m
> > 您好 退出账号，再重新登录，还是不行 一样的问题

删除原来的版本，下载最新的版本
如图：
![屏幕截图 2024-04-01 113803](https://github.com/openai-translator/openai-translator/assets/116331541/ff640537-d66e-407a-b750-589aa5564837)
![屏幕截图 2024-04-01 114032](https://github.com/openai-translator/openai-translator/assets/116331541/5d19d56e-1c39-4554-917d-7a14075893e4)

**Comment by Nathan7139** [comment]
今天測試mac chrome版
刪除後裝release的最新版0.4.15依舊無法使用
