### ISSUE TITLE
[Bug] {{OpenAI Translator is broken on Ubuntu22.04 LTS}}

### ISSUE THREAD

**Issue by junaire** [openai-translator/openai-translator#1392]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.35

### 系统/浏览器版本 System/Browser version

Ubuntu22.04 LTS

### 复现步骤 Reproduce step

1. 从 Release 中下载最新版本的 deb 包
2. 命令行安装 `sudo dpkg -i open-ai-translator_0.3.35_amd64.deb`
3. 出现依赖错误，使用 `sudo apt --fix-broken install` 修复
4. 从系统托盘（gnome）尝试打开 OpenAI Translator

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/77525145/0d294188-d574-4a5c-9110-fd0a67ea5904)

### 你期望看到什么？What did you expect to see?

正常工作

### 还有其他的内容吗？Anything else?

None

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Xuanwo** [comment]
> 3\. 出现依赖错误，使用 `sudo apt --fix-broken install` 修复

What's the error? open-ai-translator is packaged under `ubuntu-22.04`, it should work just fine on it.

**Comment by junaire** [comment]
> > 3. 出现依赖错误，使用 `sudo apt --fix-broken install` 修复
> 
> What's the error? open-ai-translator is packaged under `ubuntu-22.04`, it should work just fine on it.

deb package could depend on other packages so I don't think that's related. I just tried the latest release with AppImage (which should be self-contained), and I found:
The initial UI works fine, but when I clicked the settings icon, it shows the error:
![image](https://github.com/openai-translator/openai-translator/assets/77525145/210e434e-2c41-4d2b-858b-40dd313b2e2a)

Clicked the `Try again` button reproduces the original error message:
![image](https://github.com/openai-translator/openai-translator/assets/77525145/fc473e39-032d-4098-8f78-3e5c12fa85ee)

I have already built the project and run it in the command line, and I can confirm this still reproduces on main, but the console shows no logs so I don't know where to look at...

**Comment by junaire** [comment]
I highly suspect this is an upstream issue...

**Comment by junaire** [comment]
> Seems some wrong on your config dir: `openai-translator` will write config to `$XDG_CONFIG_HOME/xyz.yetone.apps.openai-translator/config.json`. Do you have `XDG_CONFIG_HOME` or `HOME` configured? Can openai-translator access `~/.config` or `~/.cache`?
> 
> You can try print those env value during startup.

```
❯ echo $HOME
/home/jun
❯ echo $XDG_CONFIG_HOME

❯ ls -al ~/.config/xyz.yetone.apps.openai-translator/
total 12
drwxrwxr-x  2 jun jun 4096  3月 29 15:03 .
drwx------ 48 jun jun 4096  4月 22 22:19 ..
-rw-rw-r--  1 jun jun 1048  4月 22 23:15 config.json
❯ ls -al ~/.cache/open-ai-translator
total 16
drwxrwxr-x  4 jun jun 4096  3月 29 15:03 .
drwx------ 57 jun jun 4096  4月 22 23:21 ..
drwxrwxr-x  2 jun jun 4096  3月 29 15:03 CacheStorage
drwxrwxr-x  3 jun jun 4096  3月 29 15:03 WebKitCache
```
Not sure but openai translator does write something into the desired directories...

**Comment by Xuanwo** [comment]
Please also check `~/.local/share/xyz.yetone.apps.openai-translator`.

**Comment by junaire** [comment]
> Please also check `~/.local/share/xyz.yetone.apps.openai-translator`. I expect to see:
> 
> ```shell
> /home/xuanwo/.local/share/xyz.yetone.apps.openai-translator/
> ├── databases
> │   └── indexeddb
> │       ├── v0 -> /home/xuanwo/.local/share/xyz.yetone.apps.openai-translator/databases/indexeddb
> │       └── v1
> │           └── tauri_localhost_0
> │               └── E245F118A2329D74BB22E76C9F89A7C7032203F1EE2C611EE7E19D6B6D1EB50B
> │                   ├── IndexedDB.sqlite3
> │                   ├── IndexedDB.sqlite3-shm
> │                   └── IndexedDB.sqlite3-wal
> └── localstorage
>     ├── tauri_localhost_0.localstorage
>     ├── tauri_localhost_0.localstorage-shm
>     └── tauri_localhost_0.localstorage-wal
> 
> 8 directories, 6 files
> ```
> 
> Try removing them all if there are some old content there.

I removed every old stuff and downloaded the latest version. Below is my results:
```
.
└── databases
    └── indexeddb
        ├── databases
        │   └── indexeddb
        │       ├── v0 -> /home/jun/.local/share/xyz.yetone.apps.openai-translator/databases/indexeddb/databases/indexeddb
        │       └── v1
        │           └── tauri_localhost_0
        │               └── E245F118A2329D74BB22E76C9F89A7C7032203F1EE2C611EE7E19D6B6D1EB50B
        │                   ├── IndexedDB.sqlite3
        │                   ├── IndexedDB.sqlite3-shm
        │                   └── IndexedDB.sqlite3-wal
        ├── deviceidhashsalts
        │   └── 1
        ├── localstorage
        │   ├── tauri_localhost_0.localstorage
        │   ├── tauri_localhost_0.localstorage-shm
        │   └── tauri_localhost_0.localstorage-wal
        ├── mediakeys
        │   └── v1
        │       └── salt
        └── storage
            ├── salt
            └── SNVKpYwvLVxYgAmL-TXRKis9kf_53dJf3ir83LKJBTM
                └── SNVKpYwvLVxYgAmL-TXRKis9kf_53dJf3ir83LKJBTM
                    └── origin

16 directories, 9 files
```

**Comment by Xuanwo** [comment]
> downloaded

What does `downloaded` mean? This issue still exist after cleanup `~/.local/share/xyz.yetone.apps.openai-translator/`?

**Comment by Xuanwo** [comment]
> Unfortunately, nothing changed, the issue still exists.

Interesing, let's dive deep. Are you ready to start this journey?

**Comment by junaire** [comment]
> Hi, @junaire, please call `cargo tauri dev` under project root. You can right click the poped up windows to open devtools:
> 
> ![image](https://private-user-images.githubusercontent.com/5351546/324529700-28dbdab7-5725-46c2-8178-510b5aaf6684.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MDIwNDAsIm5iZiI6MTcxMzgwMTc0MCwicGF0aCI6Ii81MzUxNTQ2LzMyNDUyOTcwMC0yOGRiZGFiNy01NzI1LTQ2YzItODE3OC01MTBiNWFhZjY2ODQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjJUMTYwMjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE0MThmMGI4YjkzNmUyYzY0ZmFjYzNkZjBjZTMxMjAzMzJkYmU5NDBjOTFmMjM1NGYxZGEyNTBmNTM5NTkyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.c0umvf5KqGHLvrwi0PGniX6Sjg1d4sJFO3z2_xRl_cg)
> 
> Please print the error message in console you can find.

Thanks, now I know the right way to debug this. Below is my logs when I clicked the settings button:
```
[Log] OpenFailedError (ErrorFallback.tsx, line 21)
[Error] The above error occurred in the <TranslateModeSelector> component:

TranslateModeSelector@http://localhost:3333/src/common/components/Settings.tsx:122:8
div
@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:454:40
Styled(div)
UID2@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:121:50
UIDConsumer@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:150:16
FormControl2@http://localhost:3333/node_modules/.vite/deps/baseui-sd_form-control.js:257:20
Field2@http://localhost:3333/node_modules/.vite/deps/rc-field-form.js:2250:20
WrapperField@http://localhost:3333/node_modules/.vite/deps/rc-field-form.js:2639:19
div
FormItem@http://localhost:3333/src/common/components/Form/item.tsx:21:16
FormItem
div
div
form
Form2@http://localhost:3333/node_modules/.vite/deps/rc-field-form.js:3739:18
@http://localhost:3333/src/common/components/Form/form.ts:109:16
div
InnerSettings@http://localhost:3333/src/common/components/Settings.tsx:1415:9
div
InnerTranslator@http://localhost:3333/src/common/components/Translator.tsx:473:51
Suspense
GlobalSuspense@http://localhost:3333/src/common/components/GlobalSuspense.tsx:19:11
ThemeProvider2@http://localhost:3333/node_modules/.vite/deps/chunk-LIQX2ESN.js:23:20
UIDReset@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:143:20
div
@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:454:40
Styled(div)
LayersManager2@http://localhost:3333/node_modules/.vite/deps/chunk-2SBMVLQG.js:242:20
BaseProvider2@http://localhost:3333/node_modules/.vite/deps/baseui-sd.js:49:23
DevProvider@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:181:10
div
ErrorBoundary@http://localhost:3333/node_modules/.vite/deps/react-error-boundary.js:18:10
Translator@http://localhost:3333/src/common/components/Translator.tsx:440:15
div
InnerWindow@http://localhost:3333/src/tauri/components/Window.tsx:123:15
ThemeProvider2@http://localhost:3333/node_modules/.vite/deps/chunk-LIQX2ESN.js:23:20
UIDReset@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:143:20
div
@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:454:40
Styled(div)
LayersManager2@http://localhost:3333/node_modules/.vite/deps/chunk-2SBMVLQG.js:242:20
BaseProvider2@http://localhost:3333/node_modules/.vite/deps/baseui-sd.js:49:23
DevProvider@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:181:10
ErrorBoundary@http://localhost:3333/node_modules/.vite/deps/react-error-boundary.js:18:10
Window@http://localhost:3333/src/tauri/components/Window.tsx:43:15
App@http://localhost:3333/src/tauri/App.tsx:34:82

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
	logCapturedError (chunk-AY6FKDNS.js:14036)
	callback (chunk-AY6FKDNS.js:14082)
	callCallback (chunk-AY6FKDNS.js:10511)
	commitUpdateQueue (chunk-AY6FKDNS.js:10528)
	commitLayoutEffectOnFiber (chunk-AY6FKDNS.js:17065)
	commitLayoutMountEffects_complete (chunk-AY6FKDNS.js:17976)
	commitLayoutEffects_begin (chunk-AY6FKDNS.js:17965)
	commitLayoutEffects (chunk-AY6FKDNS.js:17916)
	commitRootImpl (chunk-AY6FKDNS.js:19349)
	commitRoot (chunk-AY6FKDNS.js:19273)
	performSyncWorkOnRoot (chunk-AY6FKDNS.js:18891)
	flushSyncCallbacks (chunk-AY6FKDNS.js:9135)
	(anonymous function) (chunk-AY6FKDNS.js:18623)
[Error] Failed to load resource: WebKit encountered an internal error (promotions.json, line 0)
[Error] Failed to load resource: WebKit encountered an internal error (promotions.json, line 0)
[Error] Failed to load resource: WebKit encountered an internal error (promotions.json, line 0)
```

**Comment by Xuanwo** [comment]
> [Error] Failed to load resource: WebKit encountered an internal error (promotions.json, line 0)

```rust
export async function fetchPromotions(): Promise<IPromotionResponse> {
    const resp = await fetch(
        `https://raw.githubusercontent.com/yetone/openai-translator-configs/main/promotions.json?ts=${Date.now()}`,
        { cache: 'no-cache' }
    )
    if (!resp.ok) {
        throw new Error(resp.statusText)
    }
    return resp.json()
}
```

Aha, openai-translator start failed for loading promotions. cc @yetone.

**Comment by Xuanwo** [comment]
Hi, @junaire, would you like to give this a try? https://github.com/openai-translator/openai-translator/pull/1473

**Comment by junaire** [comment]
> Hi, @junaire, would you like to give this fix a try? #1473

Sorry, unless I misapplied the patch, it doesn't work :(

```
Failed to load resource: WebKit encountered an internal error
```
Doesn't this imply some kind of bug of libwebkit? Which version you are using?

**Comment by Xuanwo** [comment]
> Sorry, unless I misapplied the patch, it doesn't work :(

If it doesn't work, it should have new errors like `Error fetching promotions`. Can you read them?

**Comment by Xuanwo** [comment]
I try to remove the event on this butten, please give this PR a try: https://github.com/openai-translator/openai-translator/pull/1475

**Comment by junaire** [comment]
> > Sorry, unless I misapplied the patch, it doesn't work :(
> 
> If it doesn't work, it should have new errors like `Error fetching promotions`. Can you read them?

Yes, it has trouble loading the promotion json, but I can observe the error when the initial UI starts up too, so it's unlikely the reason.

> I try to remove the event on this butten, please give this PR a try: **https://github.com/openai-translator/openai-translator/pull/1475**

Still exists :(

BTW, I have some new logs:
```
[Error] OpenFailedError: OpenFailedError
	useObservable (dexie-react-hooks.js:91)
	TranslateModeSelector (Settings.tsx:127)
	renderWithHooks (chunk-AY6FKDNS.js:12171)
	updateFunctionComponent (chunk-AY6FKDNS.js:14577)
	callCallback2 (chunk-AY6FKDNS.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-AY6FKDNS.js:3699)
	invokeGuardedCallback (chunk-AY6FKDNS.js:3733)
	beginWork$1 (chunk-AY6FKDNS.js:19761)
	performUnitOfWork (chunk-AY6FKDNS.js:19194)
	workLoopSync (chunk-AY6FKDNS.js:19133)
	renderRootSync (chunk-AY6FKDNS.js:19112)
	performSyncWorkOnRoot (chunk-AY6FKDNS.js:18870)
	flushSyncCallbacks (chunk-AY6FKDNS.js:9135)
	(anonymous function) (chunk-AY6FKDNS.js:18623)
```

```
[Error] DatabaseClosedError: UnknownError Connection to Indexed Database server lost. Refresh the page to try again
 UnknownError: Connection to Indexed Database server lost. Refresh the page to try again
	useObservable (dexie-react-hooks.js:91)
	InnerTranslator (Translator.tsx:660)
	renderWithHooks (chunk-AY6FKDNS.js:12171)
	updateFunctionComponent (chunk-AY6FKDNS.js:14577)
	callCallback2 (chunk-AY6FKDNS.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-AY6FKDNS.js:3699)
	invokeGuardedCallback (chunk-AY6FKDNS.js:3733)
	beginWork$1 (chunk-AY6FKDNS.js:19761)
	performUnitOfWork (chunk-AY6FKDNS.js:19194)
	workLoopSync (chunk-AY6FKDNS.js:19133)
	renderRootSync (chunk-AY6FKDNS.js:19112)
	performSyncWorkOnRoot (chunk-AY6FKDNS.js:18870)
	flushSyncCallbacks (chunk-AY6FKDNS.js:9135)
	(anonymous function) (chunk-AY6FKDNS.js:18623)
[Warning] There is a LayersManager already exists in your application. It is not recommended to have more than one LayersManager in an application. (chunk-YDDJB4SJ.js, line 398)
[Error] DatabaseClosedError: UnknownError Connection to Indexed Database server lost. Refresh the page to try again
 UnknownError: Connection to Indexed Database server lost. Refresh the page to try again
	useObservable (dexie-react-hooks.js:91)
	InnerTranslator (Translator.tsx:660)
	renderWithHooks (chunk-AY6FKDNS.js:12171)
	updateFunctionComponent (chunk-AY6FKDNS.js:14577)
	callCallback2 (chunk-AY6FKDNS.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-AY6FKDNS.js:3699)
	invokeGuardedCallback (chunk-AY6FKDNS.js:3733)
	beginWork$1 (chunk-AY6FKDNS.js:19761)
	performUnitOfWork (chunk-AY6FKDNS.js:19194)
	workLoopSync (chunk-AY6FKDNS.js:19133)
	renderRootSync (chunk-AY6FKDNS.js:19112)
	recoverFromConcurrentError (chunk-AY6FKDNS.js:18732)
	performSyncWorkOnRoot (chunk-AY6FKDNS.js:18875)
	flushSyncCallbacks (chunk-AY6FKDNS.js:9135)
	(anonymous function) (chunk-AY6FKDNS.js:18623)
[Error] The above error occurred in the <InnerTranslator> component:

InnerTranslator@http://localhost:3333/src/common/components/Translator.tsx:473:51
Suspense
GlobalSuspense@http://localhost:3333/src/common/components/GlobalSuspense.tsx:19:11
ThemeProvider2@http://localhost:3333/node_modules/.vite/deps/chunk-LIQX2ESN.js:23:20
UIDReset@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:143:20
div
@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:454:40
Styled(div)
LayersManager2@http://localhost:3333/node_modules/.vite/deps/chunk-YDDJB4SJ.js:242:20
BaseProvider2@http://localhost:3333/node_modules/.vite/deps/baseui-sd.js:49:23
DevProvider@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:181:10
div
ErrorBoundary@http://localhost:3333/node_modules/.vite/deps/react-error-boundary.js:18:10
Translator@http://localhost:3333/src/common/components/Translator.tsx:440:15
div
InnerWindow@http://localhost:3333/src/tauri/components/Window.tsx:123:15
ThemeProvider2@http://localhost:3333/node_modules/.vite/deps/chunk-LIQX2ESN.js:23:20
UIDReset@http://localhost:3333/node_modules/.vite/deps/chunk-C7D3XKWM.js:143:20
div
@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:454:40
Styled(div)
LayersManager2@http://localhost:3333/node_modules/.vite/deps/chunk-YDDJB4SJ.js:242:20
BaseProvider2@http://localhost:3333/node_modules/.vite/deps/baseui-sd.js:49:23
DevProvider@http://localhost:3333/node_modules/.vite/deps/chunk-LR4KRP27.js:181:10
ErrorBoundary@http://localhost:3333/node_modules/.vite/deps/react-error-boundary.js:18:10
Window@http://localhost:3333/src/tauri/components/Window.tsx:43:15
App@http://localhost:3333/src/tauri/App.tsx:34:82

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
	logCapturedError (chunk-AY6FKDNS.js:14036)
	callback (chunk-AY6FKDNS.js:14082)
	callCallback (chunk-AY6FKDNS.js:10511)
	commitUpdateQueue (chunk-AY6FKDNS.js:10528)
	commitLayoutEffectOnFiber (chunk-AY6FKDNS.js:17065)
	commitLayoutMountEffects_complete (chunk-AY6FKDNS.js:17976)
	commitLayoutEffects_begin (chunk-AY6FKDNS.js:17965)
	commitLayoutEffects (chunk-AY6FKDNS.js:17916)
	commitRootImpl (chunk-AY6FKDNS.js:19349)
	commitRoot (chunk-AY6FKDNS.js:19273)
	performSyncWorkOnRoot (chunk-AY6FKDNS.js:18891)
	flushSyncCallbacks (chunk-AY6FKDNS.js:9135)
	(anonymous function) (chunk-AY6FKDNS.js:18623)
[Error] Unhandled Promise Rejection: DatabaseClosedError: UnknownError Connection to Indexed Database server lost. Refresh the page to try again
 UnknownError: Connection to Indexed Database server lost. Refresh the page to try again
 ```

**Comment by Xuanwo** [comment]
The logic about init and connect Indexed db is not implemented in `openai-translator`. Please try set new `$HOME` to `/tmp` and start openai?

**Comment by Xuanwo** [comment]
Thanks for the new log. I will checkout tomorrow 🥰

**Comment by Xuanwo** [comment]
Hi, @junaire, I submit a PR to print errors while open indexeddb failed: https://github.com/openai-translator/openai-translator/pull/1478. Please give it a try and share the error message.

**Comment by Xuanwo** [comment]
> This looks so weird like they have some retry logic? and we indeed triggered this 3 times, then it fails. BTW, last time I somehow debugged `err.inner.message` is exactly `connection to indexed database server lost. refresh the page to try again`, which implies nothing...

really weird. Can you inspect the indexeddb in devtools? Anything special?

**Comment by junaire** [comment]
> ```js
> _state
> ```

I'm unfamiliar with frontend techstack so I googled it a bit and I found my UI is somehow different than what I saw in the internet. (No Application page but Storage). Below is the screenshot and I can't found indexeddb.
![image](https://github.com/openai-translator/openai-translator/assets/77525145/e4ca7d8b-633a-4f0f-a24e-1cdece80f1db)

**Comment by Xuanwo** [comment]
Yes, that's really weird. Here is my side:

![image](https://github.com/openai-translator/openai-translator/assets/5351546/1ad7de80-2da4-42b8-ad3f-b158b2ce4ab5)

Seems indexeddb in your webkit doesn't work well.

Please try the following js in devtools:

```js
let db;
const request = indexedDB.open("MyTestDatabase");
request.onerror = (event) => {
    console.error("Why didn't you allow my web app to use IndexedDB?!");
};
request.onsuccess = (event) => {
    console.info("Load success");
    db = event.target.result;
};
```

**Comment by Xuanwo** [comment]
Does indexeddb works correctly on your own browser (chromium based) correctly?

**Comment by junaire** [comment]
> Does indexeddb work correctly on your own browser (chromium based) correctly? You can use the same scripts.

Yes, it's good.

**Comment by Xuanwo** [comment]
Hi, @junaire, to make it's easier to debug, I setup a repro project at https://github.com/Xuanwo/tauri-indexeddb-openfailed. Would you like to give it a try? 

It's an empty project that did nothing. If we can still reproduce this issue, it's must be not related to openai-translator.

**Comment by junaire** [comment]
Hi, @Xuanwo @yetone I think I fixed the bug. I bet this is the most weird bug I ever seen in my life. Still I don't understand why this happens, but it indeed works. Below is my fix:
```diff
diff --git a/src/common/services/promotion.ts b/src/common/services/promotion.ts
index 5ec9cd7..0f95beb 100644
--- a/src/common/services/promotion.ts
+++ b/src/common/services/promotion.ts
@@ -36,14 +36,7 @@ export interface IPromotionResponse {
 }

 export async function fetchPromotions(): Promise<IPromotionResponse> {
-    const resp = await fetch(
-        `https://raw.githubusercontent.com/yetone/openai-translator-configs/main/promotions.json?ts=${Date.now()}`,
-        { cache: 'no-cache' }
-    )
-    if (!resp.ok) {
-        throw new Error(resp.statusText)
-    }
-    return resp.json()
+    return {}
 }
```
Note **it's not about failing to fetch config, it's about `fetch` itself!** As long as you return an empty json, we're good...
I tried to replace the URL to `www.example.com` and returned `{}` the bug still reproduces. Any ideas about how `fetch` could affect the behavior of IndexedDB?

**Comment by Xuanwo** [comment]
> I tried to replace the URL to `www.example.com` and returned `{}` the bug still reproduces.

Does `fetch` return 'ok'? Or does the indexeddb break regardless of what `fetch` returns, as soon as we call it?

**Comment by junaire** [comment]
> > I tried to replace the URL to `www.example.com` and returned `{}` the bug still reproduces.
> 
> Does `fetch` return 'ok'? Or does the indexeddb break regardless of what `fetch` returns, as soon as we call it?

Nah, looks like whatever I try to fetch the only thing I got is `Failed to load resource: WebKit encountered an internal error`, even in the console.

**Comment by junaire** [comment]
> > > I tried to replace the URL to `www.example.com` and returned `{}` the bug still reproduces.
> > 
> > 
> > Does `fetch` return 'ok'? Or does the indexeddb break regardless of what `fetch` returns, as soon as we call it?
> 
> Nah, looks like whatever I try to fetch the only thing I got is `Failed to load resource: WebKit encountered an internal error`, even in the console.

https://github.com/tauri-apps/tauri/issues/1836

**Comment by Xuanwo** [comment]
> It even failed to connect to my local server created by `python3 -m http.server` , but with a slightly different error message `Connection terminated unexpectedly`

That's really weird. Do you have http proxy settings or something? Try cleanup them all and try again.

**Comment by junaire** [comment]
> > It even failed to connect to my local server created by `python3 -m http.server` , but with a slightly different error message `Connection terminated unexpectedly`
> 
> That's really weird. Do you have http proxy settings or something? Try cleanup them all and try again.

OMG, I disabled the proxy settings in the global settings then it works! With any patches applied!

**Comment by Xuanwo** [comment]
But I still don't know how proxy settings affect indexed db. Would you like to share your settings you are using?

**Comment by junaire** [comment]
> But I still don't know how proxy settings affect indexed db. Would you like to share your settings you are using?

I'm using clash of Windows, a legacy version. 
![image](https://github.com/openai-translator/openai-translator/assets/77525145/fb2df5a4-045f-4ac4-8593-ab3c2e6f181a)

**Comment by junaire** [comment]
OK, I'd like to close the issue since it's only about my local config. Still, I don't understand how can proxy settings affect the behavior of `fetch`, then affect the behavior of `indexeddb`. Maybe there're some further bugs in webkit or something but that's another story. Anyway, I'm glad that we finally get there and many thanks to @Xuanwo! <3

**Comment by Xuanwo** [comment]
Great, with `NO_PROXY=127.0.0.0/8`, I can reproduce the same error.

I think linux's no proxy setting doesn't support ip ranges, thus `127.0.0.0/8` doesn't work as you expected. So all requests to 127.0.0.1 failed which indexeddb depends on too.
