### ISSUE TITLE
[Bug] {{提示字数超出限制.}}

### ISSUE THREAD

**Issue by kevingekun** [openai-translator/openai-translator#1403]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.37

### 系统/浏览器版本 System/Browser version

macos 14.4.1

### 复现步骤 Reproduce step

输入 hello 点翻译即可复现

### 你看到了什么错误？What errors do you see?

字数超出限制

### 你期望看到什么？What did you expect to see?

正常返回数据

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
什么模型？

**Comment by leibin1204** [comment]
> 什么模型？

我用Azure也遇到了这个问题。大约0.3.10还是好的。最近的版本都有问题。

**Comment by atmomomo** [comment]
Azure

**Comment by mingchau** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/18564039/4f8e9f8c-3848-4464-b106-e5f7c0e852b3)
![image](https://github.com/openai-translator/openai-translator/assets/18564039/aeb69e5d-4fb2-4560-8756-4ee6a5ea06c1)

今天更新到0.3.38后报错，昨天0.3.37还是正常的。

**Comment by kevingekun** [comment]
0.3.38已正常
