### ISSUE TITLE
[Bug] 0.3.38引入了max_tokens参数后使用Azure服务出错

### ISSUE THREAD

**Issue by mingchau** [openai-translator/openai-translator#1406]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.38

### Model name

gpt-3.5-turbo

### 系统/浏览器版本 System/Browser version

Windows 11

### 复现步骤 Reproduce step

更新到0.3.38版本后，输入任意文字，如`你好`，然后执行任意动作，如`翻译`或者`润色`

### 你看到了什么错误？What errors do you see?

This model's maximum context length is 4096 tokens. However, you requested 4170 tokens (74 in the messages, 4096 in the completion). Please reduce the length of the messages or completion.
![image](https://github.com/openai-translator/openai-translator/assets/18564039/65c4c412-7b4f-44f6-943d-7ccec19f3c10)

### 你期望看到什么？What did you expect to see?

正常的结果

### 还有其他的内容吗？Anything else?

https://github.com/openai-translator/openai-translator/blob/e7927c48977d8598bd6dbb7907fde7c7e44d41f8/src/common/engines/azure.ts#L36
最新的commit写死了`max_tokens: 4096`，根据微软azure openai service的文档，max_tokens是一个可选参数，表示允许生成的答案的最大token数，而且不能超过4096-prompt tokens。

https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions
![image](https://github.com/openai-translator/openai-translator/assets/18564039/25614a38-b7d4-4eac-9d8c-83c2a6c0a169)

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
我是为了解决这个问题，由于我没有 Azure 服务，所以无法测试，你在之前的版本遇到过这个问题吗？https://github.com/openai-translator/openai-translator/issues/1403

**Comment by mingchau** [comment]
> 我是为了解决这个问题，由于我没有 Azure 服务，所以无法测试，你在之前的版本遇到过这个问题吗？#1403

之前的0.3.37版本是正常的，就是今天更新到0.3.38版本后遇到的。


我在0.3.38版本下使用Fiddler抓包：
![image](https://github.com/openai-translator/openai-translator/assets/18564039/96799419-9cdc-4dd7-8c94-e176bb2e7c20)


4096-207=3889
修改max_tokens后进行请求重放，如果max_tokens设置为3889、3890则正常：
![image](https://github.com/openai-translator/openai-translator/assets/18564039/e7bc2f09-8442-41d4-962c-d5115cc4e6d2)

![image](https://github.com/openai-translator/openai-translator/assets/18564039/baa5a904-4e26-40e2-9b44-14ca995957ce)

加到3891就失败了：

![image](https://github.com/openai-translator/openai-translator/assets/18564039/2cb5a7af-4de9-428d-b3ed-2913b99996fe)


不加max_tokens参数时是正常的：
![image](https://github.com/openai-translator/openai-translator/assets/18564039/dd0fcc97-5abc-4616-910a-59cac00dc1e2)

**Comment by mingchau** [comment]
v0.3.39 已解决
