### ISSUE TITLE
Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.

### ISSUE THREAD

**Issue by Jerry199022** [openai-translator/openai-translator#1422]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.40

### Model name

web Default (GPT-3.5) (gpt3.5)

### 系统/浏览器版本 System/Browser version

win11 & Cent Browser  5.1.1130.26

### 复现步骤 Reproduce step

無論是網頁選擇後跳出的圖標和工具欄中的圖標都會提示次錯誤.

### 你看到了什么错误？What errors do you see?

Error: Failed to get arkose token. Please keep https://chat.openai.com open and try again. If it still doesn't work, type some characters in the input box of chatgpt web page and try again.

### 你期望看到什么？What did you expect to see?

確認過同樣的設置在Chrome中是可以用的,就是在Cent Browser不行.希望可以盡快修復.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by allenyllee** [comment]
Same on Brave browser 1.65.114 & win 10

**Comment by yetone** [comment]
https://github.com/openai-translator/openai-translator/blob/main/docs/chatgpt-cn.md

**Comment by allenyllee** [comment]
@yetone I follow the instruction, but still doesn't work...

**Comment by DesphySallau** [comment]
我有同样的问题，用了各种方法包括但不限于重新登录openai，卸载安装新版都没什么用

**Comment by zzhou59** [comment]
@yetone I got the same issue for a while. The solution you provided never worked.

**Comment by jerrere** [comment]
Same. The solution doesn't work.

**Comment by karasHou** [comment]
问题还未解决为什么关闭了？ @yetone  普通浏览器也无法使用，chrome
