### ISSUE TITLE
[Bug] 0.3.44 快捷键无效。

### ISSUE THREAD

**Issue by suenley** [openai-translator/openai-translator#1444]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.44

### Model name

openai

### 系统/浏览器版本 System/Browser version

win11

### 复现步骤 Reproduce step

更新后发现我之前定义的快捷键ctrl + alt + t 无效了。

### 你看到了什么错误？What errors do you see?

没有任何错误，内容没有被复制，也没有唤醒OT。

### 你期望看到什么？What did you expect to see?

反馈一下这个问题。

### 还有其他的内容吗？Anything else?

没有

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hoody4032** [comment]
I experienced the same problem.

**Comment by 524785937** [comment]
是这样的 我还以为咋了呢

**Comment by suenley** [comment]
> I experienced the same problem.
> 是这样的 我还以为咋了呢

It seems that this is indeed a bug./看来，这的确是一个bug。

**Comment by yetone** [comment]
此问题已在最新版中修复
