### ISSUE TITLE
在设置中增加改变字体大小的选项

### ISSUE THREAD

**Issue by hoody4032** [openai-translator/openai-translator#1445]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

在设置中增加改变字体大小的选项

### 描述 Motivation

现在的字体对我来说有点小

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版中已支持设置字体大小
