### ISSUE TITLE
[Bug] 0.3.45版本快捷键失效，

### ISSUE THREAD

**Issue by hixcao** [openai-translator/openai-translator#1454]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.45

### Model name

win10

### 系统/浏览器版本 System/Browser version

win10

### 复现步骤 Reproduce step

0.3.43版本，是可以用shift+alt+D，快速翻译的，升级之后无法使用

### 你看到了什么错误？What errors do you see?

v0.3.45版本无法使用任何快捷键快速调出软件翻译

### 你期望看到什么？What did you expect to see?

修复 修复

### 还有其他的内容吗？Anything else?

没有

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by qiqi0606** [comment]
同样出现了这个问题

**Comment by happykkAi** [comment]
我晚上刚升级 以为是我 键盘的问题

**Comment by Edwardsqca** [comment]
3.44和3.45都有这样的问题，我也一样中招了。

**Comment by mayixb** [comment]
一样

**Comment by yetone** [comment]
此问题已在最新版中修复
