### ISSUE TITLE
[Bug] Mac 0.3.47版本写作快捷键失效

### ISSUE THREAD

**Issue by happykkAi** [openai-translator/openai-translator#1456]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.45

### Model name

gpt-4

### 系统/浏览器版本 System/Browser version

macos 14.4.1

### 复现步骤 Reproduce step

翻译快捷键不起作用

### 你看到了什么错误？What errors do you see?

无

### 你期望看到什么？What did you expect to see?

无

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by shouyiwang** [comment]
以后的版本都有同样的问题。Mac取词失败

**Comment by yetone** [comment]
此问题已在最新版中修复
