### ISSUE TITLE
[已解决] [Bug] 自动更新重启后依然是旧版本，并且再次提示更新。

### ISSUE THREAD

**Issue by iibrat** [openai-translator/openai-translator#1460]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.45

### Model name

kimi

### 系统/浏览器版本 System/Browser version

windows11

### 复现步骤 Reproduce step

启动应用 》提示更新 》更新完成自动重启 》又提示更新
上次更新没有报错，但更新好像没有成功。

### 你看到了什么错误？What errors do you see?

没有错误

### 你期望看到什么？What did you expect to see?

更新成新的版本

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by iibrat** [comment]
我发现更新是重新安装了一个新版本，但老版本还在。现在电脑上两个版本都可以打开。

**Comment by enximi** [comment]
自动更新下载安装的是OpenAI.Translator_version_x64_en-US.msi。你最开始安装的时候应该是安装的另一个版本，这两安装位置不一样所以就这样了。希望作者修一下。

**Comment by yetone** [comment]
大家不要使用 `-setup.exe` 来安装！！！！用 `-setup.exe` 来安装的话会导致无法自动更新！！！！！！！！

请务必使用 `.msi` 来安装！！！！这样才能正常自动更新到最新版本！！！

**Comment by jsdfhasuh** [comment]
现在又开始反复更新了

**Comment by kkbruce** [comment]
@yetone 0.4.33 又出現一樣的問題。

我已經移除舊版，並且手動重新下載 0.4.33 的 `.exe` 安裝，只是打開設定頁面，就會跑出更新提示。

![image](https://github.com/user-attachments/assets/36b19c6d-cb62-4a67-a8cb-ee1eeab654b8)

**Comment by jaycecd** [comment]
发现同样的问题

**Comment by Estrella-071** [comment]
same error
