### ISSUE TITLE
[已解决] [Bug] 更新后不能启动

### ISSUE THREAD

**Issue by hoody4032** [openai-translator/openai-translator#1466]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.3.49

### Model name

chatgpt4

### 系统/浏览器版本 System/Browser version

Win11 version 22H2

### 复现步骤 Reproduce step

When I started the tool, it popped up a dialog with following error.
![image](https://github.com/openai-translator/openai-translator/assets/3246146/17e5a607-bc5e-415e-9afd-57138a170d61)

Microsoft Edge can't read and write to its data directory:

C:\Program Files\OpenAl Translator\am Files
(x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\EBWe
bView

### 你看到了什么错误？What errors do you see?

Microsoft Edge can't read and write to its data directory:

C:\Program Files\OpenAl Translator\am Files
(x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\EBWe
bView

### 你期望看到什么？What did you expect to see?

no this popped up dialog

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Mosney** [comment]
---------------------------
无法创建数据目录
---------------------------
Microsoft Edge 无法读取和写入其数据目录:

        C:\Program Files\OpenAI Translator\soft\EdgeUpdate\ClientState\{F3017226-FE2A-4295-8BDF-00C3A9A7E4C5}\EBWebView
---------------------------
确定   
---------------------------


Same here

**Comment by yetone** [comment]
被 Windows Defender 误杀导致的，请下载这个版本 `x64-setup.exe`

**Comment by Mosney** [comment]
我没有使用defender，看了看杀毒软件日志也确实没有删除过文件，看了一下似乎压根没有`soft`和`am Files (x86)`这两个目录
```
❯ dir

    Directory: C:\Program Files\OpenAI Translator

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----    2024.4.23 星期二     0:00                resources
-a---    2024.4.22 星期一    14:56       28610048 OpenAI Translator.exe
-a---    2024.4.23 星期二     0:00            976 Uninstall OpenAI Translator.lnk
```

**Comment by yetone** [comment]
@Mosney 重新安装 *_x64-setup.exe 版本的可以正常启动吗？

**Comment by Mosney** [comment]
> @Mosney 重新安装 *_x64-setup.exe 版本的可以正常启动吗？

确实只在MSI安装包出现，exe安装包是没有问题的，  
另外上面的两个弹窗都是Edge webview发起的，执行文件路径为
`"C:\Program Files (x86)\Microsoft\EdgeWebView\Application\123.0.2420.97\msedgewebview2.exe"`

**Comment by Mosney** [comment]
看了一下好像是缺失文件，exe安装完后目录是这样的，存在上述的两个目录：
```
❯ dir

    Directory: C:\Users\user\AppData\Local\OpenAI Translator

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----    2024.4.23 星期二     0:10                am Files (x86)
d----    2024.4.23 星期二     0:10                resources
d----    2024.4.23 星期二     0:10                soft
-a---    2024.4.22 星期一    22:56       28610048 OpenAI Translator.exe
-a---    2024.4.23 星期二     0:10         509115 uninstall.exe

```

**Comment by yetone** [comment]
应该是 Tauri 的打包器坏了，我去他们那看看有没有相关 issue

**Comment by yetone** [comment]
@Mosney 

大家不要使用 `-setup.exe` 来安装！！！！用 `-setup.exe` 来安装的话回到无法自动更新！！！！！！！！

请务必使用 `.msi` 来安装！！！！这样才能正常自动更新到最新版本！！！

**Comment by Mosney** [comment]
@yetone 但是现在的问题是MSI根本不能正常工作，自动更新的话手动更也没什么

**Comment by yetone** [comment]
@Mosney 正在修复 `.msi` 的问题，下一个版本会好

**Comment by yetone** [comment]
大家请手动卸载 OpenAI Translator，然后下载并安装最新版的 OpenAI Translator `.exe` 安装包！

**Comment by pretenderlu** [comment]
我卸载后重新安装exe也报错，是不是路径还得自己改一下

**Comment by Jinying-Tang** [comment]
> 我卸载后重新安装exe也报错，是不是路径还得自己改一下
我也是安装在原来的路径，确实还是不行，后来换个路径就好了，很奇怪

**Comment by yetone** [comment]
> 我卸载后重新安装exe也报错，是不是路径还得自己改一下

你安装的是 0.4.0 的 .exe 吗？我刚刚完全卸载重试了一下，没发现问题

**Comment by Jinying-Tang** [comment]
> > 我卸载后重新安装exe也报错，是不是路径还得自己改一下
> 
> 你安装的是 0.4.0 的 .exe 吗？我刚刚完全卸载重试了一下，没发现问题

是的，刚试了下，我原来是安装在c:\program files下的， 把原来的安装uninstall后，再安装在这个目录下，安装目录下没有soft目录，我又uninstall后再安装到默认的app data下，就可以了

**Comment by delicacyyy** [comment]
我听说 `main.rs`[里的](https://github.com/nextai-translator/nextai-translator/blob/96c62a0ddc7235069a29db201a5ec6d8579791c8/src-tauri/src/main.rs#L488)`let server = Server::http("127.0.0.1:62007").unwrap();`会报错`An attempt was made to access a socket in a way forbidden by its access permissions` 所以程序还有可能起不来
