### ISSUE TITLE
[Bug]0.3.49 点击动作管理器报错

### ISSUE THREAD

**Issue by figozhu** [openai-translator/openai-translator#1467]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.3.49

### Model name

设备管理器

### 系统/浏览器版本 System/Browser version

win10/chorme

### 复现步骤 Reproduce step

点击设备管理器

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/4566514/9a0bf5fc-eae9-43c7-ae44-25d932e29986)

### 你期望看到什么？What did you expect to see?

正常的设置界面

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版已解决
