### ISSUE TITLE
[Bug]提示连接无回应，但是用其他的API客户端是可以正常使用的。

### ISSUE THREAD

**Issue by lovenoms** [openai-translator/openai-translator#1479]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

4.0

### Model name

gpt-3.5-turbo

### 系统/浏览器版本 System/Browser version

Windows 11

### 复现步骤 Reproduce step

选择输入完官方API密钥和cloudflare workers的转发地址后，使用中反馈：failed to call API: error sending request for url (https://rapid-cake-d046.lovenoms.workers.dev/v1/chat/completions): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)

### 你看到了什么错误？What errors do you see?

failed to call API: error sending request for url (https://rapid-cake-d046.lovenoms.workers.dev/v1/chat/completions): error trying to connect: tcp connect error: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 (os error 10060)

### 你期望看到什么？What did you expect to see?

翻译结果。

### 还有其他的内容吗？Anything else?

相同设置在chatbox中是可以正常使用的。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="537" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/21abe764-8400-4ac6-bca0-383e1b7c97d2">

关一下防火墙和代理软件，然后重启
