### ISSUE TITLE
[Bug] Windows下拖动窗口后立即消失

### ISSUE THREAD

**Issue by involvements** [openai-translator/openai-translator#1482]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.4.2

### Model name

gemini-pro

### 系统/浏览器版本 System/Browser version

Windows 11

### 复现步骤 Reproduce step

在Windows下，由于窗口不在适当的位置，在拖动翻译结果窗口后窗口立即消失。
关闭[失去焦点时自动隐藏窗口]后，bug消失

### 你看到了什么错误？What errors do you see?

![recording](https://github.com/openai-translator/openai-translator/assets/1711966/01b04674-0269-4ec2-aad1-b15bc1b0e4aa)

### 你期望看到什么？What did you expect to see?

随心所欲拖动？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
这是 Tauri 的 bug，暂时解决不了

**Comment by yetone** [comment]
已通过很 tricky 的方式绕过了这个 Tauri 的 bug，所以在最新版本中，此问题已修复。
