### ISSUE TITLE
[Bug] 无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll

### ISSUE THREAD

**Issue by StudyDayDayUpA** [openai-translator/openai-translator#1485]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.4.2

### Model name

None

### 系统/浏览器版本 System/Browser version

Windows 7旗舰版

### 复现步骤 Reproduce step

安装后打开报错：无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll

### 你看到了什么错误？What errors do you see?

无法定位程序输入点ProcessPrng于动态链接库bcryptprimitives.dll
![1](https://github.com/openai-translator/openai-translator/assets/133833977/e587e869-5a80-4556-839b-b0b545963334)

### 你期望看到什么？What did you expect to see?

希望软件能正常打开

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
你好，此软件不支持 windows 7
