### ISSUE TITLE
请教达到了使用限制怎么破

### ISSUE THREAD

**Issue by joeyzhou521** [openai-translator/openai-translator#15]
Rate limit reached for default-gpt-3.5-turbo in organization org-MnYDCjjkmogNTOZelkmrrb6G on requests per min. Limit: 20 / min. Current: 30 / min. Contact support@openai.com if you continue to have issues. Please add a payment method to your account to increase your rate limit. Visit https://platform.openai.com/account/billing to add a payment method.
感谢大佬，刚才尝试了几次之后提示了这个，只能付费才可以继续了么。谢谢

**Comment by devyujie** [comment]
过一分钟就好了

**Comment by joeyzhou521** [comment]
谢谢回答，绑了卡就没了😀
