### ISSUE TITLE
可否增加mac电脑英特尔芯片的软件程序呢？

### ISSUE THREAD

**Issue by 716ningjing** [openai-translator/openai-translator#1501]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

可否增加mac电脑英特尔芯片的软件程序呢？

### 描述 Motivation

可否增加mac电脑英特尔芯片的软件程序呢？

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by WhiteDG** [comment]
https://github.com/openai-translator/openai-translator/discussions/1490#discussioncomment-9271965

**Comment by 716ningjing** [comment]
> [第1490章 （评论）](https://github.com/openai-translator/openai-translator/discussions/1490#discussioncomment-9271965)

十分感谢，我去下载了旧版本能哟用了
