### ISSUE TITLE
[Bug]服务提供程序MiniMax返回请求地址错误

### ISSUE THREAD

**Issue by bisslot** [openai-translator/openai-translator#1502]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.4.4

### Model name

MiniMax

### 系统/浏览器版本 System/Browser version

Windows 10 / Google Chrome 124.0.6367.119

### 复现步骤 Reproduce step

翻译时提示接口返回错误, 前一日还能正常使用

### 你看到了什么错误？What errors do you see?

failed to call API: error sending request for url (https://api.minimax.chat/v1/text/chatcompletion_pro?GroupId=xxxxxxxxxxxxx): error trying to connect: unexpected EOF during handshake

### 你期望看到什么？What did you expect to see?

希望能够修复MiniMax接口调用的问题

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
我这边没复现，请关闭防火墙和代理软件，然后重启一下

**Comment by bisslot** [comment]
是的，这个错误误报了，MiniMax 的API 地址 api.minimax.com 被代理了，所以导致无法通信，这个问题解决了！
