### ISSUE TITLE
是否会考虑支持cohere command R+

### ISSUE THREAD

**Issue by jtc1246** [openai-translator/openai-translator#1508]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

支持cohere command R+

### 描述 Motivation

性能好于gpt 3.5，速度比gpt4快，并且trial可以免费使用，目前正常使用并未发现rate和使用量限制。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jtc1246** [comment]
可以使用https://github.com/missuo/cohere2openai ，这样配置：
<img width="60%" alt="Screenshot 2024-05-04 at 08 00 18" src="https://github.com/openai-translator/openai-translator/assets/43341500/b185024c-ced4-4731-a2e2-14764ebd75a3">

**Comment by yetone** [comment]
最新版已原生支持 Cohere command R+

<img width="652" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/75cec392-1e08-4775-88c1-0af6429016af">

<img width="652" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/ff454096-d1c0-444b-be60-2dcd959651fc">
