### ISSUE TITLE
Provide .msi package in releases

### ISSUE THREAD

**Issue by johnd0e** [openai-translator/openai-translator#1519]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

.msi is useful e.g. for automation

### 描述 Motivation

.msi package was included in Releases up to v0.3.51, that it disappeared without explanation.
I wonder if it is bug or intended action.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
This is the reason why .msi is no longer provided:

Firstly, I wrote "all" in the bundle.targets of my tauri.conf.json, which led it to build both wix installer (.msi) and nsis installer (-setup.exe). However, the default configuration of updaterJsonPreferNsis in Tauri's official github action tauri-apps/tauri-action@v0 is false (resulting in the generated updater json containing msi package), so users who installed with -setup.exe can never update successfully. Plus, recently Tauri's packaged .msi always lacks files and gets falsely reported by Windows Defender. But there are no issues with -setup.exe, so I completely abandoned .msi and only packaged -setup.exe.

Pitfalls:
1. I packaged both .msi and -setup.exe, which can easily be mixed up.
2. The default in Tauri's official action is .msi for updater json but they mentioned changing it to default -setup.exe for Tauri 2.0 in comments.
3. Recently packed .msis from Tauri lack files and get falsely reported.


<img width="573" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/8a00a775-d3ed-4c95-9728-f6bd95c93838">

https://x.com/yetone/status/1782486009680417097
