### ISSUE TITLE
可否增加截屏转文字的功能？

### ISSUE THREAD

**Issue by hoody4032** [openai-translator/openai-translator#1520]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

增加截屏转文字的功能

### 描述 Motivation

DeepL有一个截屏转文字的功能。用户选中这个功能就可以开始截屏。然后自动转成文字翻译。openai translator好像需要把图片上传OCR，有一点麻烦。

谢谢。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="199" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/08ab2991-26da-4987-91b7-0b0221209259">

OCR 功能一直都有的
