### ISSUE TITLE
[Bug] open-ai-translator_0.4.9_amd64.AppImage window transparent issue under Linux

### ISSUE THREAD

**Issue by ttys3** [openai-translator/openai-translator#1522]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.4.9

### Model name

gpt4

### 系统/浏览器版本 System/Browser version

Fedora Linux 40 (Workstation Edition)

### 复现步骤 Reproduce step

gpu:  nvidia kernel open driver 
Driver Version: 550.78         CUDA Version: 12.4
de:  GNOME 46  Wayland

download ./open-ai-translator_0.4.9_amd64.AppImage from releasse page https://github.com/openai-translator/openai-translator/releases/tag/v0.4.9

run it under terminal

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/41882455/4efa6f44-eefb-4373-9367-6604a2ecbdec)

❯ ./open-ai-translator_0.4.9_amd64.AppImage               
libEGL warning: egl: failed to create dri2 screen
DRM kernel driver 'nvidia-drm' in use. NVK requires nouveau.

the app started but the window is transparent.

### 你期望看到什么？What did you expect to see?

the windows shows correctly

### 还有其他的内容吗？Anything else?

no

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
‌‌‌‌Is 0.4.8 normal?

**Comment by ttys3** [comment]
> ‌‌‌‌Is 0.4.8 normal?

no

currently the latest working version is v0.3.40

```
 open-ai-translator_0.3.40_amd64.AppImage
 open-ai-translator_0.3.41_amd64.AppImage
 open-ai-translator_0.3.42_amd64.AppImage
 open-ai-translator_0.3.45_amd64.AppImage
 open-ai-translator_0.3.48_amd64.AppImage
 open-ai-translator_0.3.49_amd64.AppImage
 open-ai-translator_0.3.52_amd64.AppImage
 open-ai-translator_0.4.0_amd64.AppImage
 open-ai-translator_0.4.8_amd64.AppImage
 open-ai-translator_0.4.9_amd64.AppImage
```

**Comment by ttys3** [comment]
tried clean up below dirs, not work still:

```
~/.local/share/open-ai-translator

~/.config/xyz.yetone.apps.openai-translator

~/.cache/open-ai-translator
```

**Comment by ttys3** [comment]
just tested open-ai-translator_0.4.20_amd64.AppImage
now it works
