### ISSUE TITLE
支持DeepSeekv2

### ISSUE THREAD

**Issue by XDUwt** [openai-translator/openai-translator#1525]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望能够支持幻方deepseek

### 描述 Motivation

https://chat.deepseek.com/

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="652" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/dd3ee1ff-21e7-4000-b737-cb59a7dc2d02">

可以通过自定义 OpenAI 的 API URL 和模型来实现

**Comment by yetone** [comment]
啊好吧，原来它的 API 不是 OpenAI compatible 的，我来实现一下
