### ISSUE TITLE
对Ollama模型加载keep_alive参数的支持，让模型可以在显存内保留更长时间

### ISSUE THREAD

**Issue by SuperMaxine** [openai-translator/openai-translator#1536]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

加入调用Ollama模型时对keep_alive参数的设置选项

### 描述 Motivation

ollama默认在5分钟未使用后会将模型从显存中卸载，导致下次调用时会经历较长时间的加载过程，较为影响使用体验。

### Solution

Ollama在api调用时提供了keep_alive选项可以设置保留时长或永不卸载选项，希望可以加入设置页面让用户自主设置。详见Ollama关于API调用的文档：
https://github.com/ollama/ollama/blob/c02db93243353855b983db2a1562a02b57e66db1/docs/faq.md#how-do-i-keep-a-model-loaded-in-memory-or-make-it-unload-immediately

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
好的٩(•̤̀ᵕ•̤́๑)ᵒᵏᵎᵎᵎᵎ

**Comment by yetone** [comment]
最新版已支持 嘻嘻

**Comment by SuperMaxine** [comment]
> 最新版已支持 嘻嘻

!!!!!!!

大佬好快！！！！

大佬nb！！！
