### ISSUE TITLE
mac: Hide icon in the menubar

### ISSUE THREAD

**Issue by xxchan** [openai-translator/openai-translator#1537]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

mac: Hide icon in the menubar

### 描述 Motivation

currently icon in the dock can be hidden, but icon in the menubar cannot.
<img width="110" alt="image" src="https://github.com/openai-translator/openai-translator/assets/37948597/01462c13-4878-4e84-a936-dce89eb0cb62">

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by xxchan** [comment]
🤡
<img width="629" alt="image" src="https://github.com/openai-translator/openai-translator/assets/37948597/42b519b5-168b-4534-a4cb-9c7e04b3f309">

**Comment by yetone** [comment]
😁
