### ISSUE TITLE
[Bug]Azure 无法获取 API 模型

### ISSUE THREAD

**Issue by kawnnor** [openai-translator/openai-translator#1556]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.4.16

### Model name

Azure OpenAI API

### 系统/浏览器版本 System/Browser version

Windows 11 专业版 23H2 22631.3593 / Microsoft Edge 版本 124.0.2478.97 (正式版本) (64 位)

### 复现步骤 Reproduce step

更新到 v0.4.16 版本之后，在设置页面报错：Cannot read properties of undefined (reading 'filter')

![屏幕截图 2024-05-16 112507](https://github.com/openai-translator/openai-translator/assets/15528208/a1bd7cdc-1d68-4e43-ab97-43baeeadf505)

### 你看到了什么错误？What errors do you see?

在 v0.4.16 版本中，提供商选择“Azure”，无法刷新获取 API 模型，错误提示：Cannot read properties of undefined (reading 'filter')

### 你期望看到什么？What did you expect to see?

正常获取 API 模型，并可以选择。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢，我来修复一下

**Comment by yetone** [comment]
最新版已修复
