### ISSUE TITLE
Support of openrouter API

### ISSUE THREAD

**Issue by anthonyhtang** [openai-translator/openai-translator#1557]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

Support of OpenRouter API in OpenAI-Translator

### 描述 Motivation

OpenRouter API is getting increasingly popular. It would be great if openai-translator could add the support of OpenRouter API. Many thanks.

### Solution

Adding support to OpenRouter API. 
the current version of openai-translator does not allow specifying model names in OpenAI-compatible mode.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
Always supports custom models

<img width="652" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/bdc28943-ffc0-4ff6-b893-a14be464c0f9">

**Comment by atmomomo** [comment]
Custom Model Name not showing (0.4.17) 😔


![image](https://github.com/openai-translator/openai-translator/assets/26316925/d26f385f-5445-4fca-9cb3-4b03d2c0a38f)

**Comment by nayihz** [comment]
I encountered the same problem. Does openai-translator will request openai.com to query the API Models? If so, I think it's not neccessary when I want to use openrouter.ai but not openai.com
