### ISSUE TITLE
[Bug] 自定义 API URL 获取不到 API 模型列表时无法选择 API 模型为自定义

### ISSUE THREAD

**Issue by LisonFan** [openai-translator/openai-translator#1601]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.4.20

### Model name

custom

### 系统/浏览器版本 System/Browser version

Windows 11

### 复现步骤 Reproduce step

使用 [chat2api](https://github.com/lanqian528/chat2api) 搭建的 API 获取不了 API 模型列表，也无法选择自定义，必须得用官方的 API 获取到模型列表才能选择自定义模型
<img width="520" alt="image" src="https://github.com/openai-translator/openai-translator/assets/9424775/c649ed1a-d444-4450-997d-9f8034459e3b">

### 你看到了什么错误？What errors do you see?

无法选择自定义模型

### 你期望看到什么？What did you expect to see?

在获取不到 API 模型列表时能选择自定义模型

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by crosspacific** [comment]
API 模型那里一直在转圈，获取不到模型列表。主界面不能翻译、润色。希望恢复到能选择模型的版本

**Comment by eMUQI** [comment]
Same issue here

**Comment by greatzh** [comment]
Same.

**Comment by yetone** [comment]
更新到最新版然后勾选这个选项：

<img width="581" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/2d6ba6b0-3c15-4c50-91c0-4928c618f77e">
