### ISSUE TITLE
[Bug] 浏览器扩展插件 选中文字不显示图标

### ISSUE THREAD

**Issue by Eventidus** [openai-translator/openai-translator#1649]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.4.21

### Model name

gpt-4o

### 系统/浏览器版本 System/Browser version

Chrome 129.0.6614.3（正式版本）dev 

### 复现步骤 Reproduce step

选择文字，不出现图标；
点击右键菜单中的图标，也不弹出翻译窗口。
但是点击右上方扩展插件栏中的图标可以正常使用。

### 你看到了什么错误？What errors do you see?

选择文字，不出现图标；
点击右键菜单中的图标，也不弹出翻译窗口。
但是点击右上方扩展插件栏中的图标可以正常使用。

### 你期望看到什么？What did you expect to see?

选中文字或者点击右键菜单中的图标后可以正常进行翻译。

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by chaosMoon9** [comment]
你是不是用edge的预览版，我也有这个问题，退回edge正式版后解决了

**Comment by xieccc** [comment]
chrome， edge 更新到新版 > v130.* 就会出现这个问题，需要处理 CSP

**Comment by chenweiyi** [comment]
> chrome， edge 更新到新版 > v130.* 就会出现这个问题，需要处理 CSP
要怎么处理呢？

**Comment by drinktea1a** [comment]
但是我把扩展重装了，edge更新到最新版，好像还是不能用

**Comment by chenweiyi** [comment]
代码有问题，我修复了，看上面的 pr, 等 yetone 合并发版
