### ISSUE TITLE
[Bug] 对 pdf.js 项目的本地支持受阻

### ISSUE THREAD

**Issue by szh-bash** [openai-translator/openai-translator#170]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

Chrome store 最新版 [显示 3.9 提交的]

### System version

win11-22h2 pro

### Browser version

Chrome 111 正式版

### Minimal reproduce step

https://mozilla.github.io/pdf.js/getting_started/#download 下载 stable 版本并解压，双击 /web/viewer.html，然后将任意 pdf 拖入此页面，尝试划词翻译。[此为本地模式]
此时浏览器 url 显示如下：
![image](https://user-images.githubusercontent.com/27895812/224260700-8f7822b0-dde4-4441-a9b8-ca73e8db779c.png)

### What did you expect to see?

触发划词翻译

### What did you see instead?

划词后没有 openai 图标，未触发划词翻译

### Anything else?
经测试，压缩包解压载入 chrome 的 v0.0.14/v0.0.15/v0.0.16 版本均支持最新版 pdf.js 本地和 [demo](https://mozilla.github.io/pdf.js/web/viewer.html)  页面的划词翻译。
chrome 商城中的版本支持 pdf.js 的 [demo](https://mozilla.github.io/pdf.js/web/viewer.html) 页面划词翻译，却无法在本地环境中触发划词翻译。

**猜测的原因**：可能 chrome 商店版本中 url 相关规则与最新版本有差异导致 file:///E:/pdfjs-3.4.120/web/viewer.html 这种 url 不再触发划词翻译？
载入 chrome 的方式应该不可能是原因吧？

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by woodypeckerwho** [comment]
[pdf.js 离线.zip](https://github.com/yetone/openai-translator/files/10940075/pdf.js.zip)

试试这个旧版，在0.16版测试通过，秒翻。

**Comment by szh-bash** [comment]
> [pdf.js 离线.zip](https://github.com/yetone/openai-translator/files/10940075/pdf.js.zip)
> 
> 试试这个旧版，在0.16版测试通过，秒翻。

我又试了试手动载入 0.14/0.15/0.16 版，均可在本地 pdf.js 里划词翻译.....chrome web store 里这版很神奇啊

**Comment by szh-bash** [comment]
@yetone 是 3.9 发布的 chrome web store 版本远早于 0.14 版的问题吗？

**Comment by szh-bash** [comment]
开新 issue #562
