### ISSUE TITLE
Sign the app for macOS

### ISSUE THREAD

**Issue by AFutureD** [openai-translator/openai-translator#213]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

I am trying to create a PR for `brew`.
With `brew`, we should be easier to install the app on macOS.

Here is the file that I write for `OpenAI Translator`.
See https://github.com/AFutureD/homebrew-cask/blob/master/Casks/openai-translator.rb

But I have faced a problem.
There is a error when I test the cask file which required by brew official docs. (see [ testing-and-auditing-the-cask](https://docs.brew.sh/Adding-Software-to-Homebrew#testing-and-auditing-the-cask))

The check command is:
```
> brew audit --new-cask openai-translator
```

And the result is:
```
Already downloaded: /Users/afuture/Library/Caches/Homebrew/downloads/681c402baacc9da82f515e4eb4df9fca7d03d59a36251cd6a546b89f0d1f1359--OpenAI.Translator_0.0.17_x64.dmg
audit for openai-translator: failed
 - Signature verification failed:
/private/tmp/d20230311-56783-1urmar3/OpenAI Translator.app: code object is not signed at all
In architecture: x86_64

macOS on ARM requires applications to be signed. Please contact the upstream developer to let them know they should sign their app.
 - GitHub repository too new (<30 days old)
Error: 2 problems in 1 cask detected
```
It is obvious that the app has not been signed.

I am sorry that I do not have such  experience for  App signing issues. So, I am try to find help from you.

### Solution

There is a document from `tauri` about how to sign for macOS app.
See https://tauri.app/v1/guides/distribution/sign-macos
It is also giving a example for Github action.
But It may need a Apple Certificate from a paid Apple Developer Account which should be yours.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by AFutureD** [comment]
https://github.com/AFutureD/homebrew-cask/commit/79d8e56781f74070613f74d45e00c203a1c19031

**Comment by yetone** [comment]
Thank you for the reminder, I will look into the relevant operations!

**Comment by AFutureD** [comment]
@yetone 

Hi, I propose a new method for brew installation.

By hosting a custom tap repository, It is possible for user to install app directly from brew.

Simply as:
> brew install afutured/openai-translator-tap/openai-translator

In this method, we can:
1. Install the app following the correct architecture.
2. No more `Troubleshooting`.

Again, It is important to sign the app, otherwise someone may maliciously distribute the app to cause losses to users.

And, If you think the repo is a great contribution, I am happy to transfer the ownership to you for better maintenance.

**Comment by AFutureD** [comment]
Close.

**Comment by AFutureD** [comment]
Close.
