### ISSUE TITLE
输入API Key后无法保存[Bug] 

### ISSUE THREAD

**Issue by 1915419156** [openai-translator/openai-translator#234]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

在Ubuntu20.04上安装open-ai-translator_0.0.19_amd64.deb后;
输入API Key后无法保存；

### System version

版本：0.0.19

### Browser version

没有使用

### Minimal reproduce step

Ubuntu20.04
![image](https://user-images.githubusercontent.com/66114894/224545301-9d276c47-b095-4119-ba17-3063b826afe1.png)

### What did you expect to see?

能够保存API Key

### What did you see instead?

无

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR!

**Comment by 1915419156** [comment]
不知道和安装内核有没有关系，使用5.15.0-58-generic可以保存Key
使用5.14.0-1058-oem不能保存Key

**Comment by heddxh** [comment]
Same here. Arch linux 程序版本0.0.37

**Comment by maltoze** [comment]
fixed by #734
