### ISSUE TITLE
这么好用的功能，不要只局限于划词呀

### ISSUE THREAD

**Issue by jaychoubaby** [openai-translator/openai-translator#241]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

chrome划词功能已经很好用了，但是有时候临时想查一个在粘贴板上的词语，却还要去打开https://translate.google.com才行，可以设定为点击插件图标弹出输入框进行填写然后翻译吗，这样就可以代替谷歌翻译了。

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by szh-bash** [comment]
直接空白地方 右键-Openai Translator 打开翻译界面

**Comment by jaychoubaby** [comment]
> 直接空白地方 右键-Openai Translator 打开翻译界面

我用的是chrome的插件版本

**Comment by szh-bash** [comment]
> > 直接空白地方 右键-Openai Translator 打开翻译界面
> 
> 我用的是chrome的插件版本

我也是啊 v0.0.19，解压后导入 chrome 的

**Comment by jaychoubaby** [comment]
> > > 直接空白地方 右键-Openai Translator 打开翻译界面
> > 
> > 
> > 我用的是chrome的插件版本
> 
> 我也是啊 ot v0.0.19，chrome 111, win11-22h2-pro, 解压后导入 chrome 的

导入安装确实可以了，非常感谢，我之前装的是插件商店版的

**Comment by szh-bash** [comment]
> > > > 直接空白地方 右键-Openai Translator 打开翻译界面
> > > 
> > > 
> > > 我用的是chrome的插件版本
> > 
> > 
> > 我也是啊 ot v0.0.19，chrome 111, win11-22h2-pro, 解压后导入 chrome 的
> 
> 导入安装确实可以了，非常感谢，我之前装的是插件商店版的

看来商店版又多了个 Bug，之前我也发现 #170 和导入安装有功能差异

**Comment by jaychoubaby** [comment]
> > > > > 直接空白地方 右键-Openai Translator 打开翻译界面
> > > > 
> > > > 
> > > > 我用的是chrome的插件版本
> > > 
> > > 
> > > 我也是啊 ot v0.0.19，chrome 111, win11-22h2-pro, 解压后导入 chrome 的
> > 
> > 
> > 导入安装确实可以了，非常感谢，我之前装的是插件商店版的
> 
> 看来商店版又多了个 Bug，之前我也发现 #170 和导入安装有功能差异

原来是bug，我还以为是商店版的有限制

**Comment by szh-bash** [comment]
> > > > > > 直接空白地方 右键-Openai Translator 打开翻译界面
> > > > > 
> > > > > 
> > > > > 我用的是chrome的插件版本
> > > > 
> > > > 
> > > > 我也是啊 ot v0.0.19，chrome 111, win11-22h2-pro, 解压后导入 chrome 的
> > > 
> > > 
> > > 导入安装确实可以了，非常感谢，我之前装的是插件商店版的
> > 
> > 
> > 看来商店版又多了个 Bug，之前我也发现 #170 和导入安装有功能差异
> 
> 原来是bug，我还以为是商店版的有限制

啊那也有可能是限制，我路人 2333
