### ISSUE TITLE
希望添加Proxy代理选项

### ISSUE THREAD

**Issue by zhimiyouwu33** [openai-translator/openai-translator#265]
### Search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Motivation

首先，感谢这位码农的分享。
快醒醒，星星要破万了，希望能添加代理选项，应对各种不利的网络环境！
反正迟早要添加此功能！

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by GrayXu** [comment]
跟随系统代理设置的

**Comment by hennesshuang** [comment]
强烈要求增加，方便大陆同胞使用

**Comment by AndersonGhost** [comment]
系统开了全局也无法正常使用

**Comment by djc80s** [comment]
非常希望支持socks

**Comment by parn1986** [comment]
+1

**Comment by danerlt** [comment]
+1

**Comment by AnLiangHui** [comment]
+1+1+1+

**Comment by kdwycz** [comment]
希望增加socks5代理配置

**Comment by Karonolandiis** [comment]
这个直接走了系统代理啊

**Comment by ycyy** [comment]
+100086

**Comment by ttyy33** [comment]
希望增加socks5代理配置

**Comment by nxyd** [comment]
+1

**Comment by zchflyer** [comment]
+1

**Comment by tinytub** [comment]
希望添加代理配置,公司办公网环境不太方便配置系统代理.

**Comment by sunuslee** [comment]
希望增加socks5代理配置

**Comment by cfbsks** [comment]
![image](https://user-images.githubusercontent.com/76492899/228146382-ed8c6d4e-bb2c-441e-96e8-9389bd4b662d.png)
类似jetbrain的应用级代理设置界面

**Comment by hyyin** [comment]
顶啊，没有应用级代理 太不方便了。谢谢各位大佬

**Comment by zgpnuaa** [comment]
+1

**Comment by cyb233** [comment]
socks+1

**Comment by yetone** [comment]
最新版 0.3.9 已支持设置代理
<img width="772" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/00d0c143-1ffd-463a-bbe5-dc5aab0aec2d">
