### ISSUE TITLE
为划词后显示的图标添加超时时间或让其可以移动

### ISSUE THREAD

**Issue by AnYiEE** [openai-translator/openai-translator#308]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

为划词后显示的图标添加超时时间或让其可以移动。

### 描述 Motivation

有的时候选择文本只是为了高亮某个单词或句子，用以对外演示/强调/截图，图标一直显示又不能自动隐藏或拖动不太方便。

建议为划词后显示的图标添加超时时间或让图标可以移动。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yelion** [comment]
怎么样设置快捷键，我划词之后那个轮子没有出来
