### ISSUE TITLE
建议增加直接调用浏览器token

### ISSUE THREAD

**Issue by kettly1260** [openai-translator/openai-translator#311]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

API调用是有限度，token更适合翻译

### 描述 Motivation

API调用是有限度的，网页翻译本身就要通过浏览器，完全可以直接调用浏览器token

### Solution

可以参考该脚本https://greasyfork.org/zh-CN/scripts/456131-chatgpt-tools-plus-cookie%E7%89%88。每次只需要登录一下就行了，也不会很麻烦

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by JDYG** [comment]
The same feature requirement with [this issue](https://github.com/yetone/openai-translator/issues/122#issue-1616706547). 
Hope the developer can consider this enhancement.

**Comment by haoxia1** [comment]
+1
