### ISSUE TITLE
在ui中显示当前版本号

### ISSUE THREAD

**Issue by devyujie** [openai-translator/openai-translator#355]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

能否在ui中显示当前版本号

### 描述 Motivation

![image](https://user-images.githubusercontent.com/48620527/225862342-cb70a21b-e85a-4d2c-b495-c9cc7cb86d7f.png)

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by maltoze** [comment]
#401
