### ISSUE TITLE
[Bug] Linux 0.0.28及0.0.29 运行后没有无窗口，无托盘图标。

### ISSUE THREAD

**Issue by songww** [openai-translator/openai-translator#383]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

0.0.29及0.0.29

### 系统/浏览器版本 System/Browser version

Debian sid with Gnome 43

### 复现步骤 Reproduce step

通过desktop和命令行启动均看不到窗口，但后台可以看到进程。

### 你看到了什么错误？What errors do you see?

没有错误。再次运行会得到 "app 已经运行，去托盘查看" 的通知消息，但托盘里并没有它的图标。

托盘插件是：Tray Icons Reloaded

### 你期望看到什么？What did you expect to see?

窗口正常弹出，在0.0.26虽然也没有托盘图标，但窗口可以正常展示。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yingmanwumen** [comment]
Debian testing 无法看到窗口，但是有图标（我使用了系统代理）。
