### ISSUE TITLE
[Bug] 开了全局代理，并且挂的是美国节点，然后收到openai的账号停用通知

### ISSUE THREAD

**Issue by ypwcharles** [openai-translator/openai-translator#413]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### OpenAI Translator version

v0.0.31

### 系统/浏览器版本 System/Browser version

Edge 111.0.1661.44

### 复现步骤 Reproduce step

在windows用clash开了全局代理，并且挂的是美国节点，两小时后账号被停用，收到openai的账号停用邮件
Hi there,

After a thorough investigation, we have determined that you or a member of your organization are using the OpenAI API in ways that violate our policies.

Due to this breach we are halting access to the API immediately for the organization Personal. Common reasons for breach include violations of our [usage policies]or accessing the API from an [unsupported location]You may also wish to review our [Terms of Use]

If you believe this is in error and would like to appeal, please contact us through our [help center]We will review appeals within one business day and will contact you if we reinstate access to the API.

Best,
The OpenAI team

### 你看到了什么错误？What errors do you see?

openai api被停用

### 你期望看到什么？What did you expect to see?

api正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by SkyDriveCN** [comment]
我的情况和你一样，在没有使用插件之前连续好几天都没事，用了插件之后不到一两小时账户就被停用了。

**Comment by ypwcharles** [comment]
> 可以断言，API被停用和这个程序没关系。这个程序也不能让被停用的API功

一方面希望可以在说明里面提示后续的同学使用上需要注意一下，另外是否有可能可以提供说明引导用户更好地代理流量，避免账号被ban，要说明的一点是我用同样的节点和同样的clash全局代理，在别的软件上使用api是正常的

**Comment by blakehan** [comment]
用了插件被封+1

**Comment by smark-d** [comment]
被封跟插件没关系，和你的代理服务器有关系，就算不用这个插件，用你的代理服务器访问OpenAI API，也会被封

**Comment by z7356995** [comment]
有没有一种可能， 就是刚选择一句句子 openai 开始翻译了， 然后马上点了句子中的单词， 相同意思的请求又发给openai了？ 给openai一种滥用的感觉。  是不是可以在插件中 自动翻译整句 在设置中有一个勾选的选择。 因为我的主要功能大部份是查句子中的某个单词在句子中的意思。 整句翻译在二次选择后也有。 前面那次不需要了。

**Comment by z7356995** [comment]
第一次划选后 翻译 和 第二次 选词 后翻译 间隔时间太段。 整句翻译二次

**Comment by OverflowCat** [comment]
请访问 https://chat.openai.com/cdn-cgi/trace 并查看你的 IP 信息。很多 IP 段实际上被分配给了香港，如果你的代理软件的 GeoIP 数据库老旧，则会显示成美国。

**Comment by gaboolic** [comment]
别这样搞，兄弟，开全局你ip乱飘，不封你封谁。还是搞个代理接口吧，至少这样调到openai的ip是稳定的。https://github.com/gaboolic/vercel-reverse-proxy
