### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Moriarty1024** [openai-translator/openai-translator#434]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.33

### 系统/浏览器版本 System/Browser version

Manjaro linux

### 复现步骤 Reproduce step

打开软件窗口什么也不显示，空白

### 你看到了什么错误？What errors do you see?

打开软件窗口什么也不显示，空白

### 你期望看到什么？What did you expect to see?

出现正常的界面

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢反馈，正在安装虚拟机复现这个问题，抱歉给你带来了不好的体验！
