### ISSUE TITLE
添加开机静默自启动

### ISSUE THREAD

**Issue by lb-fes** [openai-translator/openai-translator#452]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

添加开机静默自启动

### 描述 Motivation

Windows 桌面版，添加开机静默自启动功能

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Chen1Plus** [comment]
why don't just add a link to the startup folder

**Comment by Blushxbwang** [comment]
+1，最好软件里能设置个开机启动！

**Comment by lb-fes** [comment]
@Chen1Plus 

Unable to start silently

@Blushxbwang 

无法静默自启动

**Comment by tk103331** [comment]
I can implement this feature

**Comment by person2217** [comment]
现在开机能自启动，但win10系统下，开机还是会弹出窗口，不会自动隐藏。使软件后台静默运行
