### ISSUE TITLE
希望增加自定义prompt功能，现在的prompt很差

### ISSUE THREAD

**Issue by wqrz** [openai-translator/openai-translator#498]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望增加自定义prompt功能，现在的prompt很差

### 描述 Motivation

I have a frog in my throat.  
这句用官方的chatgpt网页和https://freegpt.one/这种gpt3.5-turbo API的形式都能正确翻译出：
我喉咙有点哑

用这个插件翻译出来的是： 我嗓子里有只青蛙。

我试验的prompt是： 你是翻译专家，用口语的、专业的、优雅的方式翻译成中文，不要有翻译腔：I have a frog in my throat.  

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hutuyishi** [comment]
希望可以做成类似 monica 这样， 可以自定义action， 每个action自定义 prompt

![image](https://user-images.githubusercontent.com/104620424/229022860-2601716c-2b71-4edf-9c41-1166a0ce2007.png)
 
参考网址 https://monica.im/  【这个monica无法自定义key，只能购买他们的付费服务】

**Comment by xxchan** [comment]
BTW, 改进 prompt 实现更好的翻译效果和自定义 prompt 应该算是两个不同的需求

**Comment by hutuyishi** [comment]
@xxchan   感觉应该不冲突， 如果插件支持自定义prompt， 然后插件提供几个默认的 prompt ，  那就牛逼了，  这样一来， 市场上没几个对手了

**Comment by yetone** [comment]
我思考一下

**Comment by LightlyFloat** [comment]
请问有无兴趣说明一下如何进行prompt方面的设置？即：如何设置“动作”“角色提示词”与命令提示词

**Comment by yetone** [comment]
已支持自定义动作
