### ISSUE TITLE
需要支持配置代理的功能

### ISSUE THREAD

**Issue by dashi6174** [openai-translator/openai-translator#527]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

在Mainland，需要代理才可以访问api.openai.com

### 描述 Motivation

在Mainland，需要代理才可以访问api.openai.com

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by wangpre** [comment]
最新版支持配置代理 https://api.openai-proxy.com

**Comment by wangpre** [comment]
最新版支持配置代理 https://www.openai-proxy.com

**Comment by yetone** [comment]
最新版 0.3.9 已支持设置代理
<img width="772" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/00d0c143-1ffd-463a-bbe5-dc5aab0aec2d">
