### ISSUE TITLE
建议增加一个配置控制选中文字后是否要出现 icon 点击触发翻译

### ISSUE THREAD

**Issue by imsobear** [openai-translator/openai-translator#541]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

增加一个配置控制选中文字后是否要出现 icon 点击触发翻译

### 描述 Motivation

对于阅读时喜欢不断选中文字的人来说，比较容易误触发翻译的功能，此时其实并没有翻译需求。

### Solution

增加一个配置，关闭掉之后选中文字就不会出现图标，仅通过快捷键唤起翻译。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by myandeg** [comment]
赞同，同样有此需求。图标现在已经能够关闭，希望可以添加自定义快捷键直接对选中内容进行翻译，就像deepL的浏览器插件那样。

**Comment by yetone** [comment]
一直有这个快捷键
