### ISSUE TITLE
若设置的 API URL 不是 openai.com，建议不要检查区域是否受支持

### ISSUE THREAD

**Issue by liamwang** [openai-translator/openai-translator#544]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

若设置的 API URL 不是 openai.com，建议不要检查区域是否受支持

### 描述 Motivation

对于通过代理服务和自定义域名实现不用翻墙也能调用 openai 接口的情况，建议不要检查区域是否受支持。

建议仅当设置的 API URL 是 api.openai.com 时才检查区域是否受支持并弹出警告。

每次打开软件看到这个警告，这对于有点强迫症的人来说，感觉是有点不友好哈。 

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [x] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hh0592821** [comment]
确实，感觉我用的代理软件针对 openAI 单独设置了代理条件，但是翻译器的 ip 检测走的还是默认线路，每次都会弹出警告

**Comment by hh0592821** [comment]
> > 确实，感觉我用的代理软件针对 openAI 单独设置了代理条件，但是翻译器的 ip 检测走的还是默认线路，每次都会弹出警告
> 
> 其实你把chat.openai.com加入到代理域名里就好了，作者是通过chat.openai.com的检测功能做的IP判断。我猜测你可能只是设置了api.openai.com。

代理规则其实是`DOMAIN-SUFFIX,openai.com` 已经覆盖了，所以应用检测 ip 应该用的是其他方法。

**Comment by suenley** [comment]
> > > 确实，感觉我用的代理软件针对 openAI 单独设置了代理条件，但是翻译器的 ip 检测走的还是默认线路，每次都会弹出警告
> > 
> > 
> > 其实你把chat.openai.com加入到代理域名里就好了，作者是通过chat.openai.com的检测功能做的IP判断。我猜测你可能只是设置了api.openai.com。
> 
> 代理规则其实是`DOMAIN-SUFFIX,openai.com` 已经覆盖了，所以应用检测 ip 应该用的是其他方法。

那我知道你的问题了，咱俩一样。我有一只美国vps是同样的问题，我根据它调用地址检测，ipv6报HK。

作者通过这个接口判断的位置，你试一下。
https://chat.openai.com/cdn-cgi/trace

**Comment by i207M** [comment]
尝试把话题拉回来。OP的意思是 API URL 不是 openai.com 不需要检查区域，因为非官方的 API URL 一般是在合法区域搭建的代理。
