### ISSUE TITLE
[Bug] v0.0.36 macOS 版如果不给权限就无法启动

### ISSUE THREAD

**Issue by OctaDevelop** [openai-translator/openai-translator#545]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.36_aarch64

### 系统/浏览器版本 System/Browser version

macOS 13.3 with Apple M1

### 复现步骤 Reproduce step

正常启动 App 即可复现。

### 你看到了什么错误？What errors do you see?

<img width="573" alt="CleanShot 2023-03-30 at 19 54 19@2x" src="https://user-images.githubusercontent.com/127048902/228828062-04b21669-aa7c-4ed5-8a42-6618510732f0.png">

点击拒绝后软件退出。

### 你期望看到什么？What did you expect to see?

软件正常启动或者至少在拒绝过后依然允许启动。

OpenAI Translator 并不一定需要这个权限才可以正常工作，所以应当允许用户跳过这个授权。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hengfeiyang** [comment]
Me too, Why it always need the system accessibility features?

**Comment by yetone** [comment]
https://github.com/openai-translator/openai-translator#troubleshooting

The last GIF will give you the answer.

**Comment by yetone** [comment]
此问题已过时
