### ISSUE TITLE
[Bug] 火狐插件一直提示“We were unable to check if your IP address...”

### ISSUE THREAD

**Issue by iKun4real** [openai-translator/openai-translator#552]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.10

### 系统/浏览器版本 System/Browser version

Firefox 111.0.1

### 复现步骤 Reproduce step

除了点击插件图标打开不会显示这个提示以外，划词或者快捷键打开都会显示。翻译功能正常使用。

### 你看到了什么错误？What errors do you see?

主界面上方每次打开都会显示”We were unable to check if your IP address is in a [supported region](https://platform.openai.com/docs/supported-countries) of OpenAI. Please check your Internet connection, and ensure that you are accessing the API in a supported region of OpenAI, or your account may get banned regardless of your GPT Plus subscription status or any remaining account balance.“

### 你期望看到什么？What did you expect to see?

此提示消失。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
最新版这个问题已修复，抱歉给您带来了不好的体验

**Comment by yetone** [comment]
最新版这个问题已修复，抱歉给您带来了不好的体验
