### ISSUE TITLE
[Bug] Can't translate in Firefox browser

### ISSUE THREAD

**Issue by 0xJins** [openai-translator/openai-translator#566]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.11

### 系统/浏览器版本 System/Browser version

Window11 and Firefox browser developer version 112.0b9 (64-bit)

### 复现步骤 Reproduce step

1. Just translate English to Chinese
2. Always stay in translating status...
![image](https://user-images.githubusercontent.com/12077697/229677557-be155e16-6151-4e34-9153-62d03e5c60d1.png)

### 你看到了什么错误？What errors do you see?

No

### 你期望看到什么？What did you expect to see?

Correct to translate

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by celerysoft** [comment]
Could you please share the network request information? This will help developers identify and resolve the issue.

**Comment by 0xJins** [comment]
> Could you please share the network request information? This will help developers identify and resolve the issue.

It appears that there was no network request made. However, I did find some errors in the Console which may be useful. Please see below.
![image](https://user-images.githubusercontent.com/12077697/230259580-c9ab5847-9ac2-4646-9e71-48ef49ca3725.png)

**Comment by Iamnvincible** [comment]
Similar to my problem on firefox.
![Screenshot 2023-05-14 220307](https://github.com/yetone/openai-translator/assets/5810474/b86a7399-56f2-4678-a34d-2c5a65a98d03)
It cannot work in the page, but it works in firefox taskbar on the top right region.

**Comment by gouwazi** [comment]
firefox 113.0.1
![image](https://github.com/openai-translator/openai-translator/assets/23072555/c4a767dc-43df-4a11-a2f9-c605921bb894)

**Comment by OverflowCat** [comment]
I investigated this issue today but failed to find the cause.

Firstly, this error is related to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Property_access_denied. It seems to be a CORS issue, but there's not much related information.
I tried changing the Manifest to V2, as Firefox's V3 does not support persistently running background scripts, but this error persists.
Looking at the user feedback, the previous versions did show line numbers in the console, but the current version doesn't display error line numbers, which might be due to Vite.
vite dev-browser-extension only has a Chrome option, so we need @yetone to add a Firefox one, as the minified code is hard to debug.

**Comment by OverflowCat** [comment]
> > Could you please share the network request information? This will help developers identify and resolve the issue.
> 
> It appears that there was no network request made. However, I did find some errors in the Console which may be useful. Please see below. ![image](https://user-images.githubusercontent.com/12077697/230259580-c9ab5847-9ac2-4646-9e71-48ef49ca3725.png)

@0xJins I cannot reproduce `TypeError: "then" is readonly`, but got `Permission denied to access property "then"`. Can you provide details on how to reproduce it? (How did you install the extension?)

**Comment by kakuxuqu** [comment]
I had the error in firefox.
![image](https://github.com/openai-translator/openai-translator/assets/69780961/23852233-205c-4116-934a-1b4de2cecb3e)
