### ISSUE TITLE
可否加一个代理服务器的设置选项，socks or http？

### ISSUE THREAD

**Issue by ilovebody** [openai-translator/openai-translator#583]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

可否加一个代理服务器的设置选项，socks or http？

### 描述 Motivation

可否加一个代理服务器的设置选项，socks or http？

### Solution

可否加一个代理服务器的设置选项，socks or http？

### 还有其他内容吗？Anything else?

可否加一个代理服务器的设置选项，socks or http？

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaboolic** [comment]
可以修改url 吧。你搞一个代理接口的url，我就这么搞的，很稳定。https://github.com/gaboolic/vercel-reverse-proxy

**Comment by chengzheng777** [comment]
我这就是后端有个转的接口（有服务器能访问）
设置里面修改 API URL 为自家服务地址，API URL 路径修改为ngix反响代理的拦截

**Comment by zgpnuaa** [comment]
+1

**Comment by kk565** [comment]
+1 代理是基本需求
need proxy function

**Comment by hx3333** [comment]
确实需要搞个代理

**Comment by yetone** [comment]
最新版 0.3.9 已支持设置代理
<img width="772" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/00d0c143-1ffd-463a-bbe5-dc5aab0aec2d">
