### ISSUE TITLE
[Bug] 使用自己的http代理服务器, 在https网页下使用translator报错"Mixed Content"

### ISSUE THREAD

**Issue by hnczlsr** [openai-translator/openai-translator#587]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

Chrome extension v0.1.12

### 系统/浏览器版本 System/Browser version

Chrome 111.0.5563.110

### 复现步骤 Reproduce step

在[https.](https://www.google.com/search?q=hello)页面里划词翻译即可复现

### 你看到了什么错误？What errors do you see?

Type Error: Failed to fetch

### 你期望看到什么？What did you expect to see?

正常翻译

### 还有其他的内容吗？Anything else?

F12查看Console信息, 报错如下
Mixed Content: The page at 'https://www.google.com/search?q=hello' was loaded over HTTPS, but requested an insecure resource 'http://xxxx/v1/chat/completions'. This request has been blocked; the content must be served over HTTPS.

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hnczlsr** [comment]
看提交是直接把定义的http的apiURL替换成了https, 如果自己写的代理只支持http是不是就不行了?

**Comment by Dca3fu3** [comment]
我的解决办法是把自己的代理服务器地址升级成https就没问题了。

**Comment by hnczlsr** [comment]
同使用https解决~
