### ISSUE TITLE
能否支持Markdown显示

### ISSUE THREAD

**Issue by yulangz** [openai-translator/openai-translator#608]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望能支持markdown格式和代码高亮

### 描述 Motivation

![image](https://user-images.githubusercontent.com/53958801/231134270-5f755d45-0ae8-47bf-882b-945e1b3499b8.png)
希望能将上图中的Markdown格式的返回正确展示出来。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by imic07** [comment]
@yulangz 参考 https://github.com/yetone/openai-translator/issues/616  直接右击，检查，给div标签增加样式即可
