### ISSUE TITLE
[Bug] 生成的结果是以字符串展示的，没有格式。希望增加div格式化输出样式

### ISSUE THREAD

**Issue by imic07** [openai-translator/openai-translator#616]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

1.0.4

### 系统/浏览器版本 System/Browser version

latest edge

### 复现步骤 Reproduce step

如下图：生成的文本，样式有问题。直接是字符串，可读性不好。
![1681575672066](https://user-images.githubusercontent.com/16321067/232238006-e3578cfb-8d66-4b1e-a935-8dc7e98bbd1b.jpg)

### 你看到了什么错误？What errors do you see?

样式不对

### 你期望看到什么？What did you expect to see?

如下两个图片，两种修改方式，可以修复此问题。
![1681575836117](https://user-images.githubusercontent.com/16321067/232237991-935310d4-7297-45c0-95b0-244af43ca6cc.jpg)
![1681575751753](https://user-images.githubusercontent.com/16321067/232237997-03dbc700-1931-4304-9485-f2370edc081d.jpg)

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
首先这个不是本项目的软件，而是别人 fork 的一个版本。另外代码部分的 Markdown 输出已经在 #694 中解决。如果你对其他模式下的 Markdown 输出有建议的话，可以重新打开这个 issue。
