### ISSUE TITLE
[Bug] 用azure api翻译俄文出错

### ISSUE THREAD

**Issue by wrlm** [openai-translator/openai-translator#619]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.12

### 系统/浏览器版本 System/Browser version

Windows11/Edge版本 112.0.1722.39 (正式版本) (64 位)

### 复现步骤 Reproduce step

选中俄文点击按钮翻译
Одна из крупнейших прокремлевских распространительниц дезинформации и пропаганды, выдававшая себя в сети за русскую еврейку из Луганска, оказалась разведенной женщиной средних лет из Нью-Джерси и ветераном ВМС США. Ее разоблачили участники интернет-сообщества [«Североатлантическая организация Fella»](https://nafo-ofan.org/) (NAFO), которое борется с российской пропагандой.

У пропагандистки с ником Donbass Devushka (в разное время она также использовала псевдонимы Mila Medvedev, [@luganskforlife](https://twitter.com/LuganskforLife), CheburekiVibes, MeatballSubZero, YuGopnik, GhostofLugansk) есть свой Telegram-канал, Twitter и YouTube-канал, где она выкладывает свой подкаст. У нее около 135 тысяч подписчиков.

В Twitter Donbass Devushka публиковала свои отфильтрованные фотографии и писала, что ее зовут Мила.

### 你看到了什么错误？What errors do you see?

结果页显示：
![Dingtalk_20230417092212](https://user-images.githubusercontent.com/18413633/232356731-6c6474b5-0aba-4222-b53b-35bf12ba21a6.jpg)

### 你期望看到什么？What did you expect to see?

期望看到正确的翻译结果

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by tao12345666333** [comment]
![2023-04-19 21-56-27屏幕截图](https://user-images.githubusercontent.com/3264292/233097837-9e5d1b6e-a74e-4d59-beac-e6bc58bcda50.png)

This is because the content triggered Azure's content review policy. The issue has been resolved now.
