### ISSUE TITLE
feat: support Safari(iPad OS)

### ISSUE THREAD

**Issue by wey-gu** [openai-translator/openai-translator#626]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

feat: support Safari(iPad OS)

### 描述 Motivation

被 https://twitter.com/laike9m/status/1648254568269221888?s=20 打动

### Solution

Safari Extension 似乎是支持 Mobile 的！

https://alvarotrigo.com/blog/chrome-extensions-ipad/

### 还有其他内容吗？Anything else?

n/a

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Long-Ni** [comment]
希望支持，ipadOS也是非常重要的生产力工具呀。
搜了一圈没有发现任何一款AI翻译支持ipadOS

**Comment by shwangdev** [comment]
any updates for this thread?
