### ISSUE TITLE
建议添加自定义promoter

### ISSUE THREAD

**Issue by todaroroad** [openai-translator/openai-translator#645]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

建议添加自定义promoter

### 描述 Motivation

建议添加自定义promoter

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by luckywzy** [comment]
yes , I also need this feature

**Comment by Passluo** [comment]
+1

**Comment by maltoze** [comment]
already supported
