### ISSUE TITLE
增加古文、近代白话、现代白话之间的自由翻译

### ISSUE THREAD

**Issue by YANGXUWILL** [openai-translator/openai-translator#658]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

中文有古文、近代白话和现代白话互相翻译的需要

### 描述 Motivation

我们是中文系研究语言、文学的，有历史上各种语言变体之间自由翻译的需要。

### Solution

翻译语言选项已有简体中文、繁体文（简体、繁体都是字的问题，不是语言的问题），而在语言上需要区分文言文/古文、近代白话（如红楼梦、水浒传之类的）、现代白话/现代汉语，这三者之间存在互相翻译的问题。在ChatGPT上尝试过，它完全可以做到这一点，而且做得非常好。

### 还有其他内容吗？Anything else?

无

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
可以给出一些例句和期待的结果吗？我用于测试

**Comment by YANGXUWILL** [comment]
您好，下面给一些例子：




大致的定义
 
文言文：如《二十四史》《聊斋志异》
 
近代白话：如中国四大名著（其中《三国演义》更偏文言，可排除）
 
现代白话：即我们接触的书面的现代汉语
 
人们目前主要需求应该是：文言文翻译成现代汉语；近代白话文翻译成现代汉语；繁简转化（这是文字的问题，应该保证内容一点不变，只是繁简转化）。我看到语言列表里还有粤语方言，我不知道这种涉及方言的转换需求大不大。
 
&nbsp;
 
&nbsp;
 
以《红楼梦》的一段为例：
 
&nbsp;
 
原文（近代白话）：
 
&nbsp;
 
当下，奶娘来请问黛玉之房舍。贾母说：“今将宝玉挪出来，同我在套间暖阁儿里，把你林姑娘暂安置碧纱橱里。等过了残冬，春天再与他们收拾房屋，另作一番安置罢。”宝玉道：“好祖宗，我就在碧纱橱外的床上很妥当，何必又出来闹的老祖宗不得安静。”贾母想了一想说：“也罢了。”每人一个奶娘并一个丫头照管，余者在外间上夜听唤。一面早有熙凤命人送了一顶藕合色花帐，并几件锦被缎褥之类。
 
&nbsp;
 
这是ChatGPT翻译的现代白话文或现代汉语
 
&nbsp;
 
目前，奶娘来询问黛玉的住处。贾母说：“现在将宝玉搬到我的套间暖阁里，让林姑娘暂时住在碧纱橱里。等过了残冬，春天再重新安排他们的房屋。” 宝玉说：“好祖宗，我可以睡在碧纱橱外面的床上很舒适，不必出去打扰老祖宗休息。” 贾母想了一会儿后说：“也行。”每个人都有一个奶娘和一个丫头照顾，在外面听从召唤。同时，熙凤早已命人送来一顶莲花色帷幔和几件锦被缎褥等物品。
 
&nbsp;
 
这是ChatGPT翻译的文言文（虽然效果不是很好）
 
&nbsp;
 
於是，奶娘前来问询黛玉之居所。贾母曰：“今将宝玉挪置套间暖阁儿内，汝等林姑娘则先在碧纱橱中寄宿。残冬岁末，俟春日再与众人整修房宅，行新安置。”宝玉言：“祖宗，吾寝具已在碧纱橱旁，已十分合宜，何需再行搅扰，令老祖宗不能安枕呢？”贾母思虑片刻，曰：“亦可矣。”每人分一名乳母及一名丫鬟看护，其余则于外间值夜听唤。与此同时，熙凤已命人送来一幅藕合色花帐和数件锦被缎褥之物。
 
&nbsp;
 
&nbsp;
 
再以《聊斋志异》的《聂小倩》为例：
 
&nbsp;
 
原文（文言文）：
 
&nbsp;
 
宁采臣，浙人，性慷爽，廉隅自重。每对人言：“生平无二色。”适赴金华，至北郭，解装兰若。寺中殿塔壮丽，然蓬蒿没人，似绝行踪。东西僧舍，双扉虚掩，惟南一小舍，扃键如新。又顾殿东隅，修竹拱把，阶下有巨池，野藕已花。意甚乐其幽杳。会学使案临，城舍价昂，思便留止，遂散步以待僧归。日暮有士人来启南扉，宁趋为礼，且告以意。士人曰：“此间无房主，仆亦侨居。能甘荒落，旦暮惠教，幸甚！”宁喜，藉藁代床，支板作几，为久客计。是夜月明高洁，清光似水，二人促膝殿廊，各展姓字。士人自言燕姓，字赤霞。宁疑为赴试者，而听其音声，殊不类浙。诘之，自言秦人，语甚朴诚。既而相对词竭，遂拱别归寝。
 
&nbsp;
 
Chatgpt翻译的近代白话（效果不是很好）
 
&nbsp;
 
宁采臣，是浙江人，性格豁达，廉洁自守。常对人说：“我一生没有丝毫偏见。”他来到金华，到了北郭地区，换下了行装。在庙中，殿塔宏伟壮观，但是杂草丛生，好像没有人来过一样，看上去十分荒凉。东西两边的僧舍，门紧闭，只有南边一间小屋，门锁像刚刚换新一样。他看到殿的东侧，有修竹拱把，阶下有一片巨大的池塘，野藕已经开花。他十分喜欢这里的清幽之感。就在这时，有一位读书人来到南门，宁赶紧走上前去拜见，并询问其意图。读书人说：“这里没有房主，我也只是个外来者。既然能忍受荒凉，白天晚上慷慨相教，真是太好了！”宁感到很高兴，用稻草代替床，用板凳作桌，想当久客。这个晚上月亮明亮高悬，清澈的月光像流水一样。两人便坐在殿廊上，互相介绍自己的姓名。读书人自称燕姓，字赤霞。宁一度怀疑他是来参加科举考试的，但是听他的口音，不像是浙江人。宁询问他的家乡，他却说自己是秦人，说话很朴实真诚。后来，两人说话说累了，便告别归睡。
 
&nbsp;
 
Chatgpt翻译的现代白话
 
&nbsp;
 
宁采臣是浙江人，性格豁达而正直自律。他常说自己“一生清白无双”。一次他去了金华，到了北郭，换下行装，穿上僧袍。寺庙中的殿宇和塔楼壮丽美丽，但是荒草丛生，似乎没有人烟，显得十分荒凉。他看到东西两边的僧房，门窗虚掩，只有南边的一座小屋门窗紧闭，好像是新建的。他又看到殿的东侧有一片修竹拱护，阶下有一口巨池，野藕已经开花，觉得这里十分幽静。这时一名学使过来了，城中的客栈价格昂贵，宁采臣决定留在这里等待僧人归来。日暮时分，有一位士人来到南门启门请求进入，宁采臣迎上去并告知了自己的情况。士人说：“这里没有房主，我也是借住的。能忍受寂寞的荒凉，早晚相互教化，真是太好了！”宁采臣很高兴，就用草垫当床，搭了几块板子做桌子，想在这里多待一段时间。晚上的月亮明亮高悬，光线清澈如水，他和士人并肩坐在殿廊上，互相道出姓名。士人自称姓燕，字赤霞。宁采臣怀疑他是来应试的考生，但听他说话的语音并不像是浙江人的口音，后来才知道他是秦人，说话朴实真诚。他们相互交谈，直到言尽意穷，最后告别回去休息。




杨旭 Yang Xu
武汉大学文学院
湖北省武汉市武昌区八一路299号（430072）
主页：http://jszy.whu.edu.cn/yanghsu
新作：《经验事件及其构式类型学研究概览》（2023）、《基于认知图景理论的身体行为动词及其句式研究》（2020）、《词类与句式》（2022）



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yetone/openai-translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 晚上6:35
***@***.***&gt;;
抄送:&nbsp;"Yang ***@***.******@***.***&gt;;
主题:&nbsp;Re: [yetone/openai-translator] 增加古文、近代白话、现代白话之间的自由翻译 (Issue #658)





 
可以给出一些例句和期待的结果吗？我用于测试
