### ISSUE TITLE
能否添加字符数显示

### ISSUE THREAD

**Issue by 0xFFFF-maker** [openai-translator/openai-translator#682]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望能支持当前字符数和最大字符数显示

### 描述 Motivation

<img width="606" alt="3" src="https://user-images.githubusercontent.com/90913009/236849654-cf170d09-2467-43c7-b3ea-b5c35992ad5d.png">
希望能在输入框中加入当前字符数显示和最大字符数显示

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
OpenAI 采用的是 tiktoken，并且每个模型的编码方式都不一样。计算 token 数量需要打包一个有点大的 token 数据。实时的剩余字符数量显示可能不现实，因为需要编码再解码才能获取到 token 数量。
