### ISSUE TITLE
增加一个固定窗口的功能

### ISSUE THREAD

**Issue by KiligFei** [openai-translator/openai-translator#692]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

固定弹窗

### 描述 Motivation

选中了文本翻译后的弹窗，如果我点击页面别的地方，弹窗被关闭，希望增加一个固定弹窗的选项，让弹窗在最顶层

### 还有其他内容吗？Anything else?

我知道这是一个很冒昧的需求，希望后续可以考虑支持在选择翻译服务添加谷歌翻译，open ai 这边因为一些封号或者 key 的原因，添加一个谷歌做备用，我觉得是一个很好的点，谢谢 

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by KiligFei** [comment]
谷歌插件

**Comment by Himself65** [comment]
Thanks for feedback, I will work on this

**Comment by Labjoker** [comment]
客户端：希望在置顶翻译窗口时，该窗口可以固定在屏幕的某个位置。而不是翻译下一词条时候，窗口跳转到另一个位置，这样会遮挡我要阅读的内容

**Comment by maltoze** [comment]
how aboutt this?
![Frame 3](https://github.com/openai-translator/openai-translator/assets/18044730/4e3ba93d-f95a-49db-ba8e-1f25f57db068)

**Comment by KiligFei** [comment]
yes
