### ISSUE TITLE
[Feature] Add a function for encoding and decoding in base64 format

### ISSUE THREAD

**Issue by FDUZS** [openai-translator/openai-translator#695]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

If the input is encoded in base64, decode it. If the input is a URL starting with http(s), encode it.

### 描述 Motivation

"Select, click, done. It's a lifesaver!"

### Solution

Add this to the prompt

### 还有其他内容吗？Anything else?

no

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by FDUZS** [comment]
Or enable users to create their own prompts, similar to what was suggested in issue #688.

**Comment by OverflowCat** [comment]
GPT cannot decode a random base64 text if it does not appear in its training data. Also, I don't think this is a function that has something to do with an AI-oriented _translator_. Can you provide a use case?

![image](https://github.com/openai-translator/openai-translator/assets/20166026/211924ef-cc95-4db2-aa81-a5d50ffccbdc)

Text encoded in the image is `"Or enable users to create their own prompts, similar to what was suggested in issue #688."`

**Comment by FDUZS** [comment]
close #753
