### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by 1915419156** [openai-translator/openai-translator#696]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.44

### 系统/浏览器版本 System/Browser version

Ubuntu20.04_5.14.0-1051-oem

### 复现步骤 Reproduce step

安装后无法打开

### 你看到了什么错误？What errors do you see?

open-ai-translator: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory

### 你期望看到什么？What did you expect to see?

能正常打开使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jsbyysheng** [comment]
似乎是openssl版本的原因，我在命令行里打开之后，得到
```
open-ai-translator: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```
然后我试着升级了一下openssl3，发现还需要依赖`GLIBC_2.32`
```
open-ai-translator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by open-ai-translator)
open-ai-translator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by open-ai-translator)
open-ai-translator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by open-ai-translator)
```
Ubuntu20.04是`GLIBC_2.31`，核心库不敢升级了。。。。

**Comment by dbit-xia** [comment]
Linux Mint 20.3 Cinnamon   5.14.0-1024-oem  
Also have the same problem!
