### ISSUE TITLE
access err

### ISSUE THREAD

**Issue by fxzer** [openai-translator/openai-translator#72]
![image](https://user-images.githubusercontent.com/68853957/223608892-4aab618e-fcaa-4423-98a3-0a179454a96b.png)

**Comment by yetone** [comment]
你的 IP 被 OpenAI 封了

**Comment by fxzer** [comment]
OK



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年03月08日 12:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [yetone/openai-translator] access err (Issue #72) |

你的 IP 被 OpenAI 封了
