### ISSUE TITLE
[Bug] Cannot save after input API keys (Ubuntu 22)

### ISSUE THREAD

**Issue by CSUHYD** [openai-translator/openai-translator#723]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.45

### 系统/浏览器版本 System/Browser version

Chrome 113.0.5672.126 (Official Build) (64-bit)

### 复现步骤 Reproduce step

None

### 你看到了什么错误？What errors do you see?

输入 api key 后尝试保存，遇到如下问题：
- 无法保存，保存按钮一直转圈
- 无法退出，只能kill进程

### 你期望看到什么？What did you expect to see?

Fix bugs

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Elite-zx** [comment]
same here:
![image](https://github.com/openai-translator/openai-translator/assets/110723979/973fa233-672f-4159-bd30-c80043b30632)

**Comment by maltoze** [comment]
![image](https://github.com/openai-translator/openai-translator/assets/18044730/065b5f38-cf02-4f24-a864-4e67ebac79d8)
