### ISSUE TITLE
chrome插件，使用API KEY，提示地区限制？

### ISSUE THREAD

**Issue by 404gods** [openai-translator/openai-translator#726]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.15

### 系统/浏览器版本 System/Browser version

Microsoft Edge 版本 113.0.1774.50 (正式版本) (64 位)

### 复现步骤 Reproduce step

使用API KEY接入，关闭科学上网环境，打开插件会提示：我们无法检查您的 IP 地址是否位于 OpenAI 的支持的地区，可能是由于您的网络环境无法访问 OpenAI。请检查您的网络连接，并确保您在支持的位置访问 API，否则即使订阅了 ChatGPT Plus 或账号内仍有余额，您的账户也会被 OpenAI 封禁。
打开科学上网环境就正常，但是API KEY接入应该不受IP所在地影响啊

### 你看到了什么错误？What errors do you see?

我们无法检查您的 IP 地址是否位于 OpenAI 的支持的地区，可能是由于您的网络环境无法访问 OpenAI。请检查您的网络连接，并确保您在支持的位置访问 API，否则即使订阅了 ChatGPT Plus 或账号内仍有余额，您的账户也会被 OpenAI 封禁。

### 你期望看到什么？What did you expect to see?

正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OverflowCat** [comment]
是的，在不支持的地区使用官方 API endpoint 会导致封号（API 余额和 Plus 无法退款），使用第三方 API 代理不会出现该提示；而在不支持的地区使用网页版只是会被 Cloudflare 挡住，一般不会封号。
