### ISSUE TITLE
[Bug]error:Permission denied to access property 

### ISSUE THREAD

**Issue by rookiesky** [openai-translator/openai-translator#735]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.15

### 系统/浏览器版本 System/Browser version

macOS 12.6.5 / Firefox 113.0.1 

### 复现步骤 Reproduce step

通过https://github.com/openai-translator/openai-translator/blob/main/README-CN.md 这个页面按照的浏览器插件。
配置OPENAI的key之后 划词翻译，提示错误，但是 点击插件弹出的输入框手动收入可以正常翻译。

### 你看到了什么错误？What errors do you see?

error:Permission denied to access property "then"
![error:Permission denied to access property "then"](https://imgfg.com/i/ahlFDS3CXB.png)

### 你期望看到什么？What did you expect to see?

正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by BruceChen7** [comment]
同样的open-translator 版本 在macos 13.01 上 firefox 113版本上，有同样的问题
