### ISSUE TITLE
[Bug] 划词翻译总是触发两次

### ISSUE THREAD

**Issue by wzdnzd** [openai-translator/openai-translator#738]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.47

### 系统/浏览器版本 System/Browser version

Chrome 113.0.0.0

### 复现步骤 Reproduce step

1. 浏览器插件打开 `审查弹出内容`
2. 划词，点击图标进行翻译

### 你看到了什么错误？What errors do you see?

一次翻译触发了两次请求，然后前一次请求会被取消。偶尔会出现 `The user aborted a request`。如下图所示
<img width="1253" alt="微信图片_20230524200616" src="https://github.com/openai-translator/openai-translator/assets/8565764/c3925011-9b5c-421a-8254-9dbbf5a90b35">

### 你期望看到什么？What did you expect to see?

每次划词翻译只触发一次 HTTP 请求

### 还有其他的内容吗？Anything else?

从Chrome应用商店安装的 `0.1.15` 版本不存在此问题，如下图所示
<img width="1255" alt="微信图片_20230524201221" src="https://github.com/openai-translator/openai-translator/assets/8565764/5ad51200-6ff1-4cc5-8f3f-38feb9baf5bc">

应该是最近的 commit 引进的bug，原因是 [这里的代码](https://github.com/openai-translator/openai-translator/blob/e4c4fbea02d7f4862daed1ea59470a8eb95f92ea/src/common/components/Translator.tsx#L874) 执行了两次，`translateText` 函数触发的？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by hidaris** [comment]
应用商店的0.1.16好像也没有这个问题，你可以试试
