### ISSUE TITLE
[Bug] thread 'main' panicked at 'uinput file can not be opened: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mouce-0.2.41/src/nix/uinput.rs:34:18 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

### ISSUE THREAD

**Issue by zxp19821005** [openai-translator/openai-translator#741]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.49

### 系统/浏览器版本 System/Browser version

EndeavourOS 6.1.29-1-lts Slimjet 39.0.3.0

### 复现步骤 Reproduce step

给予AppImage文件可执行权限后，运行直接报错

### 你看到了什么错误？What errors do you see?

```
$ /opt/appimages/open-ai-translator.AppImage 
thread 'main' panicked at 'uinput file can not be opened: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mouce-0.2.41/src/nix/uinput.rs:34:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### 你期望看到什么？What did you expect to see?

软件能够正常运行

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Xuanwo** [comment]
duplicated with https://github.com/openai-translator/openai-translator/issues/564
