### ISSUE TITLE
可否开发Safari插件？

### ISSUE THREAD

**Issue by Lettte** [openai-translator/openai-translator#747]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望开发Safari插件

### 描述 Motivation

平时很少使用Chrome，反而Mac的Safari是主力浏览器，翻译很好用，希望能有Safari的版本

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by maltoze** [comment]
目前可以通过如下方式在 Safari 中使用：
1. 安装 [Userscripts ](https://apps.apple.com/us/app/userscripts/id1463298887)
2. 在 Userscripts 中安装 https://github.com/openai-translator/openai-translator/releases/download/v0.0.49/openai-translator-0.0.49.user.js

请注意，此种方式不支持流式传输
