### ISSUE TITLE
v0.0.50版本Macos上无法粘贴key并且无法保存

### ISSUE THREAD

**Issue by atk7r** [openai-translator/openai-translator#767]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.50

### 系统/浏览器版本 System/Browser version

mac intel 12.1 

### 复现步骤 Reproduce step

无法粘贴和save

### 你看到了什么错误？What errors do you see?

无法粘贴key

### 你期望看到什么？What did you expect to see?

解决方案

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yurenji** [comment]
+1 same issue

**Comment by AriaLyy** [comment]
+1 无法输入密钥

**Comment by harichen** [comment]
+1 无法输入密钥
