### ISSUE TITLE
[Bug] 0.0.50版本无法在输入框输入(MacOS 11.7.8)

### ISSUE THREAD

**Issue by huouer** [openai-translator/openai-translator#768]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.50

### 系统/浏览器版本 System/Browser version

macOS 11.7.8

### 复现步骤 Reproduce step

升級後無法輸入

### 你看到了什么错误？What errors do you see?

無

### 你期望看到什么？What did you expect to see?

無

### 还有其他的内容吗？Anything else?

系統設置已經授權Accessibility

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by vonsy** [comment]
OpenAI Translator 0.0.52 (20230530.074815)
macOS Monterey 12.6 (21G115)
Accessibility已删除老版本程序后,重新运行 OpenAI Translator,重新赋权.

主界面输入框,可以输入一个字符,然后就无法输入了.
动作管理器,创建,名称/角色提示词等输入框也是只能输入第一个字符

**Comment by fujie-xiyou** [comment]
我0.0.52  系统版本和你一毛一样  也是无法输入

**Comment by yetone** [comment]
> Mac 13.2.1 (22D68) **主界面输入没有问题。** <img alt="image" width="633" src="https://user-images.githubusercontent.com/57564522/242033407-6d39bb41-6c94-48b6-8f36-b18bdc73c096.png">

对不起，我说错了，是 macOS 12-

**Comment by leoli-dev** [comment]
我升级到最新版本 0.0.53 后遇到同样问题

系统信息如下：
<img width="271" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1598600/ea533a7b-43b4-44c6-8610-7ddb509856fb">

还有另外一个问题，我尝试删掉新版本然后下载了 0.0.50，大概是这样的：
<img width="679" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1598600/7b596025-a0fa-47fa-b394-9619e175f5f5">

有什么手动删除database 的方法吗？我想 rollback

**Comment by huouer** [comment]
0.0.53 same issue. macOS 11.7.8

**Comment by junzhnag** [comment]
无法复制 API
![SCR-20230531-elb](https://github.com/openai-translator/openai-translator/assets/36911031/0f0554c8-fd37-449f-a29f-2ab4601b805d)

**Comment by yurenji** [comment]
+1 无法复制和输入api key 
version 0.053  on macbook m1

**Comment by IntelHeartPrime** [comment]
I also have the problem, can't input any word

**Comment by fujie-xiyou** [comment]
其实mac上用 作者的另一个 Bob插件 体验更好！

**Comment by yetone** [comment]
> rendering.

谢谢！可以只勾选 console 页面的 errors 截个图吗？

**Comment by sparketainer** [comment]
macOS 12.6.6也是这个问题

**Comment by yetone** [comment]
感谢反馈，最新版已修复此问题，大家升级一下吧！

**Comment by leoli-dev** [comment]
@yetone 谢谢🙏问题解决了，而且key没丢，太好了

PS：请问有什么为爱发电的途径？不好意思长时间白嫖😄
