### ISSUE TITLE
[Bug] 0.0.53版本在有的网页拉到页尾的段落进行翻译,会直接跳到网页的页首(Microsoft Edge 版本 113.0.1774.57 (正式版本) (64 位))

### ISSUE THREAD

**Issue by OneKenneth** [openai-translator/openai-translator#775]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.53

### 系统/浏览器版本 System/Browser version

Microsoft Edge 版本 113.0.1774.57 (正式版本) (64 位)

### 复现步骤 Reproduce step

开发者您好!
比如我在(https://docs.spring.io/spring-framework/docs/3.2.x/spring-framework-reference/html/)页面
浏览到页尾,选择其中段落进行翻译,会直接跳转到页首

### 你看到了什么错误？What errors do you see?

![复现](https://github.com/openai-translator/openai-translator/assets/75555787/c5faa1a3-88c2-4b15-bc58-1b82b72de9fd)

### 你期望看到什么？What did you expect to see?

正确的是在我选择的段落位置出现翻译框

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by OneKenneth** [comment]
开发者您好,另外发现对于一些非标准的网页(对于上述划词翻译会页面跳转),例如,一些资源文档的网页(https://raw.githubusercontent.com/git/git/master/Documentation/RelNotes/2.41.0.txt),
(https://docs.spring.io/spring-framework/docs/2.0.x/reference/),
进行划词翻译,翻译功能未生效,图标都未正常显示的.
![image](https://github.com/openai-translator/openai-translator/assets/75555787/13884d54-9b26-4f17-89d7-6991a7852bc0)

**Comment by JokerQyou** [comment]
最简单的，找 Hacker News（news.ycombinator.com ）上任意一个长过1屏的页面，选中页面第一屏以后的任意内容进行翻译，翻译窗口都会跑到第一屏内。这个问题至少从 `0.1.17` 就已经存在。
