### ISSUE TITLE
🔥🔥🔥 [Bug] 启用插件导致页面里包含的代码块渲染不正常

### ISSUE THREAD

**Issue by wzdnzd** [openai-translator/openai-translator#778]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.0.53

### 系统/浏览器版本 System/Browser version

Chrome 113.0.0.0

### 复现步骤 Reproduce step

+ 从Github Release 安装最新的浏览器插件
+ 打开一个包含代码块的网址，如 [StackOverflow](https://stackoverflow.com/questions/42479902/what-does-view-do-in-pytorch)

### 你看到了什么错误？What errors do you see?

禁用插件前所有代码块都被渲染成 [object Object]，禁用插件后渲染正常，如下图
<img width="517" alt="1685507184419(1)" src="https://github.com/openai-translator/openai-translator/assets/8565764/47144a6c-21f9-495d-bf1f-513ddb46006b">

### 你期望看到什么？What did you expect to see?

插件不影响页面渲染

### 还有其他的内容吗？Anything else?

题外话：个人在该项目基础上实现了一些小功能，主要包含以下三点：
+  **第三方 ChatGPT 接口的支持**，目前支持诸如 [chatgpt-web](https://github.com/Chanzhaoyu/chatgpt-web)、[ChatGPT-Next-Web](https://github.com/Yidadaa/ChatGPT-Next-Web)、[chatbot-ui](https://github.com/mckaywrigley/chatbot-ui)、[chatgpt-vercel](https://github.com/ourongxing/chatgpt-vercel) 以及 [AILink](https://github.com/vastsa/AILink) 等

+ **不同 provider 之间自由切换，配置之间不会相互覆盖**

+ 另外就是可以像现在的机场一样 **支持订阅 APIKey 及 接口**

不知作者是否感兴趣，如果感兴趣的话，我可以提交PR。
> 如果感兴趣，可以去我的 [项目地址](https://github.com/wzdnzd/openai-translator/tree/customize) 下载份源码编译试玩一下。由于适配的比较杂，加之最近刚开始学写前端，可能代码看上去个性化方面会比较强😅

> 另外还有个小建议，作者可以考虑一下：感觉 translate 这部分代码可以抽象成接口。组装请求的 `body` 及 `headers` 以及如何解析/处理数据交给不同的 provider（对应的实现类），主流程通过 `模板方法模式` 实现调用，甚至可以预留一些 `预处理` 及 `后处理` 扩展点。这样方便添加新的 provider 及 代码维护。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by HAndy2013** [comment]
同样发现了这个问题, 而且页面设置为英文的情况下, 代码块正常, 设置中文, 代码块就出问题

**Comment by rangujie** [comment]
同样的问题，关闭插件就正常了

**Comment by Kuri-su** [comment]
同样的问题, 被渲染的 HTML 代码
```html
<div class="highlight"><pre tabindex="0" style="color:#d0d0d0;background-color:#202020;-moz-tab-size:4;-o-tab-size:4;tab-size:4;" class="language-shell"><code class="language-shell" data-lang="shell">[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]</code></pre></div>
```

**Comment by zccat** [comment]
同样的问题，开着插件打开 https://quickref.cn/docs/javascript.html 也可复现

**Comment by wey-gu** [comment]
same here, was about to report to see this :)

**Comment by hh0592821** [comment]
同样的问题，开着插件打开 https://www.luogu.com.cn/discuss/174934 也可复现

**Comment by questrr** [comment]
同样的问题，开着插件打开 https://www.luogu.com.cn/problem/solution/P1001 也可复现

**Comment by HuiruDong** [comment]
插眼~ https://juejin.cn/post/6869736425953165319 也可复现

**Comment by swiftwind0405** [comment]
插眼~ https://expo.github.io/router/docs/features/routing/#layouts 也可复现
求大佬快解决。。非常影响使用

**Comment by frostming** [comment]
任意代码块，不限高亮引擎，均可复现。。。

**Comment by Diffumist** [comment]
Same here, and upon checking the Git commit history, it seems that this is where it affects markdown rendering of code blocks in the webpage.
https://github.com/openai-translator/openai-translator/blob/a8cc203c6c1e8be0aa0c423a57e9bc810dca1c74/src/common/components/Markdown.tsx#L11-L40

**Comment by unixzii** [comment]
Seems that the code blocks are modified by Prism automatically when mounted.

<img width="1324" alt="image" src="https://github.com/openai-translator/openai-translator/assets/3109144/4437525e-48ce-4c78-8c31-431413310bed">

**Comment by yetone** [comment]
如 PR https://github.com/openai-translator/openai-translator/pull/780 所示，原因是 react-markdown 用的 syntax highlight 的配置是全局的，只要是用 react-markdown/react-syntax-highlighter 的文档都会出现这个问题，这个锅我背得太冤了啊！！！

**Comment by yetone** [comment]
> 不知作者是否感兴趣，如果感兴趣的话，我可以提交PR。

十分感兴趣，辛苦提交一下 PR 吧！期待！！！

**Comment by wey-gu** [comment]
谢谢 🧎🏻🧎🏻🧎🏻

**Comment by luckymrwang** [comment]
我也遇到同样的问题，本想去twitter给yetone大佬回复报告这个问题的，想着这里可能有人提issue，果然是

**Comment by yetone** [comment]
临时把 OpenAI Translator 从 Chrome Store 下线了，防止用户更新到最新的有问题的版本

**Comment by wzdnzd** [comment]
> > 不知作者是否感兴趣，如果感兴趣的话，我可以提交PR。
> 
> 十分感兴趣，辛苦提交一下 PR 吧！期待！！！

已PR，见 #782 😁

**Comment by 623059008** [comment]
今天进StackOverflow突然发现代码全变成[object Object]了，排查了半天发现是这个插件的问题，换个浏览器就正常了。

**Comment by binarri** [comment]
一样的问题，研究了半个小时🤣

**Comment by IsQiao** [comment]
同样的问题 #805

**Comment by zeahoo** [comment]
解决了吗现在？

**Comment by enszhou** [comment]
比较好奇大家是怎么排查到是本插件导致这个问题的？我是二分法禁用插件，看会不会对页面有影响，才找到这个插件。我装的插件比较多，这样效率比较低。有没有什么直接的办法找到是哪个插件修改了页面的特定内容？

**Comment by frostming** [comment]
> 比较好奇大家是怎么排查到是本插件导致这个问题的？我是二分法禁用插件，看会不会对页面有影响，才找到这个插件。我装的插件比较多，这样效率比较低。有没有什么直接的办法找到是哪个插件修改了页面的特定内容？

关注作者的推特，他最近宣布了markdown渲染，和问题高度相关。

逃了逃了

**Comment by wsldl123292** [comment]
审核这么慢

**Comment by kaichii** [comment]
Same Issue

**Comment by OxfordStreet** [comment]
same issue on https://learnblockchain.cn/article/5873

**Comment by yetone** [comment]
大家好！OpenAI Translator 的 Chrome 插件再次归来！已经没有被 react-syntax-highlighter 偷家的 bug 了！

![image](https://github.com/openai-translator/openai-translator/assets/1206493/1059076f-1a25-409b-bf84-72fb781b4d79)

**Comment by gaboolic** [comment]
> 

开始以为是知乎有问题了。后来发现别的网站也有问题。然后浏览器插件全禁，问题解决，确认是插件的问题
开始以为是adguard有问题，禁了之后问题还在。然后一个一个试…… 才发现居然是openai-translator

**Comment by hansedong** [comment]
> 比较好奇大家是怎么排查到是本插件导致这个问题的？我是二分法禁用插件，看会不会对页面有影响，才找到这个插件。我装的插件比较多，这样效率比较低。有没有什么直接的办法找到是哪个插件修改了页面的特定内容？

感觉这个排查方式更好，可以参考一下：https://www.526net.com/n/opz1/

**Comment by yetone** [comment]
大家去 Chrome 插件市场更新到最新版本（1.20）即可！

**Comment by OverflowCat** [comment]
Pin this issue for a period of time, as I still see many users encounter this problem and don't know how to fix

**Comment by JasonGrass** [comment]
> > 比较好奇大家是怎么排查到是本插件导致这个问题的？我是二分法禁用插件，看会不会对页面有影响，才找到这个插件。我装的插件比较多，这样效率比较低。有没有什么直接的办法找到是哪个插件修改了页面的特定内容？
> 
> @enszhou 感觉这个排查方式更好，可以参考一下：https://www.526net.com/n/opz1/

瞄了一眼，这篇博客竟然是我自己写的…… 这些偷博客的网站真实很讨嫌啊  
原文地址：[一个有趣的问题调查，网页上的代码块全部变成 [object Object] - J.晒太阳的猫 - 博客园](https://www.cnblogs.com/jasongrass/p/17448415.html )
