### ISSUE TITLE
有没有考虑过开发移动端

### ISSUE THREAD

**Issue by 0xFFFF-maker** [openai-translator/openai-translator#779]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望在移动端上也能使用

### 描述 Motivation

平时使用电脑不在身边时，也会有翻译的需求，所以希望能开发移动端供手机版使用，感谢！

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by zizhanovo** [comment]
有大佬开发了，并且来源了，可以搜一下，能找到
