### ISSUE TITLE
[Bug] Firefox右鍵翻譯error

### ISSUE THREAD

**Issue by nathan60107** [openai-translator/openai-translator#781]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.16

### 系统/浏览器版本 System/Browser version

Firefox 113.0.2

### 复现步骤 Reproduce step

Firefox右鍵複製文字後按圖示翻譯文字，會出現
![](https://cdn.discordapp.com/attachments/884121446652211200/1113439452094812241/image.png)
![](https://cdn.discordapp.com/attachments/700331141311234100/1113441978525425737/image.png)
但是附加元件自身介面的翻譯則正常運作沒有問題
![](https://cdn.discordapp.com/attachments/700331141311234100/1113443213999607898/image.png)
使用的模式是ChatGPT (Web)免費模型
![](https://cdn.discordapp.com/attachments/700331141311234100/1113442853608243250/image.png)
另外不曉得為什麼這邊會有兩個Turbo，也許是bug

### 你看到了什么错误？What errors do you see?

如圖紅字

### 你期望看到什么？What did you expect to see?

期望不出現紅字錯誤，正確翻譯文字

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by DCjanus** [comment]
这个可能是 Firefox 插件权限的问题，需要在插件管理页面，配置允许插件访问所有网页，否则只能每次点击右上角插件图标进行临时授权。

<img width="687" alt="图片" src="https://github.com/openai-translator/openai-translator/assets/15802727/33ae5eaa-54af-4dd0-8e83-c112880329aa">

**Comment by nathan60107** [comment]
Bug fixed.
