### ISSUE TITLE
[BUG] Chrome extension does not pop up properly

### ISSUE THREAD

**Issue by tao12345666333** [openai-translator/openai-translator#786]
![2023-06-01 09-31-40屏幕截图](https://github.com/openai-translator/openai-translator/assets/3264292/a688c292-491c-4378-8903-56e61663d33c)
![2023-06-01 09-31-33屏幕截图](https://github.com/openai-translator/openai-translator/assets/3264292/2cb1139a-1574-45e5-af82-5a5752be4b89)

Reinstall didn't work either

_Originally posted by @tao12345666333 in https://github.com/openai-translator/openai-translator/issues/785#issuecomment-1571192759_
            

![2023-06-01 09-35-56屏幕截图](https://github.com/openai-translator/openai-translator/assets/3264292/4dd7747e-5adc-4fce-b2ca-32dd4128632d)

**Comment by chaunceyjiang** [comment]
+1
