### ISSUE TITLE
[Bug] 谷歌插件 当页面里有代码块时 代码块内容会显示为object object object object... 

### ISSUE THREAD

**Issue by sywyyhykkk** [openai-translator/openai-translator#789]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [x] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

最新版本

### 系统/浏览器版本 System/Browser version

chrome 113.0.5672.126

### 复现步骤 Reproduce step

插件启用的情况下 在任意有代码块的页面 代码块内容显示异常 大多数情况首次进入页面即显示异常 刷新页面以后会显示异常
禁用插件后 所有页面都正常

### 你看到了什么错误？What errors do you see?

页面markdown 代码块内容异常

### 你期望看到什么？What did you expect to see?

正常显示markdown 代码块

### 还有其他的内容吗？Anything else?

谷歌插件市场里被下架了？卸载了想重装 插件市场里找不到该插件了

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by shaonianche** [comment]
ref: https://github.com/openai-translator/openai-translator/issues/778
