### ISSUE TITLE
[Bug] 在chrome浏览器启用OpenAI Translator导致有些页面不能正常显示

### ISSUE THREAD

**Issue by nettm** [openai-translator/openai-translator#803]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.17

### 系统/浏览器版本 System/Browser version

Chrome 113.0.5672.127

### 复现步骤 Reproduce step

1、启用插件，打开类似 https://zhuanlan.zhihu.com/p/485403309 这样的网页，页面不能正常显示
2、停用插件，刷新页面，页面恢复正常显示

### 你看到了什么错误？What errors do you see?

内嵌的代码不能正常显示
![image](https://github.com/openai-translator/openai-translator/assets/3842718/832db117-0582-49ef-9edb-690d70765888)

### 你期望看到什么？What did you expect to see?

希望内嵌的代码能正常显示
![image](https://github.com/openai-translator/openai-translator/assets/3842718/7a19db90-1031-49fc-b40d-beef7288de02)

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by SGB555** [comment]
+1

**Comment by cikichen** [comment]
昨天开始出现的，我一个个试才发现是这个插件的问题

**Comment by lb-fes** [comment]
今天遇到了同样的问题

内联代码和代码块都显示为 `[object Object]`

控制台 warning：

```
Translator-80667a6b.js:77
Could not find "window.__TAURI_METADATA__". The "appWindow" value will reference the "main" window label.
Note that this is not an issue if running this frontend on a browser instead of a Tauri window.
```

**Comment by fanpei91** [comment]
昨天就出现这个问题了，我还在插件商店报告了这个问题。

**Comment by Jenkyn** [comment]
+1

**Comment by yetone** [comment]
与此 issue 重复：https://github.com/openai-translator/openai-translator/issues/778
