### ISSUE TITLE
[Bug] 把网页内容的代码块自动替换成了[object Object]

### ISSUE THREAD

**Issue by gaboolic** [openai-translator/openai-translator#809]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.17

### 系统/浏览器版本 System/Browser version

Microsoft Edge Version 113.0.1774.57 (Official build) (x86_64)

### 复现步骤 Reproduce step

打开https://zhuanlan.zhihu.com/p/60578464
即可看到代码块被替换
<img width="916" alt="image" src="https://github.com/openai-translator/openai-translator/assets/3831173/226cf10f-6698-4209-a828-a64505409b1b">

### 你看到了什么错误？What errors do you see?

内容被替换了

### 你期望看到什么？What did you expect to see?

正常的页面内容

### 还有其他的内容吗？Anything else?

没了

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by gaboolic** [comment]
问题可能是2023.6.1发现的，当时以为是网站出bug了
2023.6.2怀疑是其他的adguard插件引起的，但关闭后问题还在。最后把所有的插件都关闭只保留openai-translator，问题还在，所以确认是openai-translator的问题

**Comment by Hlongyu** [comment]
+1

**Comment by wangzhigang1999** [comment]
same error,  version 0.1.17

**Comment by wangzhigang1999** [comment]
看起来作者已经修复了这个问题，最新的版本是 0.1.20，不再有这个问题了；删除现在的版本然后重新安装即可。

It seems that the author has fixed this issue in the latest version 0.1.20; you can delete the current version and reinstall it again.

Translated by OpenAI Translator ❤

**Comment by gaboolic** [comment]
edge貌似不能自动更新，难搞啊。作者上架一下edge商店吧。
不过不能自动更新的话，这个bug为啥会凭空出现

**Comment by gaboolic** [comment]
same as [https://github.com/openai-translator/openai-translator/issues/778](issue778)

**Comment by gaboolic** [comment]
same [issue778](https://github.com/openai-translator/openai-translator/issues/778)

**Comment by yetone** [comment]
最新版已修复
