### ISSUE TITLE
增加付费模式

### ISSUE THREAD

**Issue by llccing** [openai-translator/openai-translator#81]
自己付费还是有门槛，和略微繁琐，不知道能不能增加个付费的模式，比如预付费10元，20元这种；可以比官网略微贵一点，只要能够开箱即用，付费方式可以使 PayPal，或者支付宝等

**Comment by woodypeckerwho** [comment]
收费的话，除非作者身在境外无牵无挂，否则面临国内法律风险。建议微信或者支付宝友情赞助，支持共享精神。

**Comment by devbian** [comment]
> 收费的话，除非作者身在境外无牵无挂，否则面临国内法律风险。建议微信或者支付宝友情赞助，支持共享精神。

为啥会有风险？ 因为chatgpt可能会瞎说？说一些敏感内容？

**Comment by woodypeckerwho** [comment]
> 

只是说理论上有法律风险，实践中案件非常少，而且主要针对有偿提供“翻墙”服务的行为。只要没有经营行为（即免费），即使AI瞎说也没什么实质的法律风险。执法、司法得有法律依据。

**Comment by zouhangwithsweet** [comment]
《计算机信息网络国际联网管理暂行规定》明确，计算机信息网络直接进行国际联网，必须使用邮电部国家公用电信网提供的国际出入口信道。任何单位和个人不得自行建立或者使用其他信道进行国际联网。如违反规定，由公安机关责令停止联网，给予警告，可以并处一万五千元以下的罚款。

**Comment by ernestyao** [comment]
除国内法律风险外，其实本身OpenAI目前的服务范围是仅对US的，在你注册付费账号的协议条款里、以及注册过程应该都有体会，所以这方面也存在风险。
