### ISSUE TITLE
win10导出csv生词本文件乱码  改成utf-8 等编码都不ok

### ISSUE THREAD

**Issue by fly1989** [openai-translator/openai-translator#826]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.55

### 系统/浏览器版本 System/Browser version

win10

### 复现步骤 Reproduce step

导出csv文件打开后乱码 

### 你看到了什么错误？What errors do you see?

no

### 你期望看到什么？What did you expect to see?

no

### 还有其他的内容吗？Anything else?

no

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Elegant-Spider** [comment]
遇到了同样的问题

**Comment by Elegant-Spider** [comment]
感谢[maltoze](https://github.com/maltoze)的回复，已解决，记事本里另存为 -> 编码: UTF-8 with BOM -> 保存

**Comment by whilelie** [comment]
tks
