### ISSUE TITLE
关于润色功能的建议

### ISSUE THREAD

**Issue by HAndy2013** [openai-translator/openai-translator#841]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望可以同步翻译和润色

### 描述 Motivation

首先还是感谢开发者, openai-translator已经是我使用频率最高的app之一了.
关于润色功能, 平时使用的时候, 经常会进行中译英的操作, 然后在翻译完成之后, 需要:
1. 在下方复制翻译好的英文
2. 粘贴到上方, 然后点击润色按钮
3. 复制润色之后的文本

带来的问题:
1. 操作有些复杂
2. 润色之后, 界面上就没有润色之前的文本了, 不方便对比. 

希望开发者可以加入 翻译+润色 的功能, 可以在翻译完成之后, 将翻译的文本进行润色, 简化操作逻辑.

再次感谢

### Solution
能否通过新增prompts的方式, 让openai直接输出译文和译文的润色结果?

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by InitialXKO** [comment]
点右上角三个点，动作管理器，创建。然后想怎么输出都行。

**Comment by HAndy2013** [comment]
> 点右上角三个点，动作管理器，创建。然后想怎么输出都行。

感谢, 都没注意到这个功能更新, 太实用了
