### ISSUE TITLE
[Feature] 更新模型列表, openai发布了新的模型

### ISSUE THREAD

**Issue by ChasLui** [openai-translator/openai-translator#842]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

更新模型列表

### 描述 Motivation

https://openai.com/blog/function-calling-and-other-api-updates

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by AreChen** [comment]
只要在i18n-94292ed0.js中把gpt-3.5-turbo-0301改成gpt-3.5-turbo-0613就可以使用了(只试了浏览器插件版)
真的泰快拉!

**Comment by hidaris** [comment]
> 只要在i18n-94292ed0.js中把gpt-3.5-turbo-0301改成gpt-3.5-turbo-0613就可以使用了(只试了浏览器插件版) 真的泰快拉!

0613速度比0301快很多吗？

**Comment by gold16** [comment]
速度快太多了，飞一般的速度😃😃😃

**Comment by InitialXKO** [comment]
Release是不是该更新一波

**Comment by wrlm** [comment]
> 只要在i18n-94292ed0.js中把gpt-3.5-turbo-0301改成gpt-3.5-turbo-0613就可以使用了(只试了浏览器插件版) 真的泰快拉!

修改了js之后提示扩展损坏，怎么解决

**Comment by InitialXKO** [comment]
最新的release还是没有新模型

**Comment by hshenmeow** [comment]
附议，希望增加新模型
