### ISSUE TITLE
[Bug] Windows版OpenAI Translator会导致Windows11的Snipping Tool截图功能不正常

### ISSUE THREAD

**Issue by limfoo** [openai-translator/openai-translator#853]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

OpenAI.Translator_0.0.55_x64_en-US.msi

### 系统/浏览器版本 System/Browser version

Windows11 22H2

### 复现步骤 Reproduce step

- 安装OpenAI.Translator_0.0.55_x64_en-US.msi
- Win+shift+s 截图
- Win+v查看剪切板，发现截图没有自动保存至剪贴板
- 退出OpenAI.Translator
-  Win+shift+s 截图
- Win+v查看剪切板，发现截图已正常保存

### 你看到了什么错误？What errors do you see?

Windows自带snipping tool截图后无法保存至剪切板

### 你期望看到什么？What did you expect to see?

请帮忙修复这个问题，谢谢。

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by XiaolongYang-HZAU** [comment]
我也遇到了类似的问题，我的问题是截图后看到剪切板混乱，本来应该在第一位的图片跑到第二位去了

**Comment by limfoo** [comment]
不要勾选"选中文字时显示图标"，需要选词翻译的话要额外安装Snipdo，再安装clip插件。
![image](https://github.com/openai-translator/openai-translator/assets/34062417/99bc8145-89cb-460b-9d11-579589a420fa)
