### ISSUE TITLE
Hope to join the support for gpt-3.5-turbo-0613.

### ISSUE THREAD

**Issue by suenley** [openai-translator/openai-translator#857]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

Hope to join the support for gpt-3.5-turbo-0613.

### 描述 Motivation

Hope to join the support for gpt-3.5-turbo-0613.

### Solution

Hope to join the support for gpt-3.5-turbo-0613 , or add an input box for custom models...

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by InitialXKO** [comment]
#843
