### ISSUE TITLE
自定义Prompt选项

### ISSUE THREAD

**Issue by ffreemt** [openai-translator/openai-translator#859]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

提供用户自定义Prompt选项

### 描述 Motivation

有时候用户希望自定义，例如翻译时，一个可能的Prompt为：
```
将以下内容翻译成中文，保留原意。（其他更多的描述等等……）提供3个版本：
```
主要是在微调翻译时，希望看看哪个版本更贴切一些。

### Solution

在 Settings 里添加一项“自定义Prompt”项。预设值为“否”。用户选“是”时，再自行填入自定义Prompt（可以预填入系统的Prompt供用户修改）

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by BlackStar1453** [comment]
这项功能已经有了吧，在Action Manager中，只是预设的几个propmt无法修改而已。

**Comment by ffreemt** [comment]
哦，那改成可以修改的话或许不那么费事

**Comment by ffreemt** [comment]
其实已经可以在Action Manager自定义Prompt了。感谢大佬
