### ISSUE TITLE
[Bug] {{无法工作提示}}

### ISSUE THREAD

**Issue by junchina027** [openai-translator/openai-translator#874]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

v0.1.0

### 系统/浏览器版本 System/Browser version

macos 14.0

### 复现步骤 Reproduce step

![image](https://github.com/openai-translator/openai-translator/assets/102725928/86752a3a-9f47-4906-b3ad-179bbe82748d)

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/102725928/0fc03bc7-f0bd-4ea3-8812-647248efdc64)

### 你期望看到什么？What did you expect to see?

jingkuaijiejue 

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by lsy2018** [comment]
Yes, I had the same issue. Is that because that the chatGPT is no longer free?

**Comment by junchina027** [comment]
> Yes, I had the same issue. Is that because that the chatGPT is no longer free?

I also know, but the 3.5 model is free.

**Comment by Gest0r** [comment]
I am having the same issue.

**Comment by spirit-jsb** [comment]
having the same issues.

**Comment by Daydream-liu** [comment]
having the same issues.
