### ISSUE TITLE
[Bug] 使用 azure openai 报错：resources not found

### ISSUE THREAD

**Issue by lordk911** [openai-translator/openai-translator#876]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.57

### 系统/浏览器版本 System/Browser version

macos

### 复现步骤 Reproduce step

![image](https://github.com/openai-translator/openai-translator/assets/19989300/3837b0e8-0779-4f3c-b283-2e0d40d8e5c5)

![image](https://github.com/openai-translator/openai-translator/assets/19989300/958b6240-d65a-49c5-bb6a-5c61c3cdd950)

![image](https://github.com/openai-translator/openai-translator/assets/19989300/70a2135e-2f1e-49da-9fbc-65bed3c7a790)

### 你看到了什么错误？What errors do you see?

![image](https://github.com/openai-translator/openai-translator/assets/19989300/e2966d04-c1e3-40a3-b78f-ee35bf4f8906)

### 你期望看到什么？What did you expect to see?

是我配置的不对吗？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by lordk911** [comment]
已解决，模型版本不是页面上显示的

**Comment by liaohuanxuan** [comment]
不是这个，模型版本在哪看呢？

**Comment by brucmao** [comment]
我也是us east，版本号写 2023-05-15一直提示错误
![image](https://github.com/openai-translator/openai-translator/assets/6119652/c7833f04-d106-4c11-a6a0-487077f85b61)

**Comment by timedtext** [comment]
@brucmao  我现在用的 api version 是 2023-07-01-preview

**Comment by brucmao** [comment]
api path 增加chat 就可以了
API URL路径: /openai/deployments/{部署模型你起的名称}/**chat**/completions?api-version=2023-07-01-preview

**Comment by szz65** [comment]
> api path 增加chat 就可以了 /openai/deployments/{部署模型你起的名称}/**chat**/completions?api-version=2023-07-01-preview

求问老哥你是怎么查看自己的api-version的？

**Comment by brucmao** [comment]
这个是固定的把，其实 2023-05-15和 2023-07-01-preview都是可以的
