### ISSUE TITLE
网页翻译

### ISSUE THREAD

**Issue by fredericky123** [openai-translator/openai-translator#885]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

希望能像G翻一样，翻译浏览器页面并在页面中替换原文显示

### 描述 Motivation

希望能像G翻一样，翻译页面并在页面中替换原文显示，方便阅读

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by maltoze** [comment]
duplicate of #5
