### ISSUE TITLE
支持 Claude2 等免费在线大模型

### ISSUE THREAD

**Issue by szh-bash** [openai-translator/openai-translator#887]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

如题

### 描述 Motivation

https://claude.ai

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by billng** [comment]
Yes, that's what I need too!
