### ISSUE TITLE
[Bug] {{TypeError: Cannot destructure property 'finish_details' of 'E.message' as it is undefined.}}

### ISSUE THREAD

**Issue by EnjoyWT** [openai-translator/openai-translator#895]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.23

### 系统/浏览器版本 System/Browser version

chrome 114.0.5735.198（正式版本） (arm64)

### 复现步骤 Reproduce step

昨天还可以正常使用， 直接划词后提示报错，免费版的chatGPT. 
已做检查
1. chatgpt 浏览器中可以正常使用
2. 插件更新了最新
3. 

### 你看到了什么错误？What errors do you see?

<img width="681" alt="截屏2023-07-20 10 24 59" src="https://github.com/openai-translator/openai-translator/assets/17864126/0e3bc862-5550-4662-9907-2f480c53e183">

### 你期望看到什么？What did you expect to see?

正常使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by jlurh** [comment]
我也出现了这个问题，昨天还能正常使用，今天就报这个错误。

**Comment by MGDSoft** [comment]
me too :(

**Comment by zhegeshijiehuiyouai** [comment]
me too too
