### ISSUE TITLE
希望添加个泰语翻译，中文翻译成泰文。

### ISSUE THREAD

**Issue by setmoney** [openai-translator/openai-translator#916]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

可以把中文翻译成泰文，目前还没有。

### 描述 Motivation

没

### Solution

没

### 还有其他内容吗？Anything else?

没

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="652" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/eb62b873-66ca-41cc-8a89-2fd6d960dae4">
