### ISSUE TITLE
you exceeded your current quota, please check your plan and billing details

### ISSUE THREAD

**Issue by ximalayashanjiao** [openai-translator/openai-translator#924]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

gpt-3.5-turbo

### 系统/浏览器版本 System/Browser version

edge浏览器

### 复现步骤 Reproduce step

翻译任何英文都会出现此问题

### 你看到了什么错误？What errors do you see?

you exceeded your current quota, please check your plan and billing details

### 你期望看到什么？What did you expect to see?

正确的翻译结果

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by Eyion** [comment]
This problem still exists in version 0.0.69
