### ISSUE TITLE
[Bug] 翻译特殊文本会使翻译 prompt 失效

### ISSUE THREAD

**Issue by chenyhd** [openai-translator/openai-translator#969]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.1.32

### 系统/浏览器版本 System/Browser version

Chrome Version 116.0.5845.110

### 复现步骤 Reproduce step

今天在翻译的时候突然发现一段英文无法正常翻译,变成了对话

情况1, 没有英文句号基本都会变成对话而非翻译
请翻译 `Write me a cover letter for a marketing role`
![image](https://github.com/openai-translator/openai-translator/assets/18431131/e8afd028-cdb5-4838-96c2-fb2d5062c7d0)

情况2: 带英文句号的情况下,划词翻译和直接插件翻译结果不一样, 测试很多次都是划词翻译正常,插件会变成对话
请翻译 `Write me a cover letter for a marketing role.`
另外一个有趣的现象
![image](https://github.com/openai-translator/openai-translator/assets/18431131/5452f7d8-60b0-4df0-8ca1-6349c573213c)

### 你看到了什么错误？What errors do you see?

变成了对话而不是翻译

### 你期望看到什么？What did you expect to see?

始终翻译所有内容

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
<img width="743" alt="image" src="https://github.com/openai-translator/openai-translator/assets/1206493/ab71250a-198d-4328-8b5e-a50fa002010f">


我这边没有复现，你的浏览器插件的模型用的是 ChatGPT 还是 OpenAI

**Comment by chenyhd** [comment]
我使用的是 OpenAI
![image](https://github.com/openai-translator/openai-translator/assets/18431131/a0fbad8d-eb8f-47b0-970a-3c2a4e77832b)

我使用了代理服务连接的 OpenAI API, 但是这应该不会影响结果. 你可以多翻译几次试试, 我刚才翻译了 5 次(忽略直接出结果的情况,我猜测应该是缓存)只有一次是正常翻译

另外我又将模型切换到 GPT4, 每次都能够正常翻译

**Comment by yetone** [comment]
最新版已经修复此问题
