### ISSUE TITLE
软件经常取不到词，多选择几次，多试几次又能取到，不稳定

### ISSUE THREAD

**Issue by TwoBrushes** [openai-translator/openai-translator#970]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the troubleshooting section in the README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator version

0.0.68

### 系统/浏览器版本 System/Browser version

windows11

### 复现步骤 Reproduce step

在pdf中用鼠标选取文本，然后再按翻译快捷键，软件翻译文本框中空白，多反复尝试几次又可以了

### 你看到了什么错误？What errors do you see?

无法取词

### 你期望看到什么？What did you expect to see?

期望能稳定运行

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
你使用的是 SnipDo 吗？

https://github.com/openai-translator/openai-translator/blob/main/CLIP-EXTENSIONS-CN.md#snipdo

**Comment by yetone** [comment]
建议使用 SnipDo

**Comment by shaojs321** [comment]
> 建议使用 SnipDo

用SnipDo的时候 PDF格式还是经常选不了，或者是选好之后翻译没反应，要多选几遍(不是那种扫描版的PDF是能编辑的)
