### ISSUE TITLE
输入框中的文本翻译成目标语言，可以扩展成按段落或者按句子分隔吗，这样可以在文本中边写边译了。

### ISSUE THREAD

**Issue by eric-cleath** [openai-translator/openai-translator#983]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

输入框中的文本翻译成目标语言，可以扩展成按段落或者按句子分隔吗，这样可以在文本中边写边译了。

### 描述 Motivation

可能是我不会用，或者没设计这个功能。

现在是按快捷键，会把输入结束以上全部内容翻译，如果补充一句话，会重头开始全部再翻译一遍，比较耗费流量。
现在的功能适合聊天工具，不太适合文本逐句输入。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
感谢建议，会加上这个功能的！

**Comment by eric-cleath** [comment]
期待🥰
