### ISSUE TITLE
优化建议：精简写作提示语

### ISSUE THREAD

**Issue by devyujie** [openai-translator/openai-translator#987]
### Search before asking

- [X] 在 [issues](https://github.com/yetone/openai-translator/issues) 中没有找到类似的内容。
I searched in the [issues](https://github.com/yetone/openai-translator/issues) and found nothing similar.

### feature

精简写作提示语

### 描述 Motivation

这句话太长了，感觉可以短一点。例如：please wait... ✍️
![image](https://github.com/openai-translator/openai-translator/assets/48620527/65e3fa2f-af35-4993-9137-6a3781d0f60e)

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by yetone** [comment]
为了告诉用户发生了啥并突出 OpenAI Translator 这个品牌，所以只能这样了
